### ISSUE TITLE
Revamp the marine DA verify task

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#1005]
- [ ] readjust the way the plots are made (scatter size too large, field plots need to improve cosmetically, ... )
- [ ] It times out regularly, needs to be faster
- [ ] Add times series of obs count, bias, mae and rmse global and per ocean basin

**Comment by AndrewEichmann-NOAA** [comment]
- State space figures
  - [x] figures for bkg  
  - [x] figures for currents
  - [x] different colorscales (finer scales for certain local intervals)
  - [x] contouring in slices
  - [ ] add sea ice figures (+ ice thickness and snow depth, ana and bkg)
  - [x] improve titles with everything (ana, bkg, inc, bkg err, etc.)
  - [ ] venture into tweaking eva plots (colorscale and x-axis scales)
- obs space
  - [x] ensmallen geographical scatterplot datapoints
  - [ ] obscounts on scatterplots and geographical plots
  - [ ] timeseries (mean abs error, rmse, bias)

**Comment by guillaumevernieres** [comment]
Example of color map for the bkg error:
https://docs.google.com/presentation/d/1dmYs0GCh1EEZ_x3wGATQSvRZreqIyE8M1ipoQ_zWAYc/edit#slide=id.p
