### ISSUE TITLE
JEDI ATM gfs and gdas init jobs fail because sevcsr is not present

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/GDASApp#1008]
According to the Hera GDA `/scratch1/NCEPDEV/global/glopara/dump` the sevcsr bufr dump has been zero length from 20221005 12Z to present.  GDAS-validation focuses on 20210801 00Z.  JEDI ATM protoype cycling focuses on near real-time cases (e.g., 20240224 00Z).

The prepatmiodaobs job detects a zero length sevcsr bufr dump file and does not attempt to convert bufr to ioda.  The gdas and gfs init job read `parm/atm/obs/lists/gdas_prototype_3d.yaml.j2` to determine which observation to process.  GDASApp commit [3ffc340](https://github.com/NOAA-EMC/GDASApp/commit/3ffc340fec25dcd53918194baac98226d01e1179) added `sevcsr` to `gdas_prototype_3d.yaml.j2`.  This works for dates prior to 20221005 12Z.  This does not work from 20221005 12Z forward.

Options
 - create a dynamic `gdas_prototype_3d.yaml.j2` that only contains observations which are present and are to be assimilated or monitored
 - modify JEDI ATM variational or local ensemble applications to skip over empty observation files
 - remove `sevcsr` from `gdas_prototype_3d.yaml.j2`
 - other ideas ...

The _remove_ option was choosen for the 20240224 00Z JEDI ATM CI case

**Comment by RussTreadon-NOAA** [comment]
@emilyhcliu and @azadeh-gh:  Since `sevcsr` bufr dumps are zero length from 20221005 12Z to present, I recommend removing 
```
{% include 'atm/obs/config/seviri_m08.yaml.j2' %}
{% include 'atm/obs/config/seviri_m11.yaml.j2' %}
```
from `parm/atm/obs/lists/gdas_prototype_3d.yaml.j2`.  Doing so allows real-time GDASApp ATM cycling to run without failure.  

**_Are you OK with me opening a PR to remove the `seviri` entries from `gdas_prototype_3d.yaml.j2`?_**

**Comment by emilyhcliu** [comment]
> @emilyhcliu and @azadeh-gh: Since `sevcsr` bufr dumps are zero length from 20221005 12Z to present, I recommend removing
> 
> ```
> {% include 'atm/obs/config/seviri_m08.yaml.j2' %}
> {% include 'atm/obs/config/seviri_m11.yaml.j2' %}
> ```
> 
> from `parm/atm/obs/lists/gdas_prototype_3d.yaml.j2`. Doing so allows real-time GDASApp ATM cycling to run without failure.
> 
> **_Are you OK with me opening a PR to remove the `seviri` entries from `gdas_prototype_3d.yaml.j2`?_**

@RussTreadon-NOAA Yes.  Please go ahead and remove `seviri` from `gdas_prototype_3d.yaml.j2` for runs after 2022100512.

**Comment by RussTreadon-NOAA** [comment]
Thank you @emilyhcliu for the green light.

Work for this change will be done in [RussTreadon-NOAA:feature/seviri](https://github.com/RussTreadon-NOAA/GDASApp/tree/feature/seviri)
