### ISSUE TITLE
Add a bufr2ioda ctest for insitu marine obs

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#102]
Follow the existing  [atm ctest for bufr2ioda]( https://github.com/NOAA-EMC/GDASApp/blob/6440f5324b7473b3d552f3a877501f99fe7124b8/test/atm/CMakeLists.txt#L9) and add a similar test [here](https://github.com/NOAA-EMC/GDASApp/blob/6440f5324b7473b3d552f3a877501f99fe7124b8/test/soca/CMakeLists.txt#L29)

**Comment by ShastriPaturi** [comment]
The yaml files used in GDASApp, ObsProc team and the one I used are different.
I am updating the yaml I used to generate the DBUOY IODA data with the yaml being used in GDASApp.

**Comment by ShastriPaturi** [comment]
@guillaumevernieres a bufr2ioda ctest has been added for insitu marine obs (empty file) for now.

(gdasapp) Orion-login-1[110] spaturi$ ctest -V -I 11,11
UpdateCTestConfiguration  from :/work/noaa/marine/Shastri.Paturi/sandbox/GDASApp                /build/test/DartConfiguration.tcl
UpdateCTestConfiguration  from :/work/noaa/marine/Shastri.Paturi/sandbox/GDASApp                /build/test/DartConfiguration.tcl
Test project /work/noaa/marine/Shastri.Paturi/sandbox/GDASApp/build/test
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 11
    Start 11: test_gdasapp_convert_bufr_dbuoy

11: Test command: /work/noaa/marine/Shastri.Paturi/sandbox/GDASApp/build/bin/buf                r2ioda.x "/work/noaa/marine/Shastri.Paturi/sandbox/GDASApp/build/test/testinput/                bufr_dbuoy.yaml"
11: Test timeout computed to be: 10000000
1/1 Test #11: test_gdasapp_convert_bufr_dbuoy ...   Passed    0.43 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.43 sec

Will add the file and test it when hera is returned.
