### ISSUE TITLE
SMAP converter produces the wrong datetime

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#1023]
The converted datetime looks off. Discovered while adding smap to the cycling.

**Comment by apchoiCMD** [comment]
From ```/scratch1/NCEPDEV/stmp2/Guillaume.Vernieres/runs/cp1/cp1.e/COMROOT/cp1.e/gdas.20210702/00/obs/gdas.t00z.sss_smap.2021070200.nc4```
min dateTime is `1625264512`
max dateTime is `1625281152`
Both are slightly off from the DA windows, do I point them out correctly?

**Comment by guillaumevernieres** [comment]
> From `/scratch1/NCEPDEV/stmp2/Guillaume.Vernieres/runs/cp1/cp1.e/COMROOT/cp1.e/gdas.20210702/00/obs/gdas.t00z.sss_smap.2021070200.nc4` min dateTime is `1625264512` max dateTime is `1625281152` Both are slightly off from the DA windows, do I point them out correctly?

Yes. It's possible that the original files are not in the correct place @apchoiCMD

**Comment by apchoiCMD** [comment]
> > From `/scratch1/NCEPDEV/stmp2/Guillaume.Vernieres/runs/cp1/cp1.e/COMROOT/cp1.e/gdas.20210702/00/obs/gdas.t00z.sss_smap.2021070200.nc4` min dateTime is `1625264512` max dateTime is `1625281152` Both are slightly off from the DA windows, do I point them out correctly?
> 
> Yes. It's possible that the original files are not in the correct place @apchoiCMD

Looking into it- Thanks @guillaumevernieres

**Comment by apchoiCMD** [comment]
Random Smap_converter test on `20231119.00`, Result shows reasonably well.

![image](https://github.com/NOAA-EMC/GDASApp/assets/141867620/c2d59ae4-a618-4289-bd1e-fb94f97cca73)
![image](https://github.com/NOAA-EMC/GDASApp/assets/141867620/f8fd5fb7-1f1f-4456-adab-87e4df937966)
