### ISSUE TITLE
Handling of missing files in OBS_YAML

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/GDASApp#1038]
Currently when loading `OBS_YAML` with `wxflow.YAMLFile`, if a line in `OBS_YAML` such as

`- !INC ${OBS_YAML_DIR}/insitu_profile_bathy.yaml`

points to a non-existant file, the script fails with the following error:

`FileNotFoundError: [Errno 2] No such file or directory: '/scratch1/NCEPDEV/da/Andrew.Eichmann/fv3gfs/insitu/global-workflow/sorc/gdas.cd/parm/soca/obs/config/insitu_profile_bathy.yaml`

This could be caught, but it is unclear how to handle the exception while using the rest of the possibly existing files in `OBS_YAML`. 

- Can we format `OBS_YAML` to not use the `INC` directive and just access the list of files, and load those individually? 
- Should some exception handling be requested for `wxflow.YAMLFile`? 
- Or do we want to preserve this level of brittleness?

**Comment by guillaumevernieres** [comment]
@AndrewEichmann-NOAA , what we have now is the correct behavior. It should fail if we're trying to assimilate an obs type that we don't know yet how to assimilate (indicated by the absence of a yaml file).
