### ISSUE TITLE
GDASApp develop build problem

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/GDASApp#1046]
Attempts to build GDASApp `develop` failed on Hera and Orion as [documented](https://github.com/NOAA-EMC/GDASApp/pull/1033#issuecomment-2058739950) in PR #1033.   The failure is related to EMC RZDM being down.

Commenting out the inclusion of testing in the GDASApp build via the following change to the top-level `CMakeLists.txt` 
```
index f4f2fd9..f369f04 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -40,4 +40,4 @@ option(WORKFLOW_TESTS "Include global-workflow dependent tests" OFF)
 add_subdirectory(ush)

 # Include testing.
-add_subdirectory(test)
+##add_subdirectory(test)
```
allows the GDASApp build to proceed.

**Comment by guillaumevernieres** [comment]
Happy to work on this, unless you are already on it @RussTreadon-NOAA or @CoryMartin-NOAA ?

**Comment by RussTreadon-NOAA** [comment]
I took a shortcut and simply commented out `add_subdirectory(test)` in hopes that EMC RZDM returns to service within the next few days.  Cory's suggestion of adding a file staging ctest to download input files and output references is a good idea.

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA do we just want to commit that hack for now so that full workflow testing can occur? or hope for the best with RZDM?

**Comment by CoryMartin-NOAA** [comment]
"real fix" is under testing now
