### ISSUE TITLE
Create a 0.25deg zeo iau incr

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#1076]

**Comment by guillaumevernieres** [comment]
FYI @JessicaMeixner-NOAA , I just copied the 0.25deg "zero" increment here: 
```/scratch2/NCEPDEV/ocean/Guillaume.Vernieres/data/static/1440x1080x75/soca/mom6_increment_zero.nc```

**Comment by JessicaMeixner-NOAA** [comment]
/scratch1/NCEPDEV/climate/Jessica.Meixner/cycling/IC_2021063000/gdas.20210630/00/analysis/ocean/gdas.t00z.ocninc.nc is now the zero inc
