### ISSUE TITLE
The gfs is not used as background (yet)

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#1078]
https://github.com/NOAA-EMC/GDASApp/blob/7ecfc17f9df39859b340c8ba81c3c27bfb5f18ac/ush/soca/bkg_utils.py#L104

Looks like I missed this when @AndrewEichmann-NOAA cleaned-up the background staging utility. The background for the DA should come from the `gdas` fcst, always.

**Comment by AndrewEichmann-NOAA** [comment]
d'oh
