### ISSUE TITLE
SOCA updates

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#1093]
We need to take care of the following when we decide to update to more recent version of develop:
- [x] the Rossby radius of deformation file was converted to netcdf
- [x] latlon from soca::Geometry is no more. It's used in the hybrid weight app
- [x] Might not be able to make a subset copy of an increment anymore (changes in ensemble stuff needed)
- [x] diffusion will be moved to oops, which will require some updates to diagb (probably not going to be merged soon ...)
- [x] diag B failing: ```Exception: Could not find edge 0 for Quadrilateral elem 0 with nodes ( 1 73 74 2 )```

**Comment by RussTreadon-NOAA** [comment]
Update the following GDASApp submodules to the head of their respective develop as of 13:30 EST on 5/17/2024
```
        modified:   fv3-jedi (new commits)
        modified:   ioda (new commits)
        modified:   iodaconv (new commits)
        modified:   oops (new commits)
        modified:   saber (new commits)
        modified:   soca (new commits)
        modified:   ufo (new commits)
        modified:   vader (new commits)
```
`build.sh -v` aborted with
```
In file included from /work2/noaa/da/rtreadon/git/global-workflow/update/sorc/gdas.cd/bundle/gdas-utils/soca/gdas_socahybridweights.cc(1):
/work2/noaa/da/rtreadon/git/global-workflow/update/sorc/gdas.cd/bundle/gdas-utils/soca/gdas_socahybridweights.h(34): error: class "soca::Geometry" has no\
 member "latlon"
        geom.latlon(lats, lons, halo);
             ^

compilation aborted for /work2/noaa/da/rtreadon/git/global-workflow/update/sorc/gdas.cd/bundle/gdas-utils/soca/gdas_socahybridweights.cc (code 2)
make[2]: *** [gdas-utils/soca/CMakeFiles/gdas_socahybridweights.x.dir/gdas_socahybridweights.cc.o] Error 2
make[2]: Leaving directory `/work2/noaa/da/rtreadon/git/global-workflow/update/sorc/gdas.cd/build'
make[1]: *** [gdas-utils/soca/CMakeFiles/gdas_socahybridweights.x.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

This is checklist item 2.

**Comment by guillaumevernieres** [comment]
Thanks for testing @RussTreadon-NOAA . I'll start working on this in a few mn ...

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres , no need to rush on a Friday afternoon.

**Comment by guillaumevernieres** [comment]
@RussTreadon-NOAA , do you have a branch I could submit a PR fix to? There's only 2 issues that I know need to be fixed, the latlon issue that you mention above and a ascii file that became netcdf and changed name ...

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres , I do not have a branch.  I'm working from a local copy of GDASApp `develop`.

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres , I just created GDASApp [feature/soca_update](https://github.com/NOAA-EMC/GDASApp/tree/feature/soca_update).  Feel free to push to this branch.

**Comment by RussTreadon-NOAA** [comment]
As a test, revert soca back to current GDASApp hash, [soca @ 18f7813](https://github.com/jcsda-internal/soca/tree/18f7813dc4eb5033dbba7bc0da65e3c9166fb5a4).  After this `./build.sh` completes.  Run `test_gdasapp` including g-w tests on Orion.  `test_gdasapp_atm_jjob_var_run` and `test_gdasapp_atm_jjob_ens_run` failed with
```
1: Exception: lapse_rate does not exist in ufo::PredictorFactory
1: Exception: oops::Variational<FV3JEDI, UFO and IODA observations> terminating...
1: Exception: level: 0
1: lapse_rate does not exist in ufo::PredictorFactory
```
Given the `var_run` and `ens_run` failures, the downstream `var_inc`, `var_final`, and `ens_final` also failed.  A partial answer to the failure is found in fv-3jedi PR [#1201](https://github.com/JCSDA-internal/fv3-jedi/pull/1201).  The var and ens failures will be addressed via a new GDASApp issue.

**Comment by CoryMartin-NOAA** [comment]
I think the VarBC predictors now are named like `lapseRate` rather than `lapse_rate`.

EDIT: guessing since you linked to the fv3-jedi PR you already knew that :-)

**Comment by guillaumevernieres** [comment]
@RussTreadon-NOAA , @CoryMartin-NOAA , I fixed the build issues, but I'm stuck with the diag B application failing. I'm going to postpone work on this until I talk to @travissluka later today.

**Comment by guillaumevernieres** [comment]
Fix is here: https://github.com/NOAA-EMC/GDASApp/tree/feature/submodules_soca
