### ISSUE TITLE
Move obs and fix files to Orion

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#1094]
We won't be able to cycle on orion and hercules until this is done.

### Fix files
Copy the soca fix files from
```
/scratch2/NCEPDEV/ocean/Guillaume.Vernieres/data/static/
```
to
```
/work/noaa/da/marineda/gfs-marine/data/static
```
excluding the offline ensemble ```/scratch2/NCEPDEV/ocean/Guillaume.Vernieres/data/static/1440x1080x75/soca/bkgerr/ens/```

### Obs 
Just copy over June-July-August 2021 to:
```/work/noaa/da/marineda/gfs-marine/data/obs```

**Comment by apchoiCMD** [comment]
Completion of copying what we need to `/work/noaa/da/marineda/gfs-marine/data`
