### ISSUE TITLE
Archive ocean history files on HPSS

### ISSUE THREAD

**Issue by KatherineLukens-NOAA** [NOAA-EMC/GDASApp#1105]
The model_data/ocean/history files are not archived on HPSS.

**Comment by AndrewEichmann-NOAA** [comment]
@KatherineLukens-NOAA Could you provide an `ls` of that directory to know what to save?

**Comment by KatherineLukens-NOAA** [comment]
@AndrewEichmann-NOAA /model_data/ocean/history/ should contain the following files (as an example):
gdas.ocean.t18z.inst.f000.nc
gdas.ocean.t18z.inst.f003.nc
gdas.ocean.t18z.inst.f006.nc
gdas.ocean.t18z.inst.f009.nc

**Comment by guillaumevernieres** [comment]
same thing for sea ice @AndrewEichmann-NOAA

**Comment by AndrewEichmann-NOAA** [comment]
@KatherineLukens-NOAA Could you point to your experiment again? I need to look at some logs to understand what is going on.

**Comment by KatherineLukens-NOAA** [comment]
Here is the experiment log directory: /scratch1/NCEPDEV/da/Katherine.Lukens/NSST/expts/ctl/ctl_Gbranch/COMROOT/ctl_Gbranch/logs/
