### ISSUE TITLE
Use JCB in the UFO test data script

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/GDASApp#1113]
https://github.com/NOAA-EMC/GDASApp/blob/3925f24c4b455683b13d2fcc253c1a2402a0d9ff/ush/ufoeval/run_ufo_hofx_test.sh#L188

**Comment by ADCollard** [comment]
I think this issue references [feature/jcb-darth-vader](https://github.com/NOAA-EMC/GDASApp/tree/feature/jcb-darth-vader).  I am re-testing this as we need to fix this issue.

**Comment by CoryMartin-NOAA** [comment]
Closed by #1256
