### ISSUE TITLE
soca gridgen is failing

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#1118]
Not sure what happened:
```
   what():  Cannot open gridgen.yaml  (No such file or directory)
```

**Comment by AndrewEichmann-NOAA** [comment]
I got gridgen to work in the letkf task, and the rest of the ctests of tasks that use it work still....

**Comment by guillaumevernieres** [comment]
Same here, but the `ci` reported an issue ... 
https://github.com/NOAA-EMC/GDASApp/pull/1114#issuecomment-2118265712

**Comment by guillaumevernieres** [comment]
... a glitch in the ci ... closing
