### ISSUE TITLE
Ocean Heat content

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#1147]
- write code to compute the ocean heat content from mom6's history files (python at first is OK). Start with [0-300]m and [300-1000] ... I'm open to other bounds that would make more sense.
- compare against the PSL replay to ORAS5 (time series, maps, ...)

**Comment by JohnSteffen-NOAA** [comment]
A python script compares ocean heat content 0-300m between the marine DA - GFSv17 prototype experiments to the ORAS5 replay:
/scratch1/NCEPDEV/da/John.Steffen/utils/heat_content/plot_ohc300m.py

Python environment used:
module use /scratch1/NCEPDEV/hwrf/save/Maria.Aristizabal/modulefiles
module load modulefile.graphics.run.hera

Sub routines and yaml configure:
constants.py
eos80.py
library.py
plot_ocean.yml

Example figures:
./figures/GFSv17_C03_2021071900_OHC300m_f006.png
./figures/GFSv17_C03_2021071900_OHC300m_differ_f006.png 

Possible updates could include a 300m-1000m heat content plot, time series plots, and other variable of interest (MLD, SSH, SSS, SST, etc.). In the HAFS application, all the figure production is controlled by a driver shell script.

**Comment by JohnSteffen-NOAA** [comment]
![GFSv17_C03_2021071900_OHC300m_f006](https://github.com/NOAA-EMC/GDASApp/assets/77806417/1651ca25-a6a4-453e-b4a0-b5bd44c8b70b)
![GFSv17_C03_2021071900_OHC300m_differ_f006](https://github.com/NOAA-EMC/GDASApp/assets/77806417/6cfbdae6-4b4e-4313-b335-53bea9ddb9bd)

**Comment by guillaumevernieres** [comment]
Thanks @JohnSteffen-NOAA

**Comment by guillaumevernieres** [comment]
- statistics over a specified time period
- time series 
- interpolate to the same vertical grid
