### ISSUE TITLE
Add B Error Templated YAML for Aerosol DA

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/GDASApp#116]
Using https://github.com/NOAA-EMC/GDASApp/blob/develop/parm/atm/berror/staticb_bump.yaml as an example, add in a templated YAML for static B from BUMP for global aerosol DA.

**Comment by CoryMartin-NOAA** [comment]
@andytangborn for a first go, I propose only creating a YAML for 'identity' **B** so that we don't have to worry about staging BUMP files, just to get the plumbing going.

**Comment by andytangborn** [comment]
Ok.  I've started on the BUMP yaml, but I can do ID as well, and use that
first.

**Comment by CoryMartin-NOAA** [comment]
Closed through #122
