### ISSUE TITLE
soca ctests failing

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/GDASApp#1192]
Install `develop` at 4c58b1e on Hera.  Run ctests with following failures
```
        1838 - test_gdasapp_soca_nsst_increment_to_mom6 (Failed)
        1842 - test_gdasapp_soca_JGLOBAL_PREP_OCEAN_OBS (Failed)
        1845 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN (Failed)
        1846 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_ECEN (Failed)
        1848 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT (Failed)
        1849 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_POST (Failed)
        1851 - test_gdasapp_soca_incr_handler (Failed)
```
This issue is opened to document changes needed to get the above tests passing.

**Comment by RussTreadon-NOAA** [comment]
g-w has moved to `task_config` instead of `runtime_config`.   Many soca scripts use `runtime_config`  See [comments](https://github.com/NOAA-EMC/global-workflow/pull/2700#issuecomment-2183461359) in g-w PR [#2700](https://github.com/NOAA-EMC/global-workflow/pull/2700).

**Comment by guillaumevernieres** [comment]
Thanks for the head's up @RussTreadon-NOAA

**Comment by RussTreadon-NOAA** [comment]
Work for this issue will be done in [RussTreadon-NOAA:feature/soca_ctests](https://github.com/RussTreadon-NOAA/GDASApp/tree/feature/soca_ctests)

**Comment by RussTreadon-NOAA** [comment]
Three sets of changes made to get soca ctests to pass
- Add `PYTHONPATH` with g-w `wxflow` to `test/soca/socaincr2mom6.sh`
- Correct `wxflow` `PYTHONPATH` in `ush/soca/run_jjobs.py`
- Replace `runtime_config` with `task_config` and `self.config` with `self.task_config` in `ush/soca` scripts

Build GDASApp with the above changes in g-w PR [#2700](https://github.com/NOAA-EMC/global-workflow/pull/2700).  48 out of 48 ctests pass
```
Test project /scratch1/NCEPDEV/da/role.jedipara/git/global-workflow/pr2700/sorc/gdas.cd/build
      Start 1488: test_gdasapp_util_coding_norms
 1/48 Test #1488: test_gdasapp_util_coding_norms ........................   Passed    3.13 sec
      Start 1489: test_gdasapp_util_ioda_example
 2/48 Test #1489: test_gdasapp_util_ioda_example ........................   Passed    3.95 sec

...

      Start 1868: test_gdasapp_atm_jjob_ens_final
47/48 Test #1868: test_gdasapp_atm_jjob_ens_final .......................   Passed   42.28 sec
      Start 1869: test_gdasapp_aero_gen_3dvar_yaml
48/48 Test #1869: test_gdasapp_aero_gen_3dvar_yaml ......................   Passed    0.80 sec

100% tests passed, 0 tests failed out of 48

Label Time Summary:
gdas-utils    =  11.96 sec*proc (11 tests)
script        =  11.96 sec*proc (11 tests)

Total Test time (real) = 2293.05 sec
```
