### ISSUE TITLE
Marine DA is broken

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#1199]
- wrong wxflow # in the g-w develop?   
- Machine identification in the CMakeLists doesn't work and is missing the container case
- something wrong with jcb, I must have not paid attention to possible required changes ... will comment out for now
- ~diag b is failing with ```Could not find edge 0 for Quadrilateral elem 0 with nodes ( 1 73 74 2 ) ``` I think I know why ... maybe~ Container related, so non-issue.
- ~probably more, but I can't debug the rest until I fix the bullet above ...~

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres , what is broken for marine DA?

As [reported](https://github.com/NOAA-EMC/global-workflow/pull/2700#issuecomment-2188584765) in g-w [PR #2700](https://github.com/NOAA-EMC/global-workflow/pull/2700), g-w C48mx500_3DVarAOWCDA CI was successfully run on Hera this morning (6/25/2024)
```
Hera(hfe02):/scratch1/NCEPDEV/stmp2/role.jedipara/EXPDIR/pr2700_wcda$ rocotostat -d pr2700_wcda.db -w pr2700_wcda.xml -c all -s
   CYCLE         STATE           ACTIVATED              DEACTIVATED
202103241200        Done    Jun 25 2024 09:45:12    Jun 25 2024 10:00:34
202103241800        Done    Jun 25 2024 09:45:12    Jun 25 2024 10:46:18
```

GDASApp ctests have also been successfully run under `role.jedipara` using PR [#2700](https://github.com/NOAA-EMC/global-workflow/pull/2700).  48 out of 48 tests pass.
```
Test project /scratch1/NCEPDEV/da/role.jedipara/git/global-workflow/pr2700/sorc/gdas.cd/build
      Start 1488: test_gdasapp_util_coding_norms
 1/48 Test #1488: test_gdasapp_util_coding_norms ........................   Passed    2.53 sec
      Start 1489: test_gdasapp_util_ioda_example
 2/48 Test #1489: test_gdasapp_util_ioda_example ........................   Passed    3.30 sec
...
      Start 1868: test_gdasapp_atm_jjob_ens_final
47/48 Test #1868: test_gdasapp_atm_jjob_ens_final .......................   Passed   42.77 sec
      Start 1869: test_gdasapp_aero_gen_3dvar_yaml
48/48 Test #1869: test_gdasapp_aero_gen_3dvar_yaml ......................   Passed    0.92 sec

100% tests passed, 0 tests failed out of 48

Label Time Summary:
gdas-utils    =  10.28 sec*proc (11 tests)
script        =  10.28 sec*proc (11 tests)

Total Test time (real) = 3529.03 sec
```

I do not know when PR [#2700](https://github.com/NOAA-EMC/global-workflow/pull/2700) will be merged into g-w `develop`

**Comment by guillaumevernieres** [comment]
I saw that, unexpected! Thanks for testing @RussTreadon-NOAA .
It looks like the g-w develop is pointing to the wrong wxflow #, I think the other issues are related to building with gnu in containers, which I had not done in a while.

**Comment by guillaumevernieres** [comment]
I just got things to work but I had to use wxflow develop instead of the hash in the g-w and jcb is not working. I commented out the jcb stuff for now since it's just there as demo code. Is that expected @RussTreadon-NOAA ?

**Comment by RussTreadon-NOAA** [comment]
It's been a while since I ran GDASApp using the hashes associated with g-w `develop`.  I'm not surprised that it doesn't work out out the box.  Hopefully PR [#2700](https://github.com/NOAA-EMC/global-workflow/pull/2700) will be merged into g-w `develop` soon.

**Comment by AndrewEichmann-NOAA** [comment]
Also, because the letkf task class script inherits `config` from `Analysis`, which is a child of `wxflow` `Task`, that has to be changed in g-w too

**Comment by guillaumevernieres** [comment]
> Also, because the letkf task class script inherits `config` from `Analysis`, which is a child of `wxflow` `Task`, that has to be changed in g-w too

Do what you have to do to make it work in your sandbox, but let's wait until the dust settles with @RussTreadon-NOAA 's pr 2700.

**Comment by guillaumevernieres** [comment]
Seems fine now
