### ISSUE TITLE
Populate other sources of ice concentration (S-NPP)

### ISSUE THREAD

**Issue by apchoiCMD** [NOAA-EMC/GDASApp#1224]
We need to populate obs of ice concentration (S-NPP) at least for June-July 2021 to `/scratch1/NCEPDEV/da/common`
```
NPR-MIRS-IMG_v11r4_npp_s20210601XXXXX_eXXXXX_cXXXXX
.
.
NPR-MIRS-IMG_v11r4_npp_s20210731XXXXX_eXXXXX_cXXXXX
```

**Comment by apchoiCMD** [comment]
Now available with two month of sets `202106 to 202107` at
```
/scratch1/NCEPDEV/da/common
```

**Comment by apchoiCMD** [comment]
Populated in `/scratch1/NCEPDEV/da/common`

**Comment by JohnSteffen-NOAA** [comment]
I don't see this data in the common directory

**Comment by apchoiCMD** [comment]
> I don't see this data in the common directory

Look for the file name convention like below,
```
NPR-MIRS-IMG_v11r4_npp_sYYYYMMDDHHMMSSS_eYYYYMMDDHHMMSSS_cYYYYMMDDHHMMSSS
```
in and from
```
/scratch1/NCEPDEV/da/common/gdas.20210630/00/ocean/icec
```

**Comment by apchoiCMD** [comment]
`2021.06.01.00Z to 2021.08.01.00Z` has been prepared
