### ISSUE TITLE
GDAS ocean post failed obs stats

### ISSUE THREAD

**Issue by JohnSteffen-NOAA** [NOAA-EMC/GDASApp#1265]
The GDAS ocean analysis post task is failing to produce the *stats.csv file. Here is a snippet from an example gdasocnanalpost.log file: 
```
2024-08-21 15:42:05,279 - WARNING  - root        : srun -l --export=ALL -n 1 /scratch1/NCEPDEV/da/John.Steffen/global-workflow-gv/sorc/gdas.cd/build/bin/gdassoca_obsstats.x diag_stats.yaml has failed
STDERR: srun: error: h12c52: task 0: Exited with exit code 1
```
This results in the downstream failure of the gdasarch task as it cannot find the *stats.csv file since it is not produced. Here is a sample log from the gdasarch task:
```
FileNotFoundError: FATAL ERROR: Required file, directory, or glob gdas.20210630/06/analysis/ocean/gdas.t06z.ocn.*.stats.csv not found!
```
A short-term band-aid is to comment out the following line for gdasarch to complete but this does not fix the source of the issue:
https://github.com/NOAA-EMC/global-workflow/blob/1b18f2f97eec24a8b3f817b7ef1b4caa2be24937/parm/archive/gdasocean_analysis.yaml.j2#L28

**Comment by guillaumevernieres** [comment]
I found the cause of the problem, it's failing in the processing of the insitu obs.
```console
[...]
Exception: level: 1
	Reason:	Variable not found.
	name:	oceanBasin
	source_column:	0
	source_filename:	/scratch2/NCEPDEV/ocean/Guillaume.Vernieres/sandboxes/global-workflow/sorc/gdas.cd/bundle/ioda/src/engines/ioda/src/ioda/Engines/ObsStore/Variables.cpp
	source_function:	std::shared_ptr<ioda::ObsStore::Variable> ioda::ObsStore::Has_Variables::open(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> &) const
	source_line:	234
	stacktrace:	
```
the `oceanbasin` variable is missing.
