### ISSUE TITLE
File output lacks OMA diagnostics after JEDI minimization

### ISSUE THREAD

**Issue by ypwang19** [NOAA-EMC/GDASApp#1273]
After running minimization with JEDI, the OMA variable was not written out to diagnostic files. Adding `prints frequency` to the `final section` in the YAMLs in GDASApp `parm` can turn on the OMA diagnostics. 

This issue is opened to track the changes needed to modify the YAMLs for minimization.

**Comment by RussTreadon-NOAA** [comment]
Work for this issue will be done in [`feature/anlomb_diag`](https://github.com/NOAA-EMC/GDASApp/tree/feature/anlmob_diag).

The following changes have been committed to `feature/anlomb_diag`
- 307a6d5 - add prints with frequency PT3H to `3dvar_fgat_gfs_aero.yaml.j2` and `3dvar_gfs_aero.yaml.j2` in `parm/aero/variational/`
- b57d559 - add `final_prints_frequency: PT3H` to `parm/atm/jcb-base.yaml.j2`
- 050add7 - add `final_prints_frequency: PT3H` to `parm/snow/jcb-base.yaml.j2`

**Comment by RussTreadon-NOAA** [comment]
Tagging @jiaruidong2017 for awareness.

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres , we have 
```
final:
  diagnostics:
    departures: oman
  increment:
```
in `parm/soca/3dvarfgat.yaml`.

Yaping and Cory found it necessary to add a `prints` section to get analysis minus observation diagnostics written to the diagnostic files.  For example, [`307a6d5`](https://github.com/NOAA-EMC/GDASApp/commit/307a6d5ce211b92ba2cd7a40b6b024f770135a6f) modified `parm/aero/variational/3dvar_fgat_gfs_aero.yaml.j2` to 
```
final:
  diagnostics:
    departures: anlmob
  prints:
    frequency: PT3H
  increment:
```

We may need to make a similar change in marine DA templates.

**Comment by RussTreadon-NOAA** [comment]
Initially surprising finding.   `test_gdasapp_atm_jjob_var_run` fails when run from g-w PR [#2805](https://github.com/NOAA-EMC/global-workflow/pull/2805) at [f445e28](https://github.com/NOAA-EMC/global-workflow/pull/2805/commits/f445e28d8e4d57222416b191e80651af5e1850da) with changes from `feature/anlomb_diag` added to `sorc/gdas.cd`.   

A check of the log file shows that the reference check fails
```
0: Run: Finishing oops::Variational<FV3JEDI, UFO and IODA observations> with status = 0
0: terminate called after throwing an instance of 'oops::TestReferenceMissingReferenceLineError'
0:   what():  TestReference: Missing reference file line corresponding to test output Line#:90
0: Test line: 'CostJb   : Nonlinear Jb = 0.0000033199535370'
srun: error: h21c46: task 0: Aborted (core dumped)
srun: Terminating StepId=66180083.0
```
With `prints` added to the yaml, we get the following extra printout
```
CostJb   : Nonlinear Jb = 0.0000033199535370
CostJo   : Nonlinear Jo(AMSUA N19) = 39476.8510817764617968, nobs = 73667, Jo/n = 0.5358824315063252, err = 6.2697697603632934
CostJo   : Nonlinear Jo(sondes) = 10639.2476170353256748, nobs = 4255, Jo/n = 2.5004107208073623, err = 10.9811231401273197
CostFunction: Nonlinear J = 50116.0987021317414474
```
This printout is not in `test/atm/global-workflow/3dvar.ref`.   Hence, the check throws an error and the test fails.

We need to update the atmosphere `3dvar.ref` as part of GDASApp PR #1274.

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres , not sure if adding 
```
  prints:
    frequency: PT3H
```
is something we want for marine DA but [b69af09](https://github.com/NOAA-EMC/GDASApp/commit/b69af0979a441dc19655d75ff085f32dfa43a713) adds this to the `finals` section of
- `parm/soca/marine-jcb-base.yaml`
- `parm/soca/variational/3dvarfgat.yaml`

We can revert this commit if it is not necessary / desired.

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA G doesn't have this issue because he has `output:` writing out the analysis states. Since we didn't do that from JEDI, we needed to add prints after a PR earlier this summer changed when the final diagnostics are computed.

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA , does this mean the `parm/soca` changes committed at [b69af09](https://github.com/NOAA-EMC/GDASApp/commit/b69af0979a441dc19655d75ff085f32dfa43a713) are **not** necessary?

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA I don't think they're necessary but I also don't think they will harm anything

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA , OK, I'll leave [b69af09](https://github.com/NOAA-EMC/GDASApp/commit/b69af0979a441dc19655d75ff085f32dfa43a713) alone.

**Comment by RussTreadon-NOAA** [comment]
@ypwang19 , do you have any more commits or changes to make to PR #1274?  If not, it's ready for review.

**Comment by ypwang19** [comment]
> @ypwang19 , do you have any more commits or changes to make to PR #1274? If not, it's ready for review.

It looks good to me, thank you!
