### ISSUE TITLE
Script to generate ensemble IC's

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#1290]
### Issue: Atmosphere Component Uncertainty

I'm not sure about how to proceed with the atmosphere component. @CatherineThomas-NOAA, could you provide some guidance?

### Task

Develop an application that performs the following tasks:

#### Input:
- Deterministic ocean and sea ice restart files
- Ensemble size
- B-matrix

#### Output:
- Structured deterministic and ensemble initial conditions (ICs). The ensemble ICs are copies of the deterministic ICs.
- Ocean increments generated by randomizing the B-matrix.
- **Directory structure**: Ensure that the output generates a directory structure that aligns with the requirements of the 1/2 cycle to start.

**Comment by AndrewEichmann-NOAA** [comment]
Couldn't this use `ufs_utils`, at least on the atmospheric side?

**Comment by guillaumevernieres** [comment]
> Couldn't this use `ufs_utils`, at least on the atmospheric side?

I have no idea @AndrewEichmann-NOAA , but I'm pretty sure the tools to do this for the atmosphere already exist.

**Comment by CatherineThomas-NOAA** [comment]
@AndrewEichmann-NOAA is correct.  The UFS_UTILS utility gdas_init will produce cold start ICs for the atmosphere.  It will create the directory structure expected by the global-workflow for both the deterministic and ensemble.  @guillaumevernieres I can provide more details if needed.
