### ISSUE TITLE
Move existing UFSDA scripts to GDASApp

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/GDASApp#13]
Both j-jobs/exscripts for atm analysis but also python ush scripts.

**Comment by CoryMartin-NOAA** [comment]
Copied everything in [feature/ufsda_files](https://github.com/NOAA-EMC/GDASApp/tree/feature/ufsda_files), still need to clean it up and add everything to cmake. @aerorahul any special way to handle j-jobs and ex-scripts in the cmake build? Would they just copy to build(install)/jobs and build(install)/scripts?

**Comment by aerorahul** [comment]
> Copied everything in [feature/ufsda_files](https://github.com/NOAA-EMC/GDASApp/tree/feature/ufsda_files), still need to clean it up and add everything to cmake. @aerorahul any special way to handle j-jobs and ex-scripts in the cmake build? Would they just copy to build(install)/jobs and build(install)/scripts?

See the `CMakeLists.txt` in obsproc [here](https://github.com/NOAA-EMC/obsproc/tree/develop/jobs)
`make install` would then copy the **relevant** files to the `INSTALL_PREFIX/jobs` directory.

**Comment by CoryMartin-NOAA** [comment]
Closed through #19 but still needs cleaned up and updated for this new app
