### ISSUE TITLE
Orion/Hercules clean up 

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#1307]
## /work2/noaa/ng-godas/
- [x] ```/work2/noaa/ng-godas/jhossen/```  ~Ask Jakir to move or~ delete (4.5T) . The actual owner is Shastri ...
- [x] ```/work2/noaa/ng-godas/spaturi/```   @apchoiCMD , do you have the permissions to cleanup Shastri's stuff?
- [x] ```/work2/noaa/ng-godas/yli/```    Ask Yongzuo to move this (468GB)
          ***-> Reduced to 214GB***
- [x] ```/work2/noaa/ng-godas/ufs_cpld_ensemble``` (166GB) Delete (owner is @liuxiao37k )

## /work2/noaa/marine/spaturi
- [x] ```/work2/noaa/marine/spaturi``` Delete

## /work2/noaa/da/
- [x] ```/work2/noaa/da/spaturi``` Delete
```
hercules-login-2:/work2/noaa/da/spaturi$ du -sh *
1.6M	cplusplus
39M	forNick
11T	fromHera
28G	hercules
37G	insitu_BUFR
12M	NCODA
350G	plots
3.1T	sandbox
```

**Comment by apchoiCMD** [comment]
I don't think I do both-
```
(gdasapp) orion-login-3[25] mindoc$ ls -ld spaturi/
drwxr-s--- 6 spaturi ng-godas 4096 Jul 31  2023 spaturi/
```
```
(gdasapp) orion-login-3[32] mindoc$ ls -ld spaturi/
drwxr-s--- 28 spaturi marine 4096 Feb  7  2023 spaturi/
```

**Comment by apchoiCMD** [comment]
@guillaumevernieres I got all permissions to clean/remove above folders- I will complete above this afternoon.

Update : Above checked folders have been removed-

**Comment by apchoiCMD** [comment]
Deleted all lists above-
