### ISSUE TITLE
Unable to build GDASApp on Hera

### ISSUE THREAD

**Issue by keenaneure** [NOAA-EMC/GDASApp#1318]
Attempted to build GDASApp on Hera,

The commands I followed from the README page are:
`git clone --recursive --jobs 8 --branch dev/gdasapp https://github.com/NOAA-EMC/global-workflow.git`

The pathway is:
/scratch1/BMC/wrfruc/eure

And I am pasting the command line output below:

`remote: Total 14253 (delta 2193), reused 2130 (delta 1909), pack-reused 11628 (from 1)        
Receiving objects: 100% (14253/14253), 40.27 MiB | 5.46 MiB/s, done.
Resolving deltas: 100% (9830/9830), done.
Submodule path 'sorc/gdas.cd/parm/jcb-algorithms': checked out 'df03b11da1701f1713959f9ffc29dd2ba66efe62'
remote: Enumerating objects: 69, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 69 (delta 2), reused 2 (delta 2), pack-reused 52 (from 1)
Unpacking objects: 100% (69/69), 7.55 KiB | 108.00 KiB/s, done.
From https://github.com/noaa-emc/jcb-gdas
 * branch            70c44e5631282a87e9c58eea14b4a3a98680222c -> FETCH_HEAD
Submodule path 'sorc/gdas.cd/parm/jcb-gdas': checked out '70c44e5631282a87e9c58eea14b4a3a98680222c'
Submodule path 'sorc/gdas.cd/sorc/crtm': checked out 'bb7adbfc4f3deadedac98743bcb4e18a2bca11f9'
Submodule path 'sorc/gdas.cd/sorc/femps': checked out '4f12677d345e683bf910b5f76f0df120ad27482d'
Submodule path 'sorc/gdas.cd/sorc/fms': checked out '1f739141ef8b000a0bd75ae8bebfadea340299ba'
Submodule path 'sorc/gdas.cd/sorc/fv3': checked out '47b766295682df2e53b59d0dd07b5c511b84dd67'
Submodule path 'sorc/gdas.cd/sorc/fv3-jedi': checked out 'b5dd092e22a1ec8efdddc2bfbd58628b695ad1c4'
Submodule path 'sorc/gdas.cd/sorc/fv3-jedi-lm': checked out 'af67095ee87ffb472218aa386e34c6bfe64ca424'
Submodule path 'sorc/gdas.cd/sorc/gsibec': checked out 'c8ac58d9b43eb8f890e565d12c88f1b0579c9ccd'
Submodule path 'sorc/gdas.cd/sorc/gsw': checked out '697cbeb7605d70ed3857664c5f54a5c05346e31f'
Submodule path 'sorc/gdas.cd/sorc/icepack': checked out '73136ee8dcdbe378821e540488a5980a03d8abe6'
Submodule path 'sorc/gdas.cd/sorc/ioda': checked out 'd4dc2cdaa944f2a8220fa5207968f0dab6c8b183'
Submodule path 'sorc/gdas.cd/sorc/iodaconv': checked out '7fb44969a419348ba07abad1544b443212fc8d6c'
Downloading etc/jcb-text.png (11 KB)
Error downloading object: etc/jcb-text.png (fdb18dd): Smudge error: Error downloading etc/jcb-text.png (fdb18ddd36bb2285c6e588ad94559babc318eba3e802b9e1c349fed18a3a82af): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to '/scratch1/BMC/wrfruc/eure/global-workflow/.git/modules/sorc/gdas.cd/modules/sorc/jcb/lfs/logs/20241010T163937.702531353.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: etc/jcb-text.png: smudge filter lfs failed
fatal: Unable to checkout 'faee9f4c029de3d9c9749ce5d12f4e97eb90c022' in submodule path 'sorc/gdas.cd/sorc/jcb'
fatal: Failed to recurse into submodule path 'sorc/gdas.cd'`

**Comment by CoryMartin-NOAA** [comment]
thanks @keenaneure @danholdaway @guillaumevernieres @aerorahul JCB's git-lfs things were not resolved apparently

**Comment by danholdaway** [comment]
@keenaneure what hash of JCB are you trying to get. That etc directory is not present anymore.

**Comment by keenaneure** [comment]
I am not sure. I was looking at the instructions for (eventually) running the BUFR2IODA converter instructions, part of which seems to require cloning GDASApp, [here](https://docs.google.com/document/d/1PQqM_CmoNWpd8xtDx0nNVnOkxNFmJaGrk8CD-WunVjM/edit?pli=1).
Perhaps these instructions are outdated, but this is all I know.

**Comment by CoryMartin-NOAA** [comment]
I think the problem is the `dev/gdasapp` branch. Can you try to just clone `develop`?

**Comment by keenaneure** [comment]
I cloned `develop` and that worked just fine. Thanks!
