### ISSUE TITLE
Add support for Gaea C6

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/GDASApp#1323]
we apparently have a huge allocation on Gaea C6. GDASApp needs to be updated to build on the C6 nodes

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA , are you able to build GDASApp `develop` at 6fb0a65 on Gaea?

I cloned `develop` at 6fb0a65 in /gpfs/f5/nggps_emc/scratch/Russ.Treadon/git/GDASApp/test.  I executed `nohup ./build.sh -f -v > build.log 2>&1 &` in `test/`.  The build fails with
```
-- ESMFMKFILE not defined. This is the path to esmf.mk file. Without this filepath, ESMF_FOUND will always be FALSE.
CMake Warning at jedicmake/CMakeModules/Modules/FindESMF.cmake:114 (message):
  ESMFMKFILE does not exist
Call Stack (most recent call first):
  da-utils/CMakeLists.txt:18 (find_package)


CMake Error at /autofs/ncrc-svm1_sw/gaea-c5/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/cmake-3.23.1-d2agejkeecr2btxpcjo\
aaab3tyoe42ax/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find ESMF (missing: ESMF_LIBRARY_LOCATION
  ESMF_INTERFACE_LINK_LIBRARIES ESMF_F90COMPILEPATHS) (Required is at least
  version "8.0.0")
Call Stack (most recent call first):
  /autofs/ncrc-svm1_sw/gaea-c5/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/cmake-3.23.1-d2agejkeecr2btxpcjoaaab3tyoe42ax\
/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  jedicmake/CMakeModules/Modules/FindESMF.cmake:121 (find_package_handle_standard_args)
  da-utils/CMakeLists.txt:18 (find_package)


-- Configuring incomplete, errors occurred!
See also "/gpfs/f5/nggps_emc/scratch/Russ.Treadon/git/GDASApp/test/build/CMakeFiles/CMakeOutput.log".
See also "/gpfs/f5/nggps_emc/scratch/Russ.Treadon/git/GDASApp/test/build/CMakeFiles/CMakeError.log".
```
Not sure if this is due to something in my Gaea environment or GDASApp `develop`

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA Gaea is tricky. You are trying on a C5 node, my PR was for a C6 node. You have to hit `ctrl+C` then specify `gaea6` to get a C6 login node. The C5 modulefile was added before the DA-Utils repo had the ESMF dependency, so that modulefile probably needs updated.

**Comment by RussTreadon-NOAA** [comment]
Thank you @CoryMartin-NOAA .  I logged into a C6 node.  I'm stuck.  I belong to the following groups: `ncep rstprod nggps_emc sudo_role.glopara sudo_role.jedipara`  I can not create any directories in `/gpfs/f6`.  I submitted my AIM request for `ira-sti` access.  I'll wait until this access is granted.

**Comment by CoryMartin-NOAA** [comment]
I suspect all C5 needs is a `load("esmf/8.5.0")` line added to the modulefile and then it should compile

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA , you are right.  After adding 
```

 load("fms/2023.04")
+load("esmf/8.5.0")
 load("atlas/0.35.1")
```
to `modulefiles/GDAS/gaea.intel.lua`, the C5 build works.   

Do we anticipate building and running on C5?  

If _yes_, I'll open a PR to get this one line change into `develop`.  If _no_, we should consider removing `modulefiles/GDAS/gaea.intel.lua`.  It does not work _as is_ but `gaeac6.intel.lua` works.

**Comment by CoryMartin-NOAA** [comment]
I think @jswhit2 has aspirations of running things on C5, so if it's a one line change, we can/should probably support it.
