### ISSUE TITLE
Cosmetic adjustment to the verify task

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#1349]
Summary of the "review" panel.

## State space figures
- [x] colorbars need to have the bounds as labels
- [x] use "pcolor" instead of contourf  for the horizontal plots
- [x] fill continent
- [ ] ~~use long name for the variables (low priority)~~
- [x] figure out the missing variables for None None None in the title
- [x] Missing units
- [x] Colormap should go from Blue to Red

### Increment
- [x] missing ocean incr
- [x] global seaice figure are wrong

### Backgrounds/Analysis
- [x] global figures are not correct
- [x] color scales for ice and snow depth are swapped: use [0, 4m] hor hice and [0, 0.5m] for hsnow
- [x] try [33, 41] psu for salinity
- [x] missing horizontal and meridional sections 

### Background error
- [x] skip the ensemble stuff if the files are not present, it's currently failing

### Background Error Location
- [x] point the `gdas.t00z.ocean.bkgerr_stddev.nc` file out under bmatrix/ocean from `comout`

## Obs space figures (EVA)
- [x] size of scatter dots is too large
- [x] check how to plot passive obs, color scales are wrong for omb's

**Comment by apchoiCMD** [comment]
@guillaumevernieres this animation is from Zonal section of bkgerr at Temp lat 0 for the July-

![ezgif com-animated-gif-maker](https://github.com/user-attachments/assets/ca96d447-6c3b-43a6-9da0-64dcb9cbf1eb)
