### ISSUE TITLE
Add land DA component to GDASApp (1)

### ISSUE THREAD

**Issue by jiaruidong2017** [NOAA-EMC/GDASApp#136]
- [x] Add a templated LETKF-OI YAML for global land DA
       Following the 3dvar_gfs_aero.yaml in parm/aero/variational/
- [x] Add Obs List YAML for snow observations to be assimilated
      Following the examples in parm/aero/obs/lists/
- [x] Modify the yamltool to generate the yaml file for the snow DA test. 
      Code: ush/ufsda/yamltools.py

**Comment by jiaruidong2017** [comment]
@CoryMartin-NOAA I tried to build the GDASApp, but it failed with the following error message:

```
-- Feature TESTS enabled
CMake Error at build/jedicmake/jedicmake-config.cmake:19 (message):
  File or directory
  /scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GDASApp/jedicmake/CMakeModules/Modules
  referenced by variable jedicmake_MODULES does not exist !
Call Stack (most recent call first):
  build/jedicmake/jedicmake-config.cmake:36 (set_and_check)
  crtm/CMakeLists.txt:20 (find_package)

-- Configuring incomplete, errors occurred!
See also "/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GDASApp/build/CMakeFiles/CMakeOutput.log".
```

The whole build message is as below:
[error_in_build_gdasapp.docx](https://github.com/NOAA-EMC/GDASApp/files/9678023/error_in_build_gdasapp.docx)

Thanks.

**Comment by RussTreadon-NOAA** [comment]
@jiaruidong2017 , this is a known problem.   It's been reported by Cory [(jedicmake #22](https://github.com/JCSDA-internal/jedi-cmake/issues/22)) and me ([GDASApp #140](https://github.com/NOAA-EMC/GDASApp/issues/140)).   Workarounds are being explored while we await final resolution.

**Comment by jiaruidong2017** [comment]
@RussTreadon-NOAA Thank you very much for your information.

**Comment by jiaruidong2017** [comment]
@CoryMartin-NOAA After I built the GDASApp package on hera, I tried to load the necessary modules as below: 

```
module use /scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GDASWork/GDASApp/modulefiles
module load GDAS/hera
```

However, I received the following error messages as below:
`
conda: Command not found.
`

I checked the modules loaded  as below:

>module list
```
Currently Loaded Modules:
  1) intel/2022.1.2                   13) pkg-config/0.27.1       25) bufr/11.7.1      37) atlas/0.30.0      49) libxaw/1.0.13
  2) stack-intel/2021.5.0             14) hdf5/1.12.1             26) git-lfs/2.10.0   38) sp/2.3.3          50) udunits/2.2.28
  3) impi/2022.1.2                    15) parallel-netcdf/1.12.2  27) ecbuild/3.6.5    39) gsl-lite/0.37.0   51) ncview/2.1.8
  4) stack-intel-oneapi-mpi/2021.5.1  16) netcdf-c/4.8.1          28) openjpeg/2.3.1   40) libjpeg/2.1.0     52) netcdf-cxx4/4.3.1
  5) cmake/3.22.1                     17) nccmp/1.9.0.1           29) eccodes/2.27.0   41) krb5/1.15.1       53) json/3.10.5
  6) curl/7.29.0                      18) netcdf-fortran/4.5.4    30) eigen/3.4.0      42) libtirpc/1.2.6    54) py-pybind11/2.8.1
  7) gettext/0.19.8.1                 19) antlr/2.7.7             31) openblas/0.3.19  43) hdf/4.2.15        55) hpc/1.2.0
  8) libunistring/0.9.10              20) gsl/2.7.1               32) eckit/1.19.0     44) jedi-cmake/1.4.0  56) miniconda3/4.6.14
  9) libidn2/2.3.0                    21) nco/5.0.6               33) fftw/3.3.10      45) libpng/1.6.37     57) gdasapp/1.0.0
 10) pcre2/10.39                      22) parallelio/2.5.7        34) fckit/0.9.5      46) libxt/1.1.5       58) GDAS/hera
 11) zlib/1.2.12                      23) wget/1.14               35) fiat/1.0.0       47) libxmu/1.1.2      59) netcdf/4.7.0
 12) git/2.37.0                       24) boost/1.78.0            36) ectrans/1.0.0    48) libxpm/4.11.0
```

Following the instructions, I proceed to conduct the run and I got the errors as below:

>ush/run_jedi_exe.py --config ush/examples/run_jedi_exe/3dhofx_hera.yaml
```
Traceback (most recent call last):
  File "ush/run_jedi_exe.py", line 9, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```
It seems there are some problems in the loaded modules. @CoryMartin-NOAA  Do you have any suggestions or comments? Thank you very much.

**Comment by jiaruidong2017** [comment]
@CoryMartin-NOAA Would you please change the permission  from `750` to `755` of your following directory?

`/scratch1/NCEPDEV/da/Cory.R.Martin/GDASApp/fix/bump/`
**drwxr-s---** 4 Cory.R.Martin **da** 4096 Jul  1 07:36 bump

I am conducting the GDASApp atm DA tests using your bump directory. My account is in the `global` group on hera, and I don't have access to your `dump` directory.  Thanks.

**Comment by CoryMartin-NOAA** [comment]
@jiaruidong2017 ok try it now, permissions updated.

**Comment by jiaruidong2017** [comment]
Thanks @CoryMartin-NOAA

**Comment by jiaruidong2017** [comment]
@CoryMartin-NOAA I tried to run `ush/genYAML` with the modified example configure file `ush/examples/run_jedi_exe/3dhofx_hera.yaml`, but I received the following errors: 

> ush/genYAML --config ush/examples/run_jedi_exe/3dhofx_hera.yaml

```
Traceback (most recent call last):
  File "ush/genYAML", line 29, in <module>
    genYAML(args.config)
  File "ush/genYAML", line 19, in genYAML
    output_file = all_config_dict['output']
KeyError: 'output'
```
The input yaml file is attached here. Do you have any sample input yaml file I can learn how to run the `genYAML`. Thank you very much.

[3dhofx_hera.yaml.txt](https://github.com/NOAA-EMC/GDASApp/files/9804785/3dhofx_hera.yaml.txt)

**Comment by CoryMartin-NOAA** [comment]
Check out https://github.com/NOAA-EMC/GDASApp/blob/develop/test/genYAML_prep.sh, @jiaruidong2017

**Comment by jiaruidong2017** [comment]
Thanks @CoryMartin-NOAA

**Comment by jiaruidong2017** [comment]
@CoryMartin-NOAA I generated the yaml file for the snow DA. However, when I conducted the JEDI run using this yaml file, the run failed with the following errors:

```
GeometryData: Global tree size = 55296, footprint = 3538944
Exception: Bad parameter: /obsdatain: Mandatory parameter 'engine' not found  (/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GDASWork/GDASApp/oops/src/oops/util/parameters/RequiredParameter.h +135 deserialize)
```
Do you have any comments and suggestions on how to fix the issues? Thank you very much.

Below the the yaml file and the output logfile:
[genYAML_output_letkfoi.yaml.docx](https://github.com/NOAA-EMC/GDASApp/files/9854419/genYAML_output_letkfoi.yaml.docx)
[stdout.jedi_letkf_snow.docx](https://github.com/NOAA-EMC/GDASApp/files/9854422/stdout.jedi_letkf_snow.docx)

**Comment by CoryMartin-NOAA** [comment]
This is due to a relatively new change in JEDI IODA. All of the IODA obsdatain and obsdataout files need to specify the `engine`. See the first 10 lines or so here: https://github.com/NOAA-EMC/GDASApp/blob/develop/parm/atm/obs/config/amsua_n19.yaml

**Comment by jiaruidong2017** [comment]
@CoryMartin-NOAA Got it. Thanks Cory.

**Comment by jiaruidong2017** [comment]
@CoryMartin-NOAA My run failed with new errors as below: 

```
GeometryData: Global tree size = 55296, footprint = 3538944
WARNING: string style datetime will cause performance degredation and will eventually be deprecated.
WARNING: Please update your datetime data to the epoch style representation using the new variable: MetaData/dateTime.
adpsfc_snow processed vars: 1 variables: totalSnowDepth
adpsfc_snow assimilated vars: 1 variables: totalSnowDepth

WARNING from PE     0: The function named string has been moved from fms_io_mod to fms_mod.  Please update your call.

Multiplicative inflation will be applied with multCoeff=1
RTPP inflation is not applied rtppCoeff is out of bounds (0,1], rtppCoeff=0
RTPS inflation is not applied rtpsCoeff is out of bounds (0,1], rtpsCoeff=0
Using EIGEN implementation of LETKF
Exception: Bad parameter: Bad conversion from std::string '150'90 150' to double  (/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/cache/build_stage/emc.nemspara/spack-stage-eckit-1.19.0-mhcpgdqqrzcypxnwzsgiusdqa42efhaw/spack-src/src/eckit/utils/Translator.cc +179 operator())
Exception: Bad parameter: Bad conversion from std::string '150'90 150' to double  (/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/cache/build_stage/emc.nemspara/spack-stage-eckit-1.19.0-mhcpgdqqrzcypxnwzsgiusdqa42efhaw/spack-src/src/eckit/utils/Translator.cc +179 operator())
Exception: Bad parameter: Bad conversion from std::string '150'90 150' to double  (/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/cache/build_stage/emc.nemspara/spack-stage-eckit-1.19.0-mhcpgdqqrzcypxnwzsgiusdqa42efhaw/spack-src/src/eckit/utils/Translator.cc +179 operator())
Exception: Bad parameter: Bad conversion from std::string '150'90 150' to double  (/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/cache/build_stage/emc.nemspara/spack-stage-eckit-1.19.0-mhcpgdqqrzcypxnwzsgiusdqa42efhaw/spack-src/src/eckit/utils/Translator.cc +179 operator())
Exception: Bad parameter: Bad conversion from std::string '150'90 150' to double  (/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/cache/build_stage/emc.nemspara/spack-stage-eckit-1.19.0-mhcpgdqqrzcypxnwzsgiusdqa42efhaw/spack-src/src/eckit/utils/Translator.cc +179 operator())
Exception: Bad parameter: Bad conversion from std::string '150'90 150' to double  (/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/cache/build_stage/emc.nemspara/spack-stage-eckit-1.19.0-mhcpgdqqrzcypxnwzsgiusdqa42efhaw/spack-src/src/eckit/utils/Translator.cc +179 operator())
Bad parameter: Bad conversion from std::string '150'90 150' to double caught in  (/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GDASWork/GDASApp/oops/src/oops/runs/Run.cc +192 execute)
Exception: oops::LocalEnsembleDA<FV3JEDI, UFO and IODA observations> terminating...
Bad parameter: Bad conversion from std::string '150'90 150' to double caught in  (/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GDASWork/GDASApp/oops/src/oops/runs/Run.cc +192 execute)
```
Do you have any clue on this issue? Thanks.

**Comment by guillaumevernieres** [comment]
@jiaruidong2017 , it looks like an issue with your buddy check filter. Check for recent `yaml` syntax changes in `ufo` for this specific filter.

**Comment by jiaruidong2017** [comment]
@guillaumevernieres Thank you for your suggestions. I took a look of the generated yaml file, and found the `observations` section was rearranged in an alphabetic order which made the `observations` section very mess. 
@guillaumevernieres @CoryMartin-NOAA Do you have any idea how to keep the all the sections in the original order. Thanks.

**Comment by CoryMartin-NOAA** [comment]
@jiaruidong2017 not currently, sorry. The YAML parsing tool puts it in alphabetical order. Perhaps a future one will be able to accommodate that.

**Comment by jiaruidong2017** [comment]
@CoryMartin-NOAA @guillaumevernieres My test runs failed with the new errors as following: 

```
adpsfc_snow totalSnowDepth nlocs = 1553, nobs = 1553, min = 0, max = 22, avg = 2
QC adpsfc_snow totalSnowDepth: 360 out of bounds.
QC adpsfc_snow totalSnowDepth: 1 out of domain of use.
QC adpsfc_snow totalSnowDepth: 4 black-listed.
QC adpsfc_snow totalSnowDepth: 4 rejected by first-guess check.
QC adpsfc_snow totalSnowDepth: 2 removed by buddy check.
QC adpsfc_snow totalSnowDepth: 1182 passed out of 1553 observations.
Beginning core local solver...
Assertion failed: geom_.extraFields().has_field("filtered_orography") in getOrography, line 77 of /scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GDASWork/GDASApp/fv3-jedi/src/fv3jedi/GeometryIterator/GeometryIterator.cc
Assertion failed: geom_.extraFields().has_field("filtered_orography") in getOrography, line 77 of /scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GDASWork/GDASApp/fv3-jedi/src/fv3jedi/GeometryIterator/GeometryIterator.cc
Assertion failed: geom_.extraFields().has_field("filtered_orography") in getOrography, line 77 of /scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GDASWork/GDASApp/fv3-jedi/src/fv3jedi/GeometryIterator/GeometryIterator.cc
Assertion failed: geom_.extraFields().has_field("filtered_orography") in getOrography, line 77 of /scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GDASWork/GDASApp/fv3-jedi/src/fv3jedi/GeometryIterator/GeometryIterator.cc
Assertion failed: geom_.extraFields().has_field("filtered_orography") in getOrography, line 77 of /scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GDASWork/GDASApp/fv3-jedi/src/fv3jedi/GeometryIterator/GeometryIterator.cc
Assertion failed: geom_.extraFields().has_field("filtered_orography") in getOrography, line 77 of /scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GDASWork/GDASApp/fv3-jedi/src/fv3jedi/GeometryIterator/GeometryIterator.cc

```
Do you have any idea on how to fix the issues? Thank you very much.

The yaml file and the output logfile are attached below:
[genYAML_output_letkfoi.yaml.pdf](https://github.com/NOAA-EMC/GDASApp/files/9864860/genYAML_output_letkfoi.yaml.pdf)
[stdout.jedi_letkf_snow2.pdf](https://github.com/NOAA-EMC/GDASApp/files/9864886/stdout.jedi_letkf_snow2.pdf)

**Comment by guillaumevernieres** [comment]
@jiaruidong2017 ... My guess is probably not as good as yours, but if you read the nice trace-back given to you, it looks like your geometry is missing a field called "filtered_orography". I'm just reading what's above.
That's a pretty nice trace back in your stdout file, read it and dig into your issue. Most likely a missing or wrong orography file?

**Comment by CoryMartin-NOAA** [comment]
Yeah I agree with G, @jiaruidong2017 there is probably something wrong with the `time invariant state fields` section of YAML or the field is not being read in properly from a file.

**Comment by jiaruidong2017** [comment]
@CoryMartin-NOAA @guillaumevernieres The issue resulted from the new change of the yaml file in the new JEDI package, which cause the input parameter file not accessible. I have fixed the issue and the test run went through now. Thank you very much for your help.
