### ISSUE TITLE
Add/fix build capability for Gaea-C5 and Gaea-C6

### ISSUE THREAD

**Issue by DavidBurrows-NCO** [NOAA-EMC/GDASApp#1360]
After the recent Gaea-C5 OS upgrade, GDASApp fails to build.
This issue corrects Gaea-C5 build and adds Gaea-C6 build capability (following ufs-wx-model https://github.com/ufs-community/ufs-weather-model/pull/2448).

Refs NOAA-EMC/global-workflow 3011 https://github.com/NOAA-EMC/global-workflow/issues/3011
Refs NOAA-EMC/global-workflow 3032 https://github.com/NOAA-EMC/global-workflow/pull/3032

**Comment by CoryMartin-NOAA** [comment]
C6 should already have a modulefile in develop, but C5 may need modified
