### ISSUE TITLE
Unable to build GDASApp on Cactus (post upgrade system)

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/GDASApp#1376]
Attempts to build GDASApp `develop` at [5fb52d3](https://github.com/NOAA-EMC/GDASApp/commit/5fb52d368aeda52b205e8323b4d2db7ff3082e70) on Cactus fail with an oops configuration error
```
-- ---------------------------------------------------------
-- Adding bundle project oops
-- ---------------------------------------------------------
-- [oops] (1.10.0)
-- Feature TESTS enabled
CMake Error at /apps/spack/cmake/3.20.2/intel/19.1.3.304/utnbptm3hrf7gppztidueu4jogfgemut/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES)
Call Stack (most recent call first):
  /apps/spack/cmake/3.20.2/intel/19.1.3.304/utnbptm3hrf7gppztidueu4jogfgemut/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /apps/spack/cmake/3.20.2/intel/19.1.3.304/utnbptm3hrf7gppztidueu4jogfgemut/share/cmake-3.20/Modules/FindOpenMP.cmake:542 (find_package_handle_standard_args)
  oops/CMakeLists.txt:56 (find_package)


-- Configuring incomplete, errors occurred!
See also "/lfs/h2/emc/da/noscrub/russ.treadon/git/GDASApp/develop/build/CMakeFiles/CMakeOutput.log".
See also "/lfs/h2/emc/da/noscrub/russ.treadon/git/GDASApp/develop/build/CMakeFiles/CMakeError.log".
```

The GDASApp `develop` build on Dogwood works.   Dogwood is scheduled to be upgraded 11/19-21/2024.  

Ticket #2024111410000051 has been submitted to the WCOSS2 helpdesk to report this problem.

**Comment by CoryMartin-NOAA** [comment]
FYI this is the same issue that has plagued Acorn for months...

**Comment by RussTreadon-NOAA** [comment]
> FYI this is the same issue that has plagued Acorn for months...

Oops, that's not a good sign.  We may wind up in the same situation on Dogwood by the end of next week.

**Comment by RussTreadon-NOAA** [comment]
**12/2/2024 update**

Update working copy of `develop` on Cactus to 76208eb.  Execute `nohup ./build.sh -v -f >build.log 2>&1 &` in `/lfs/h2/emc/da/noscrub/russ.treadon/git/GDASApp/develop`.  Build successfully ran to completion.  The previously reported oops configuration error did not occur.

**Comment by RussTreadon-NOAA** [comment]
Closing this issue because the reported problem no longer occurs on Cactus.
