### ISSUE TITLE
Correct content of ObsError in obs radiance file generated from GSI

### ISSUE THREAD

**Issue by ADCollard** [NOAA-EMC/GDASApp#138]
The test obs radiance files generated from the GSI contains the final GSI obs errors in ObsError/BrightnessTemperature.   We need the input obs errors that are presently located in the same file in MetaData/ObsError (they will have to be replicated for each observation before adding to the ObsError/BrightnessTemperature variable).

As the ObsError/BrightnessTemperature contained missing data (where obs were rejected in the GSI) we had some odd rejections for some tests with QCCode::missing (10) from UFO.

**Comment by CoryMartin-NOAA** [comment]
@ADCollard does this mean we need input obs errors *instead* for all of the radiance observations? If so, it should be a relatively minor fix/change in ioda-converters to do this.

**Comment by ADCollard** [comment]
@CoryMartin-NOAA I'm not sure what you mean by instead.  We do need the input obs errors in ObsError/BrightnessTemperature but they can stay in MetaData/ObsError if we wish.

I did an off-line correction to the obs file and this change does indeed remove the erroneous QCCode::missing (10)  from the UFO output.  Should I replicate/move this issue to ioda-converters?

**Comment by CoryMartin-NOAA** [comment]
Looks like the input error is what is used to compute ObsError/brightness_temperature:
https://github.com/JCSDA-internal/ioda-converters/blob/f6f3b0133fd658a5cac852a48ac3d0232e2c9a52/src/gsi-ncdiag/gsi_ncdiag.py#L1248

Is the issue that something is masking them through QC in the converter?

**Comment by ADCollard** [comment]
@CoryMartin-NOAA That piece of code will use Inverse_Observation_Error (which is the final error) as Input_Observation_Error is not available for radiance files.  What we actually need from the GSI diag file is error_variance.

**Comment by CoryMartin-NOAA** [comment]
ha, oh I can't read... my bad (the line above says input)

**Comment by CoryMartin-NOAA** [comment]
@ADCollard but yes, this should be a new issue in ioda-converters

**Comment by ADCollard** [comment]
@CoryMartin-NOAA OK, I'll create a new issue and (attempt) to fix.

ADC
