### ISSUE TITLE
Turn off g-w dependent reference checks on WCOSS2

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/GDASApp#1399]
Reference checks have been added to several GDASApp ctests.  g-w dependent ctests on WCOSS2 yield larger than expected differences with respect to the Hera generated reference files.  Given this, decide to turn off g-w dependent ctest reference checks on WCOSS2

This issue is opened to document this modification to the test templates.

**Comment by RussTreadon-NOAA** [comment]
Work for this issue will be done in [feature/reference_check](https://github.com/NOAA-EMC/GDASApp/tree/feature/reference_check)

**Comment by RussTreadon-NOAA** [comment]
**Question**

Should we allow reference checks to be **active** on all machines _except_ WCOSS2?

The commit at [2b01692](https://github.com/NOAA-EMC/GDASApp/commit/2b016927d546720118454453fdc4a1ecb4a372a2) turns off reference checks on all machines except Hera.

**Comment by DavidNew-NOAA** [comment]
@RussTreadon-NOAA Yes, I think as long as the Hera-derived reference checks pass on a machine, they should be active.

**Comment by RussTreadon-NOAA** [comment]
Change template logic to **turn off** reference check on WCOSS2.  Reference check remains active on all other machines.  Done at 7882ca8.
