### ISSUE TITLE
Unable to build GDASApp on Hera

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/GDASApp#140]
Attempts to build a fresh clone of GDASApp develop at [8e8d725](https://github.com/NOAA-EMC/GDASApp/commit/8e8d7257d6905108dfae820caa3ae1bf993e9269) on Hera via `./build.sh -v -t hera` fail with

```
-- [crtm] (2.3.0) [5c52ad0]
-- Feature TESTS enabled
CMake Error at build/jedicmake/jedicmake-config.cmake:19 (message):
  File or directory
  /scratch1/NCEPDEV/da/Russ.Treadon/git/GDASApp/work/jedicmake/CMakeModules/Modules
  referenced by variable jedicmake_MODULES does not exist !
Call Stack (most recent call first):
  build/jedicmake/jedicmake-config.cmake:36 (set_and_check)
  crtm/CMakeLists.txt:20 (find_package)


-- Configuring incomplete, errors occurred!
See also "/scratch1/NCEPDEV/da/Russ.Treadon/git/GDASApp/work/build/CMakeFiles/CMakeOutput.log".
```

The above error may be related to behavior reported in [jcsda-internal/jedi-cmake issue #22](https://github.com/JCSDA-internal/jedi-cmake/issues/22).  Recent communication in the jedi-cmake issue indicates that `spack-stack` will soon be installed on Hera.   A `spack-stack` status update has been requested in [NOAA-EMC spack-stack issue #339 ](https://github.com/NOAA-EMC/spack-stack/issues/339).   

 It seems installation of `spack-stack/1.1.0` should resolve GDASApp build issues on Hera.   `spack-stack/1.1.0` should also bring in `bufr/11.7.1` (see [hpc-stack issue #489](https://github.com/NOAA-EMC/hpc-stack/issues/489))     `bufr/11.7.1` is needed for the updated ioda-converters.

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA I'm wondering if this is due to the fact that JEDI-cmake now needs to be checked out recursively? 

This line: https://github.com/NOAA-EMC/GDASApp/blob/8e8d7257d6905108dfae820caa3ae1bf993e9269/CMakeLists.txt#L45

It might need to look like this:
```
ecbuild_bundle( PROJECT jedicmake GIT "https://github.com/jcsda/jedi-cmake.git" BRANCH develop UPDATE RECURSIVE )
include( jedicmake/cmake/Functions/git_functions.cmake )
```

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA , your suggested changes to the top level `CMakeLists.txt` works for the configuration step.   `./build.sh -v -t hera` gets to the make step.   The build eventually fails when compiling iodaconv code.  Here's the compilation error
```

/scratch1/NCEPDEV/da/Russ.Treadon/git/GDASApp/work/iodaconv/src/bufr/BufrParser/Query/DataProvider.cpp(47): error: identifier "get_isc_f" is undefined
              get_isc_f(&intPtr, &size);
              ^

/scratch1/NCEPDEV/da/Russ.Treadon/git/GDASApp/work/iodaconv/src/bufr/BufrParser/Query/DataProvider.cpp(50): error: identifier "get_link_f" is undefined
              get_link_f(&intPtr, &size);
              ^

/scratch1/NCEPDEV/da/Russ.Treadon/git/GDASApp/work/iodaconv/src/bufr/BufrParser/Query/DataProvider.cpp(53): error: identifier "get_itp_f" is undefined
              get_itp_f(&intPtr, &size);
              ^

/scratch1/NCEPDEV/da/Russ.Treadon/git/GDASApp/work/iodaconv/src/bufr/BufrParser/Query/DataProvider.cpp(56): error: identifier "get_typ_f" is undefined
              get_typ_f(&charPtr, &strLen, &size);
              ^

/scratch1/NCEPDEV/da/Russ.Treadon/git/GDASApp/work/iodaconv/src/bufr/BufrParser/Query/DataProvider.cpp(76): error: identifier "get_tag_f" is undefined
              get_tag_f(&charPtr, &strLen, &size);
              ^

/scratch1/NCEPDEV/da/Russ.Treadon/git/GDASApp/work/iodaconv/src/bufr/BufrParser/Query/DataProvider.cpp(84): error: identifier "get_jmpb_f" is undefined
              get_jmpb_f(&intPtr, &size);
              ^

/scratch1/NCEPDEV/da/Russ.Treadon/git/GDASApp/work/iodaconv/src/bufr/BufrParser/Query/DataProvider.cpp(88): error: identifier "get_inode_f" is undefined
          get_inode_f(bufrLoc, &inode_);
          ^

/scratch1/NCEPDEV/da/Russ.Treadon/git/GDASApp/work/iodaconv/src/bufr/BufrParser/Query/DataProvider.cpp(89): error: identifier "get_nval_f" is undefined
          get_nval_f(bufrLoc, &nval_);
          ^

/scratch1/NCEPDEV/da/Russ.Treadon/git/GDASApp/work/iodaconv/src/bufr/BufrParser/Query/DataProvider.cpp(91): error: identifier "get_val_f" is undefined
          get_val_f(bufrLoc, &dataPtr, &size);
          ^

/scratch1/NCEPDEV/da/Russ.Treadon/git/GDASApp/work/iodaconv/src/bufr/BufrParser/Query/DataProvider.cpp(94): error: identifier "get_inv_f" is undefined
          get_inv_f(bufrLoc, &intPtr, &size);
          ^

/scratch1/NCEPDEV/da/Russ.Treadon/git/GDASApp/work/iodaconv/src/bufr/BufrParser/Query/DataProvider.cpp(102): error: identifier "delete_table_data_f" is undefined
          delete_table_data_f();
          ^

/scratch1/NCEPDEV/da/Russ.Treadon/git/GDASApp/work/iodaconv/src/bufr/BufrParser/Query/DataProvider.cpp(116): error: identifier "nemdefs_f" is undefined
          nemdefs_f(fileUnit_,
          ^

/scratch1/NCEPDEV/da/Russ.Treadon/git/GDASApp/work/iodaconv/src/bufr/BufrParser/Query/DataProvider.cpp(142): error: identifier "nemtab_f" is undefined
              nemtab_f(bufrLoc_,
              ^

/scratch1/NCEPDEV/da/Russ.Treadon/git/GDASApp/work/iodaconv/src/bufr/BufrParser/Query/DataProvider.cpp(148): error: identifier "nemtbb_f" is undefined
              nemtbb_f(bufrLoc_,
              ^

compilation aborted for /scratch1/NCEPDEV/da/Russ.Treadon/git/GDASApp/work/iodaconv/src/bufr/BufrParser/Query/DataProvider.cpp (code 2)
make[2]: *** [iodaconv/src/bufr/CMakeFiles/ingester.dir/BufrParser/Query/DataProvider.cpp.o] Error 2
make[2]: Leaving directory `/scratch1/NCEPDEV/da/Russ.Treadon/git/GDASApp/work/build'
make[1]: *** [iodaconv/src/bufr/CMakeFiles/ingester.dir/all] Error 2
make[1]: Leaving directory `/scratch1/NCEPDEV/da/Russ.Treadon/git/GDASApp/work/build'
make: *** [all] Error 2
```

This looks like the issue reported on slide 2 of the [20220929 JEDI T2O](https://docs.google.com/presentation/d/1fWrIsO5TKkDnQfH6VaMxQkJJYG-PtJqbx1KstPf4ND0/edit?usp=sharing) slides.   

@guillaumevernieres is right.  We cannot build the current head of GDASApp on Hera.   Looks like we need to wait for `bufr/11.7.1 via `spack-stack/1.1.0`.

**Comment by RussTreadon-NOAA** [comment]
While not a solution, I found that the combination of @CoryMartin-NOAA 's suggested changes to `CMakeLists.txt` along with cloning a specific ioda-converters hash allows `./build.sh -t hera` to run to completion without any compilation errors.   

I backed up to ioda-converters `develop` @ [a29e1247](https://github.com/JCSDA-internal/ioda-converters/commit/a29e12476a0d4b4836b6be5148da1bec3f443934) (September 19, 2022 commit).  

I did not try ioda-converters `develop` hashes between a29e1247 and the current head, [b2b1f13](https://github.com/JCSDA-internal/ioda-converters/commit/b2b1f13a3c139497aa6695fa209d80a94c3b6728). It's possible that one or more of these hashes may also allow `./build.sh -t hera` to run to completion.

Again, this is **not** a solution.  It's a sensitivity.

**Comment by CoryMartin-NOAA** [comment]
Thanks for testing @RussTreadon-NOAA .  I think this means we need to do 2 things. 1) make that jedi-cmake change (that won't matter for when jedi-cmake is loaded as a module, but I think it's good to do so for completeness sake) and 2) switch to spack-stack once Dom has that installed on Hera (switch to using it on both Hera and Orion). I'll create issues if they don't already exist.

**Comment by CoryMartin-NOAA** [comment]
Created issues #141 and #142

**Comment by guillaumevernieres** [comment]
@CoryMartin-NOAA  and @RussTreadon-NOAA : I'm being bold and closing this issue!
