### ISSUE TITLE
Make jedi-cmake check out recursive

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/GDASApp#141]
Now that jedi-cmake has a submodule, ecbuild needs to checkout `jedi-cmake` recursively. This can be achieved with minimal changes to the top level `CMakeLists.txt` file.

**Comment by RussTreadon-NOAA** [comment]
Create branch [`feature/jedicmake`](https://github.com/NOAA-EMC/GDASApp/tree/feature/jedicmake) as a copy of `develop` at [8e8d725](https://github.com/NOAA-EMC/GDASApp/commit/8e8d7257d6905108dfae820caa3ae1bf993e9269).   The change to `CMakeLists.txt` will be made in `feature/jedicmake`.

**Comment by RussTreadon-NOAA** [comment]
**Build Tests**

Clone GDASApp `feature/jedicmake` on Hera.   Execute `./build.sh -t hera`.   The configuration step of the build successfully completed.   The compilation failed with undefined references in ioda-converters code.   

Repeat this test on Orion.  Execute `./build.sh -t orion`.   The configuration step of the build successfully completed.   The compilation failed with undefined functions in ioda-converters code.

Presumably building with `bufr/11.7.1` will resolve the ioda-converter compilation errors on both machines.  Currently the Hera and Orion builds load `bufr/noaa-emc-11.5.0`.

**Comment by CoryMartin-NOAA** [comment]
Closed through merge of #144
