### ISSUE TITLE
Start to use tags/hashes when checking out repositories

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/GDASApp#143]
GDASApp is starting to mature and people are using it for science/validation. Because of this, we should probably stop checking out 'develop' and instead switch to tags/hashes that we know build and update them as part of PRs.

Thoughts @RussTreadon-NOAA @guillaumevernieres or is this too premature?

**Comment by RussTreadon-NOAA** [comment]
While hofx and soca are maturing, the atmospheric workflow is not.   I've only tested plumbing.  I have not conducted any scientific validation of fv3jedi_var.x or fv3jedi_letkf.x.    If hofx and soca development are at point where tags make sense, tag.   Just my two cents.

**Comment by CoryMartin-NOAA** [comment]
Sorry @RussTreadon-NOAA if I wasn't clear, I don't mean tagging GDASApp, but rather checking out hashes of fv3-jedi, ufo, etc. so that we don't run into these issues where it no longer builds. Or do you think we still should proceed with always checking out develop as default?

**Comment by RussTreadon-NOAA** [comment]
Ooops.  You are right, @CoryMartin-NOAA.  I misread your comment.    

Is it safe to assume that what JCSDA promotes to `develop` in various [https://github.com/jcsda](https://github.com/jcsda)  repos works?    If so, we can replace _jcsda-internal_ references with _jcsda_ in the top-level GDASApp `CMakeLists.txt`.   

This said, even if _jcsda_ `develop` is safe to use, changes in `develop` might alter results.   This could invalidate our controls for ongoing GDASApp development.  Even if results aren't changed, `develop` updates can break GDASApp (e.g., change in yaml keywords).   Given this, now may indeed be the time to point the GDASApp `CMakeLists.txt` at specific tags or hashes.

Some questions to consider if we have GDASApp `CMakeLists.txt` clone specific tags or hashes:
- who decides which tags or hashes to use?    
- who periodically reviews the tags or hashes we use and updates the GDASApp `CMakeLists.txt`?
- how do we decide when to update the GDASApp `CMakeLists.txt`?

Developers are always able to edit their local copy of `CMakeLists.txt` to clone `develop` or different tags/hashes from _jcsda_ or _jcsda-internal_,  I foresee myself, for the time being, as someone who does this if we point `CMakeLists.txt` at specific tags or hashes.

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA JCSDA plans to do a 'release' tag of JEDI this week or next. Do we wait for that until attempting to use tags/hashes? Or do we do it ASAP because of the ioda-converters issue?

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA , what's the starting point for next week's EMC UFO code sprint?   If the code sprint needs a fixed & functional GDASApp, we need to identify this week which tags or hashes we plan on using.   If UFO developers already have a fixed & functional environment in which they can work, I'd wait for the JEDI release tag.

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA I'm inclined (based on what I think you're saying) to do it now then. I'm looking into `spack-stack` now, it looks like it is there on Hera and Orion. I will create a branch and try to tackle this issue and #142 together

**Comment by guillaumevernieres** [comment]
> GDASApp is starting to mature and people are using it for science/validation. Because of this, we should probably stop checking out 'develop' and instead switch to tags/hashes that we know build and update them as part of PRs.
> 
> Thoughts @RussTreadon-NOAA @guillaumevernieres or is this too premature?

Sorry @CoryMartin-NOAA and @RussTreadon-NOAA , I'm just seeing this issue. Could we add a `main` branch that would point to static repos? Seems to me that is the purpose intended for a `main` branch.

**Comment by CoryMartin-NOAA** [comment]
@guillaumevernieres so do you propose a main branch that is updated less frequently, and a develop branch that is used by 'power users' like us?

**Comment by guillaumevernieres** [comment]
@CoryMartin-NOAA yes, not sure at what frequency we would update it, but higher than what the quarterly JSCDA tags?

**Comment by CoryMartin-NOAA** [comment]
@guillaumevernieres is there a way to make the default branch for cloning `main` but the default branch for PRs to be `develop`?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres is there a way to make the default branch for cloning `main` but the default branch for PRs to be `develop`?

@CoryMartin-NOAA good question ... My google fu didn't come up with anything useful. Maybe we could restrict who can push to `main`, that would limit the # of people who would forget to switch to develop when submitting a PR . To be investigated ...

**Comment by CoryMartin-NOAA** [comment]
This was done in #146, can we close this issue?

**Comment by RussTreadon-NOAA** [comment]
Since #146 addressed this, I agree that we should close this issue.
