### ISSUE TITLE
Use a history file as initial condition for the pseudo model

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#172]
We are currently pointing to a restart for the IC's and MOM6 history output for the subsequent backgrounds. 
A test I did a while back using a history file in lieu of a restart failed, I tried again yesterday and it seems fine! 
- [x] Swap MOM.res.nc with a history file in the ```background``` definition for the ocean. This is going to simplify the 1/4 deg case where MOM6 dumps at least 4 restarts per checkpoint
- [x] Update the increment function: Thickness index name isn't  the same

**Comment by CoryMartin-NOAA** [comment]
Are they called 'diag' files in MOM6? Just as an FYI, our common nomenclature is:
- diag file: observation space statistics (IODA obsdataout for example)
- history file: model output that isn't a FMS RESTART file

**Comment by guillaumevernieres** [comment]
> Are they called 'diag' files in MOM6? Just as an FYI, our common nomenclature is:
> 
> * diag file: observation space statistics (IODA obsdataout for example)
> * history file: model output that isn't a FMS RESTART file

Good point @CoryMartin-NOAA , updating my jargon.
