### ISSUE TITLE
test_gdasapp_soca_ana_run failing on hera

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/GDASApp#174]
Is this expected?

Running ctest under develop with soca on hera results in the first six test passing, and then seven failing:

> The following tests FAILED:
> 	  7 - test_gdasapp_soca_ana_run (Failed)
> Errors while running CTest

The relevant errors seem to be:
> ls: cannot access /scratch1/NCEPDEV/da/Andrew.Eichmann/gdasapp/myGDASApp/build/test/soca/3dvar/analysis/Data/ocn.*3dvar*.incr*: No such file or directory
...
> ncks: ERROR file /scratch1/NCEPDEV/da/Andrew.Eichmann/gdasapp/myGDASApp/build/test/soca/3dvar/analysis/soca_gridspec.nc not found. 
...
> ncks: ERROR file /scratch1/NCEPDEV/da/Andrew.Eichmann/gdasapp/myGDASApp/build/test/soca/3dvar/analysis/Data/inc.nc not found. 

The build is under /scratch1/NCEPDEV/da/Andrew.Eichmann/gdasapp/myGDASApp/build/test/soca - it's a fork from today from develop.  The log is preserved in /scratch1/NCEPDEV/da/Andrew.Eichmann/gdasapp/myGDASApp/build/test/soca/LastTest.logSAVE

**Comment by guillaumevernieres** [comment]
You can't run that specific test on the login node @AndrewEichmann-NOAA , it's using `srun` with 2 cores. Just ignore that test for now or run it within an interactive queue.
