### ISSUE TITLE
Module file as used in GDASApp for building JEDI

### ISSUE THREAD

**Issue by jiaruidong2017** [NOAA-EMC/GDASApp#177]
I need to update the JEDI version in the land directory for offline land DA workflow, and we want to use the same modules as in the GDASApp. 
@CoryMartin-NOAA Would you please point me the modules used in the GDASApp I can use for building the JEDI? Thanks.

**Comment by guillaumevernieres** [comment]
@jiaruidong2017 There's a wiki here: [GDASApp-in-Standalone-Mode](https://github.com/NOAA-EMC/GDASApp/wiki/Using-GDASApp-in-Standalone-Mode:-Atmospheric-applications), most of it is probably still up to date. There's a section called **Build GDASApp**, it was written for us! Read it, most of what you need to know to build this repo and the JEDI bundle is explained in the wiki.

To load the modules, copy/pasted from the link above:

```console
module use modulefiles
module load GDAS/$platform
```

**Comment by jiaruidong2017** [comment]
@guillaumevernieres Thank you very much for your help. I could build the GDASApp successfully following the wiki help. 
I tried to build a standalone JEDI using the same modules as GDASApp with the following steps:

1. git clone https://github.com/JCSDA-internal/fv3-bundle.git fv3-bundle_20221102
2. cd fv3-bundle_20221102; mkdir build; cd build
3. module use /scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GDASWork/GDASApp/modulefiles
   module load GDAS/hera
4. ecbuild -DMPIEXEC_EXECUTABLE=`which srun` -DMPIEXEC_NUMPROC_FLAG="-n" ..

I received the following errors: 

```
-- Found OpenMP: TRUE (found version "5.0") found components: Fortran
CMake Error at fv3-jedi/CMakeLists.txt:74 (find_package):
  By not providing "Findcrtm.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "crtm", but
  CMake did not find one.

  Could not find a package configuration file provided by "crtm" (requested
  version 2.2.3) with any of the following names:

    crtmConfig.cmake
    crtm-config.cmake

  Add the installation prefix of "crtm" to CMAKE_PREFIX_PATH or set
  "crtm_DIR" to a directory containing one of the above files.  If "crtm"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/workflow/fv3-bundle_20221102/build/CMakeFiles/CMakeOutput.log".
See also "/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/workflow/fv3-bundle_20221102/build/CMakeFiles/CMakeError.log".
CMake Error: CTEST_USE_LAUNCHERS is enabled, but the RULE_LAUNCH_COMPILE global property is not defined.
Did you forget to include(CTest) in the toplevel CMakeLists.txt ?
```

@guillaumevernieres Did I miss something? Thanks again.

**Comment by CoryMartin-NOAA** [comment]
@jiaruidong2017 the issue is that now they turned off building CRTM in the bundle by default and want you to load it as a module.

```
option("BUNDLE_SKIP_CRTM" "Don't build CRTM" "ON") # Don't build crtm unless user passes -DBUNDLE_SKIP_CRTM=OFF
```

 My modulefile does not load CRTM, so you will need to either:
- edit the fv3-bundle CMakeLists.txt file and change `ON` to `OFF
- include `-DBUNDLE_SKIP_CRTM=OFF` in your ecbuild command

**Comment by jiaruidong2017** [comment]
@CoryMartin-NOAA I used the second option to include `-DBUNDLE_SKIP_CRTM=OFF` in my ecbuild command. It works now and both build and compile are successful. Thank you very much for your help.
