### ISSUE TITLE
Convert BUMP files to different layout

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#180]
I missed the memo completely, we can now convert our "bump" files to an arbitrary layout. Not high priority, but this needs to be done.

Pinging @andytangborn , since that might be of interest to you as well. I added you to the list of assignees, but feel free to remove yourself if this isn't something you plan to work on. 

The application to convert the bump files is still **ErrorCovarianceTraining**.
**Steps:**
1. Write global nicas and norm
```yaml 
write_nicas_global: true
write the NICAS norm file # not quite sure what the key is for that
``` 
when first generating the convolution weights
2. To generate the bump files for a different layout:
```yaml
load_nicas_global: true
write_nicas_local: true
```
Contact Benjamin befoer working on this.

**Comment by andytangborn** [comment]
Thanks. This will be really helpful.

**Comment by guillaumevernieres** [comment]
I don't think we're going to be using BUMP in the future @andytangborn . Closing this issues, but feel free to re-open if you need this feature.
