### ISSUE TITLE
Add land DA component to GDASApp (2)

### ISSUE THREAD

**Issue by jiaruidong2017** [NOAA-EMC/GDASApp#181]
- [x] Add a python code to create pseudo-ensemble for use in LETKF-OI
      Codes located in ush/land/create_ensemble/ 
      Reads in sfc_data restarts, and sets snowdepth to +/- perturbation, given stdev(ensemble) of B
- [x] Add IMS_proc/ 
      Code for processing IMS input ascii/netcdf files on the UFS model grid.
      Codes located in ush/land/IMS_proc/ 
      url = https://github.com/noaa-psd/land-IMS_proc.git

**Comment by jiaruidong2017** [comment]
When conducting the letkf_create_ens.py test using the GDASApp modules, It generated the ensembles successfully but came with the warning below: 

```
/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GDASWork/GDASApp/ush/land/create_ensemble/letkf_create_ens.py:32: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  var_array = ncOut.variables["snwdph"][:]
```
I did a web research and found that the warning comes because the NumPy package recently deprecated its `numpy.bool` in favor of the standard Python `bool`. There are two options: 
1) This is a harmless warning. If we can live with it, just leave it be.
2) If we can't stand the warning, we can silence the `DeprecationWarning` by add the following: 
```
from warnings import filterwarnings
filterwarnings(action='ignore', category=DeprecationWarning, message='`np.bool` is a deprecated alias')
```
@ClaraDraper-NOAA @CoryMartin-NOAA Which option do you prefer? Thanks.

**Comment by CoryMartin-NOAA** [comment]
@jiaruidong2017 I would probably just not worry about this for now and we will revisit it when this is closer to being in operations. My $0.02

**Comment by jiaruidong2017** [comment]
I conducted the `IMS_proc` test runs using your modules, but it failed with reading the IMS snowcover data as below:

> submit_job.sh
```
 lsm           2
 reading model backgroundfile:./20160104.180000.sfc_data.tile1.nc
 reading model backgroundfile:./20160104.180000.sfc_data.tile2.nc
 reading model backgroundfile:./20160104.180000.sfc_data.tile3.nc
 reading model backgroundfile:./20160104.180000.sfc_data.tile4.nc
 reading model backgroundfile:./20160104.180000.sfc_data.tile5.nc
 reading model backgroundfile:./20160104.180000.sfc_data.tile6.nc
 reading ASCII IMS snow cover data from
 /scratch2/NCEPDEV/land/data/DA/snow_ice_cover/IMS/2016/ims2016005_4km_v1.3.nc
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
calcfIMS           000000000042C0BA  Unknown               Unknown  Unknown
libpthread-2.17.s  00007F21E1E49630  Unknown               Unknown  Unknown
libnetcdff.so.6.2  00007F21E3551C70  netcdf_mp_nf90_ge     Unknown  Unknown
calcfIMS           0000000000410C7B  imsaggregate_mod_         581  IMSaggregate_mod.f90
calcfIMS           000000000040C6C1  imsaggregate_mod_         105  IMSaggregate_mod.f90
calcfIMS           000000000040BBB7  MAIN__                     46  driver_fIMS.f90
calcfIMS           000000000040B792  Unknown               Unknown  Unknown
libc-2.17.so       00007F21E178C555  __libc_start_main     Unknown  Unknown
calcfIMS           000000000040B6A9  Unknown               Unknown  Unknown
```
The `fims.nml` for this run is as below:
```
 &fIMS_nml
  idim=96, jdim=96,
  otype=oro_C96.mx100,
  jdate=2016005,
  yyyymmddhh=20160104.18,
  imsformat=2,
  imsversion=1.3,
  IMS_OBS_PATH="/scratch2/NCEPDEV/land/data/DA/snow_ice_cover/IMS/2016/",
  IMS_IND_PATH="/scratch2/NCEPDEV/land/data/DA/snow_ice_cover/IMS/index_files/"
  /
```
@ClaraDraper-NOAA Do you think anything I missed in above configures? I appreciate your any comments and suggestions. Thank you.

**Comment by CoryMartin-NOAA** [comment]
```
reading ASCII IMS snow cover data from
 /scratch2/NCEPDEV/land/data/DA/snow_ice_cover/IMS/2016/ims2016005_4km_v1.3.nc
```
ASCII but .nc? Is that a typo or is this supposed to be an ASCII file?

**Comment by jiaruidong2017** [comment]
@CoryMartin-NOAA The `IMS_proc` can read IMS snow cover data in both ASCII and netcdf formats. That is a typo in the output log file. Thanks.

**Comment by ClaraDraper-NOAA** [comment]
@jiaruidong2017 It's telling you where the code is failing, so it shouldn't be too hard for you to figure out what the problem is. Have you double-checked each entry in the namelist? I can't tell you if it's right or not, since I don't know the details of your experiment.

**Comment by jiaruidong2017** [comment]
This error was caused by the node running out of memory when I tried to conduct my test runs at C96 resolution. This runtime error was fixed by adding `ulimit` in the submit_job.sh.

**Comment by jiaruidong2017** [comment]
@ClaraDraper-NOAA When I tried to add the IMS_proc into the GDASApp, the configuring is incomplete with error message below. I checked the file `cmake/compiler_flags_Intel_Fortran.cmake`, and found there were a extra letter "B" at the beggining of the file as `B# (C) Copyright 2018 UCAR.`. I am not sure whether or not the crash was caused by this. Would you please remove the letter `B` from the file and let me know so that I could try it again? Thanks. 

@CoryMartin-NOAA When I tried to clone the IMS_proc code, it required me to input my username and password. Is it okay to use IMS_proc like this in the GDASApp or doing anything is required to avoid this? Thanks.

```
-- ---------------------------------------------------------
-- Adding bundle project land-imsproc
-- Cloning land-imsproc from https://github.com/NOAA-PSL/land-IMS_proc.git into /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp/land-imsproc...
Username for 'https://github.com': jiaruidong2017
Password for 'https://jiaruidong2017@github.com':
-- /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp/land-imsproc retrieved.
-- Updating land-imsproc to TAG 1a4608c...
-- git fetch --all @ /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp/land-imsproc
-- git fetch --all --tags @ /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp/land-imsproc
-- git checkout 1a4608c @ /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp/land-imsproc
-- ---------------------------------------------------------
-- [imsproc] (2022.10) [1a4608c]
-- Feature TESTS enabled
CMake Error at land-imsproc/cmake/compiler_flags_Intel_Fortran.cmake:2:
  Parse error.  Expected "(", got newline with text "

  ".
Call Stack (most recent call first):
  land-imsproc/cmake/imsproc_compiler_flags.cmake:16 (include)
  land-imsproc/CMakeLists.txt:16 (include)


-- Configuring incomplete, errors occurred!
```

**Comment by CoryMartin-NOAA** [comment]
@jiaruidong2017 this is actually a good point @ClaraDraper-NOAA the repo will need to be able to be cloned by everyone for use in GDAS. Can you make it a public facing repository? (it can obviously still live in NOAA-PSL but it needs to be readable by all)

**Comment by barlage** [comment]
@jiaruidong2017 if you look at the log, you'll see that this file (compiler_flags_Intel_Fortran.cmake) is actually created by @jkbk2004

**Comment by ClaraDraper-NOAA** [comment]
@jiaruidong2017 I removed the extra B. If you need any other changes made, it'd be better for you to create a fork, and work from that fork initially. Then once you have it working, issue a PR to update my code.  As Mike said, Jong is the person to ask about the CMake files. I don't think it works out of the box on hera, but Jong will know (and can help you fix it). 

@CoryMartin-NOAA it should not be public. I'll switch all the others later today.

**Comment by jkbk2004** [comment]
@jiaruidong2017 can you point me to the path you are working on hera? So that we may work together for debugging.

**Comment by jkbk2004** [comment]
@jiaruidong2017 I will take a look: /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp

**Comment by jiaruidong2017** [comment]
> @jiaruidong2017 I removed the extra B. If you need any other changes made, it'd be better for you to create a fork, and work from that fork initially. Then once you have it working, issue a PR to update my code. As Mike said, Jong is the person to ask about the CMake files. I don't think it works out of the box on hera, but Jong will know (and can help you fix it).
> 
> @CoryMartin-NOAA it should not be public. I'll switch all the others later today.

@ClaraDraper-NOAA Thank you and will work from my fork.

**Comment by jiaruidong2017** [comment]
> @jiaruidong2017 I will take a look: /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp

Thanks @jkbk2004. Yes, that is my temporary working directory.

**Comment by jiaruidong2017** [comment]
@ClaraDraper-NOAA I have successfully built the GDASApp with the IMS_proc including your fix from my fork and an executable file was created. I will conduct the test runs to reproduce the results from the offline land DA workflow. Thanks again. 

@jkbk2004 My working directory is at `/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.1/` on hera.

**Comment by jkbk2004** [comment]
@jiaruidong2017 does "./build.sh -t hera" go thru the build on hera? Can you save command line history?

**Comment by jiaruidong2017** [comment]
> @jiaruidong2017 does "./build.sh -t hera" go thru the build on hera? Can you save command line history?

@jkbk2004 Yes, it went through the build process on hera. How can I save the command line history?

**Comment by jkbk2004** [comment]
@jiaruidong2017 @CoryMartin-NOAA `CMake Error at /scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/cmake-3.22.1-mpovvsm/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES)`

**Comment by jiaruidong2017** [comment]
@jkbk2004 I saved the command line history at /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.1/command_line_history.log

**Comment by jiaruidong2017** [comment]
@jkbk2004 When you use cmake to build `land-IMS_proc`, you don't use both `build.sh` and `hera_modules` in the `land-IMS_proc` packages. Is it correct? Thanks.

**Comment by jkbk2004** [comment]
@jiaruidong2017 On landDA side, the cmake requirement is fairly easy: ecbuild and compiler. But I think the build errors I keep seeing is about stack issue, since it struggles to find all build environment variables and packages for some of GDAS bundle component `CMake Error at /scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/cmake-3.22.1-mpovvsm/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES)
Call Stack (most recent call first):
  /scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/cmake-3.22.1-mpovvsm/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/cmake-3.22.1-mpovvsm/share/cmake-3.22/Modules/FindOpenMP.cmake:544 (find_package_handle_standard_args)
  oops/CMakeLists.txt:56 (find_package)`

**Comment by jiaruidong2017** [comment]
Split this into other issues
