### ISSUE TITLE
[Bug] PR 145 broke this repo

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#184]
I should have paid attention! @jiaruidong2017 , your changes below L180: 
https://github.com/NOAA-EMC/GDASApp/blob/2712a22aa81788d85e14cac358de12956a75d238/ush/ufsda/yamltools.py#L181
broke this repo.

It would have been avoidable had we triggered the `ci`, the `soca_run` test is broken again.

@jiaruidong2017 : My `concern` is that I can easily `fix` what you broke, but I have no idea how to not break it for you, since you/we did not add a ctest that covers your code changes. I'll do my "best" to try to maintain the functionality you added, but at the end of the day, the burden of fixing that bug is on you. 

This could also have been avoided in my last PR, which was merged after #145 , but I did not contain the latest commit and missed that bug as well ... I just added a github reminder that will warn us when the branch that we want to merge is behind develop.

**Comment by jiaruidong2017** [comment]
@guillaumevernieres Thank you for letting me know the issues and sorry for making any inconvenience for you. Sure, please make your changes for fixing what I broke, and let me know once you commit your changes. I will make a quick test run to do a check from my end. Thanks again.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres Thank you for letting me know the issues and sorry for making any inconvenience for you. Sure, please make your changes for fixing what I broke, and let me know once you commit your changes. I will make a quick test run to do a check from my end. Thanks again.

No worries @jiaruidong2017 , I'll ping you in my next pr.
