### ISSUE TITLE
Marine obs yaml files

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#194]
It's time to copy these [`yaml` files](https://github.com/NOAA-EMC/godas/tree/develop/soca/obs) and modify them to work with the `GDASApp`.

**Comment by ShastriPaturi** [comment]
@guillaumevernieres we need to add the yamls for bufr insitu (ships, shipsu, dbuoy and mbuoyb, to start with). It may not be complete.

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres Are these the obs in the soca test that are not assimilated at this point?

**Comment by guillaumevernieres** [comment]
@AndrewEichmann-NOAA , nope, these are in our database but not in the test. This issue is just about converting the yamls from what's needed in soca-sci to what we need in this repo.

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres @ShastriPaturi 
I have an intial commit for an example yaml here:
https://github.com/NOAA-EMC/GDASApp/blob/feature/marine-obs-yaml-files/parm/soca/obs/config/sst_drifter.yaml

Couple of questions:

- Should the _letkf block go?
- The yamls in godas have list dashes - should those be removed? Are they handled differently by GDASApp?

**Comment by ShastriPaturi** [comment]
@AndrewEichmann-NOAA the yaml looks fine to me.
I am ok with keeping the yaml as is,  unless @guillaumevernieres has any other suggestion.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres @ShastriPaturi I have an intial commit for an example yaml here: https://github.com/NOAA-EMC/GDASApp/blob/feature/marine-obs-yaml-files/parm/soca/obs/config/sst_drifter.yaml
> 
> Couple of questions:
> 
> * Should the _letkf block go?
> * The yamls in godas have list dashes - should those be removed? Are they handled differently by GDASApp?

Good questions @AndrewEichmann-NOAA !
- The letkf block should not be part of the gdasapp obs yaml yet, so yes, good call.
- nope, looks good

What I should do is show you how to run the stand alone application so you can actually test those yamls ...

**Comment by ShastriPaturi** [comment]
Please add me to your tutorial @guillaumevernieres

**Comment by guillaumevernieres** [comment]
> @AndrewEichmann-NOAA the yaml looks fine to me. I am ok with keeping the yaml as is, unless @guillaumevernieres has any other suggestion.

sorry, just seeing your comment @ShastriPaturi . We want to remove what we know we don't want. The letkf block is one thing we certainly don't want to carry around.

**Comment by AndrewEichmann-NOAA** [comment]
@ShastriPaturi @guillaumevernieres 
There are varying degrees of overlap between the godas marine and existing GDASApp yamls, namely 

- adt_j3_egm2008.yaml
- icefb_GDR.yaml
- salt_profile_fnmoc.yaml 
- sss_smap_jpl.yaml
- sst_drifter.yaml 
- sst_noaa19_l3u.yaml
- temp_profile_fnmoc.yaml

Generally the godas versions would add QC filters. Should I adapt the godas versions (and test with the existing soca in GDASApp) or leave alone what is already in GDASApp?

**Comment by guillaumevernieres** [comment]
@AndrewEichmann-NOAA , we do need to update the gdasapp yamls with whatever filtering we've been doing so far.
