### ISSUE TITLE
Harmonization/reorganization of observation sources in soca test

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/GDASApp#196]
As noted in https://github.com/NOAA-EMC/GDASApp/pull/193 certain observation files need to be renamed or reorganized for consistency.

One item is the following, introduced by @ShastriPaturi :

The bufr_<dbuoy,,mbuoyb>prof.YYYYMMDD.nc has both sea_water_temperature and sea_water_salinity. Since the composite obsspace yaml is not implemented yet, I would suggest to rename the yamls as: temp_bufr_<dbuoy,mbuoyb>prof.YYYYMMDD.nc with sea_water_temperature & salt_bufr_<dbuoy,mbuoyb>prof.YYYYMMDD.nc with sea_water_salinity

Others changes may be added as necessary (@guillaumevernieres ?)

**Comment by AndrewEichmann-NOAA** [comment]
@ShastriPaturi You refer to the yaml files here while using the nc files as examples - I presume you mean to rename the yaml files also, along the same pattern.

One thing I notice is that the bufr2ioda yaml files in test/testinput/ have the same names as the analysis-prep stage files in parm/soca/obs/config/ . Is this necessary? It seems to have a lot of potential for confusion.
@guillaumevernieres

**Comment by guillaumevernieres** [comment]
@AndrewEichmann-NOAA . We can only do 1 "obsspace" per yaml for now, I think that's what @ShastriPaturi is referring to. Is there a way to only output 1 variable with the bufr2ioda converter?

**Comment by ShastriPaturi** [comment]
> @AndrewEichmann-NOAA . We can only do 1 "obsspace" per yaml for now, I think that's what @ShastriPaturi is referring to. Is there a way to only output 1 variable with the bufr2ioda converter?

Exactly @guillaumevernieres. Yes, it can be done @guillaumevernieres. @AndrewEichmann-NOAA can use only temp/saln in the QUERY and the variables and write out one files for each obsspace.
