### ISSUE TITLE
Prepare test data for snow DA prototyping/unit testing

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/GDASApp#201]
- [ ] C96 (preferably C48) land surface restart files
- [ ] low resolution/subsetted observation files

**Comment by CoryMartin-NOAA** [comment]
Are the files in here usable: /scratch1/NCEPDEV/da/Cory.R.Martin/CI/GDASApp/data/lowres ?

**Comment by guillaumevernieres** [comment]
@CoryMartin-NOAA , the ocean backgrounds are probably ok, but I'll need to sub-sample the obs.

**Comment by CoryMartin-NOAA** [comment]
@guillaumevernieres sorry I meant this specifically for land DA :-), I will adjust the title accordingly because I somehow missed adding that

**Comment by jiaruidong2017** [comment]
> Are the files in here usable: /scratch1/NCEPDEV/da/Cory.R.Martin/CI/GDASApp/data/lowres ?

@CoryMartin-NOAA They are usable if we go with C48 resolution. But the required IMS index file is not available yet at C48 for the test. I checked and found the IMS index files are only available at C96 and C384 now. Do you want me to make the tests at t18z cycle of 20210323 by using these restart files? 

@barlage Would you please help to add the IMS index_file to the following directory at:
/scratch2/NCEPDEV/land/data/DA/snow_ice_cover/IMS/index_files/

**Comment by CoryMartin-NOAA** [comment]
C48 would be great if it is not too much trouble, that way we can use this one set for ocean, land, atmosphere (and eventually aerosols). If it is a lot of work, C96 is fine for now, especially if the file size of C48 is already too big to store on RZDM (it might not be!)

**Comment by jiaruidong2017** [comment]
IMS OBS: 
`/scratch2/NCEPDEV/land/data/DA/snow_ice_cover/IMS/2021/ims2021083_4km_v1.3.nc`

Dimension: 6144 by 6144
Data format: netcdf
byte IMS_Surface_Values(time, y, x)
file size=567,046

**IMS Index file:**
`/scratch2/NCEPDEV/land/data/DA/snow_ice_cover/IMS/index_files/IMS4km_to_FV3_mapping.oro_C48.mx100.nc`

File size=4.1 MB

**Comment by jiaruidong2017** [comment]
**GTS OBS:** (Global vesus Subsets)
/scratch2/NCEPDEV/land/data/DA/snow_depth/GTS/data_proc/

```
Global:                               Report #         File size
Adpsfc_snow_2021032300.nc4		3,326		371,308
Adpsfc_snow_2021032306.nc4		4,186		488,534
Adpsfc_snow_2021032312.nc4		2,950		338,751
Adpsfc_snow_2021032318.nc4		2,641		326,012
```
```
Finland: Lat: [52,72] Lon: [20,32]     Report #	        File size
Adpsfc_snow_2021032300.nc4		1,129		139,573
Adpsfc_snow_2021032306.nc4		1,229		155,851
Adpsfc_snow_2021032312.nc4		1,102		138,741
Adpsfc_snow_2021032318.nc4		1,165		144,742
```
```
Russia: Lat: [50,70] Lon: [80,160]       Report #	File size
Adpsfc_snow_2021032300.nc4		  470		  81,665
Adpsfc_snow_2021032306.nc4		  19		  30,974
Adpsfc_snow_2021032312.nc4		  8		  30,974
Adpsfc_snow_2021032318.nc4		  6		  30,974
```
