### ISSUE TITLE
Generate marine DA plots using EVA in the GDASApp

### ISSUE THREAD

**Issue by mjhossen** [NOAA-EMC/GDASApp#202]
- [ ] Modify the existing python tool in the GDASApp [gen_eva_obs_yaml.py](https://github.com/NOAA-EMC/GDASApp/blob/develop/ush/eva/gen_eva_obs_yaml.py) to generate obs space plots using a valid ```var.yaml``` from marine DA experiments
- [ ] create eva templates for the marine obs
- [ ] test the generated yaml with eva

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres I have this plotting from the soca ctest results, with a couple of issues:

- The `marine_gdas_plots.yaml` in `feature/eva_emcpy` expects the group `PreQC`, which looks right, but the nc files in the ctest have `PreQc`. Which to use?
- The only existing `var.yaml`, in `build/test/soca/3dvar/ocnanal_12/`, points to observation files in `build/test/soca/3dvar/ocnanal_12/diags/`, but with everything being under g-w the existing ones are in `gw/testrun/testjjobs/ROTDIRS/gdas_test/gdas.20180415/12/ocean/diags/`. Is there a jjob-oriented `var.yaml` getting deleted? I thought `WIPE_DATA="NO"` would prevent that.
- In the following section in the original `marine_gdas_plots.yaml`...

```
    # Generate omb that passed QC for JEDI
    - transform: accept where
      new name: experiment::@GRPNAME@PassedQC::${variable}
      starting field: experiment::@GRPNAME@::${variable}
      where:
        - experiment::PreQC::${variable} == 0
      for:
        variable: *variables
```
...I replaced `@GRPNAME@` with `ombg`. Is this what is desired?

**Comment by guillaumevernieres** [comment]
- `PreQC` seems correct, I must have messed up the conversion of the test obs. Not sure why it's not failing in the var test.
- Ha! yes ... the post j-job bombs the rundir, and the var.yaml. Oops! You'll need to add a step in the post j-job to save the var.yaml in the rotdir. One more reason to move the j-jobs in this repo while we're sorting out these type of issues ...
-  yes, `ombg` is a good start.
