### ISSUE TITLE
test_gdasapp_soca_ana_prep failing on salt_profile_fnmoc

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/GDASApp#205]
A soca test in freshly pulled build of develop results in the following:

>   obs_type:
>            salt_profile_fnmoc
>   provider: gdasapp
>   target_file: /scratch1/NCEPDEV/da/Andrew.Eichmann/gdasapp/soca-test-rename-bufr-obs/build/test/soca/3dvar/gdas.t12z.salt_profile_fnmoc.2018041512.nc4.0
>   time_window: P1D
>   type:     ob
>   user_date_format:
> 
> 2022-11-23 15:54:19,220 - INFO - r2d2 - Starting
> 2022-11-23 15:54:19,222 - INFO - localdb - shared: fetch from /scratch1/NCEPDEV/da/Andrew.Eichmann/gdasapp/soca-test-rename-bufr-obs/build/test/soca/obs/r2d2-shared/gdasapp/ob/soca/P1D/2018-04-15/gdasapp.soca.ob.P1D.salt_profile_fnmoc.2018-04-15T00:00:00Z.nc4 to /scratch1/NCEPDEV/da/Andrew.Eichmann/gdasapp/soca-test-rename-bufr-obs/build/test/soca/3dvar/gdas.t12z.salt_profile_fnmoc.2018041512.nc4.0
> 2022-11-23 15:54:19,224 - INFO - r2d2 - Success
> 
> 2022-11-23 15:54:19:INFO:Concatenating 2 files from globbing /scratch1/NCEPDEV/da/Andrew.Eichmann/gdasapp/soca-test-rename-bufr-obs/build/test/soca/3dvar/gdas.t12z.salt_profile_fnmoc.2018041512.nc4*
> Traceback (most recent call last):
>   File "/scratch1/NCEPDEV/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/site-packages/xarray/core/dataset.py", line 1395, in _construct_dataarray
>     variable = self._variables[name]
> KeyError: 'sea_surface_temperature'
>

**Comment by ShastriPaturi** [comment]
@AndrewEichmann-NOAA, the file:
gdas.t12z.salt_profile_fnmoc.2018041512.nc4 should have "sea_water_salinity"

**Comment by guillaumevernieres** [comment]
Dang ... Thanks for pointing that out @AndrewEichmann-NOAA . I "probably" forgot a few steps in the concatenation logic.
