### ISSUE TITLE
Extend functionality of run_jedi_exe.py

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/GDASApp#223]
Make run_jedi_exe script more generic/flexible to exercise more components

**Comment by CoryMartin-NOAA** [comment]
Sounds like we are going to 'abandon' run_jedi_exe

**Comment by RussTreadon-NOAA** [comment]
While we may abandon `run_jedi_exe.py` in the long term, I have changes which restore the 3dvar functionality.   Branch [`feature/runjedi`](https://github.com/NOAA-EMC/GDASApp/tree/feature/runjedi) has been created to hold these updates.   We can decide later if we want to open a PR to merge `feature/runjedi` into `develop`.

**Comment by guillaumevernieres** [comment]
> While we may abandon `run_jedi_exe.py` in the long term, I have changes which restore the 3dvar functionality. Branch [`feature/runjedi`](https://github.com/NOAA-EMC/GDASApp/tree/feature/runjedi) has been created to hold these updates. We can decide later if we want to open a PR to merge `feature/runjedi` into `develop`.

I vote for merging your changes @RussTreadon-NOAA . I added a script that will run the soca jjobs [here](https://github.com/NOAA-EMC/GDASApp/blob/develop/ush/soca/run_jjobs.py) that takes as input an ordered list of [j-jobs](https://github.com/NOAA-EMC/GDASApp/blob/develop/ush/soca/examples/run_jjobs_hera.yaml), but it will take some work to make it generic enough to run the other jedi applications.

**Comment by RussTreadon-NOAA** [comment]
92d21cc adds `ush/ufsda/genYAML.py` and updates `run_jedi_exe.py` to access `genYAML` via import.    

`ush/genYAML` and `ush/ufsda/genYAML.py` are virtually identical.    It does not make sense to retain both.   Removal of `ush/genYAML` needs to be done with care.   GDASApp dependencies on `ush/genYAML` need to be updated and tested.   It is also necessary to update and test UFS-DA scripts in global-workflow which reference `genYAML`.

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA I think just the last 5 lines of `ush/genYAML` + a new `import` line are all that are needed to keep downstream uses of genYAML satisfied without redundant lines of code. But this will need to be tested.

**Comment by RussTreadon-NOAA** [comment]
OK, let me try.  Thank you @CoryMartin-NOAA for your help in sorting this out.

**Comment by RussTreadon-NOAA** [comment]
PR #278 restored the ability of `run_jedi_exe.py` to run 3dvar.   `feature/runjedi` was deleted upon closure of PR #278.

Continued work in this issue will be done in [`feature/runexe`](https://github.com/NOAA-EMC/GDASApp/tree/feature/runexe).

**Comment by RussTreadon-NOAA** [comment]
Change title of issue to more accurately describe the scope of this issue.

**Comment by guillaumevernieres** [comment]
> Change title of issue to more accurately describe the scope of this issue.

@RussTreadon-NOAA , we should remove the part that I added a while back that runs the "ex_script", it isn't needed anymore.

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres , are you referring to the `gw_scripts` GDASApp mode?   
```
./run_jedi_exe.py:    supported_app_modes = ['hofx', 'variational', 'gw_scripts']
./examples/run_scripts/soca1deg.yaml:GDASApp mode: gw_scripts
./examples/run_scripts/soca025.yaml:GDASApp mode: gw_scripts
./examples/run_scripts/soca5deg.yaml:GDASApp mode: gw_scripts
```

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres , are you referring to the `gw_scripts` GDASApp mode?
> 
> ```
> ./run_jedi_exe.py:    supported_app_modes = ['hofx', 'variational', 'gw_scripts']
> ./examples/run_scripts/soca1deg.yaml:GDASApp mode: gw_scripts
> ./examples/run_scripts/soca025.yaml:GDASApp mode: gw_scripts
> ./examples/run_scripts/soca5deg.yaml:GDASApp mode: gw_scripts
> ```

Yes, `gw_scripts` isn't needed anymore. What's under the else statement [run_jedi_exe.py#L149](https://github.com/NOAA-EMC/GDASApp/blob/7c77f1a88714003ba72d7266a6df9f2c426aafbc/ush/run_jedi_exe.py#L149) can be removed ... I think.
