### ISSUE TITLE
Use `${PDY}${cyc}` instead of `${CDATE}`?

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#237]
can we please use `${PDY}${cyc}` instead of `${CDATE}`?
We will eventually deprecate the use of `${CDATE}` in favor of the above.

_Originally posted by @aerorahul in https://github.com/NOAA-EMC/GDASApp/pull/236#discussion_r1044605036_

See this issue for more details: [global-workflow](https://github.com/NOAA-EMC/global-workflow/issues/198)

**Comment by AndrewEichmann-NOAA** [comment]
Addressed by https://github.com/NOAA-EMC/GDASApp/pull/252 and https://github.com/NOAA-EMC/global-workflow/pull/1191
