### ISSUE TITLE
debug in ioda converter

### ISSUE THREAD

**Issue by jiaruidong2017** [NOAA-EMC/GDASApp#238]
When the ioda converter is used to convert IMS snow depth data in netcdf format into the ioda format under GDASApp settings, the commands are as below: 

```
IMS_IODA=${EXECDIR}/imsfv3_scf2ioda.py
echo 'do_landDA: calling ioda converter'
python ${IMS_IODA} -i IMSscf.${YYYY}${MM}${DD}.${TSTUB}.nc -o ${JEDIWORKDIR}ioda.IMSscf.${YYYY}${MM}${DD}.${TSTUB}.nc
```
It failed with the following error messages: 

```
Traceback (most recent call last):
  File "/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GDASWork/GDASApp/build/bin/imsfv3_scf2ioda.py", line 23, in <module>
    import ioda_conv_engines as iconv
  File "/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GDASWork/GDASApp/build/lib/pyiodaconv/ioda_conv_engines.py", line 2, in <module>
    import ioda_obs_space as ioda_os
ModuleNotFoundError: No module named 'ioda_obs_space'
```
Any idea? Thanks.

**Comment by CoryMartin-NOAA** [comment]
@jiaruidong2017 you need to add the `ioda_obs_space` to your `$PYTHONPATH` environment variable. This is probably something like `export PYTHONPATH=$PYTHONPATH:/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GDASWork/GDASApp/build/lib/python3.7/pyioda/
`

However, looking here, I don't see it at all, perhaps it requires running `make` inside of `ioda`? I assume you didn't run the build script with the option to build everything?

**Comment by jiaruidong2017** [comment]
@CoryMartin-NOAA I conducted my test run at the working directory: /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.5/build/. I got the same error message as below. I checked and found there were `ioda_obs_space` available `build/lib/python3.7/pyioda/`. Do you mean I need to add `export PYTHONPATH=$PYTHONPATH:/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.5/build/lib/python3.7/pyioda/` into `/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.5/modulefiles/GDAS/hera.lua`? Thanks.

```
1292: do_landDA: calling ioda converter
1292: Traceback (most recent call last):
1292:   File "/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.5/build/bin/imsfv3_scf2ioda.py", line 23, in <module>
1292:     import ioda_conv_engines as iconv
1292:   File "/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.5/build/lib/pyiodaconv/ioda_conv_engines.py", line 2, in <module>
1292:     import ioda_obs_space as ioda_os
1292: ModuleNotFoundError: No module named 'ioda_obs_space'
1/1 Test #1292: test_gdasapp_land_imsproc ........***Failed    1.98 sec
```

**Comment by CoryMartin-NOAA** [comment]
No you do not want to add it to the modulefile, it needs to be added at runtime since it is part of the build.

**Comment by jiaruidong2017** [comment]
@CoryMartin-NOAA Yes, you are right. I just added to my script, and it worked. The test passed with some warning as below: 

```
1292: /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.5/build/bin/imsfv3_scf2ioda.py:94: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
1292: Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
1292:   sndv = ncd.variables['IMSsnd'][:]
1/1 Test #1292: test_gdasapp_land_imsproc ........   Passed   17.80 sec

The following tests passed:
        test_gdasapp_land_imsproc

100% tests passed, 0 tests failed out of 1
```
Is it okay to have these warning? Thank you very much.

**Comment by CoryMartin-NOAA** [comment]
@jiaruidong2017 yes I think it is fine for now (I think you've even seen this warning before if I recall)

**Comment by jiaruidong2017** [comment]
@CoryMartin-NOAA Yes, that is in the `test_gdasapp_land_create_ens`.

**Comment by jiaruidong2017** [comment]
Can I open another PR to add this into the `test_gdasapp_land_imsproc` ctest?

**Comment by CoryMartin-NOAA** [comment]
@jiaruidong2017 sure
