### ISSUE TITLE
[Bug] Changes to BUMP's yaml keys 

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#239]
Just a head's up @RussTreadon-NOAA and @CoryMartin-NOAA ...
See [SABER PR #389](https://github.com/JCSDA-internal/saber/pull/389)

_Merge will happen Jan 5 2023_

**Comment by RussTreadon-NOAA** [comment]
Thanks, @guillaumevernieres , for the heads up.   We also need to digest updates to the IODA naming conventions in the near future.
