### ISSUE TITLE
Transition to `pygw` tools

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#243]
good for now, but we will want to transition to `pygw` tools ASAP

_Originally posted by @CoryMartin-NOAA in https://github.com/NOAA-EMC/GDASApp/pull/234#discussion_r1047433676_

**Comment by RussTreadon-NOAA** [comment]
Fully transitioning to `pygw` is critical.    atm 3dvar ctests in GDASApp in `feature/ctest_atm_3dvar` fail after locally merging the current head of `devlop`, [74b9c1d](https://github.com/NOAA-EMC/GDASApp/commit/74b9c1d9d0263b88ce84a0382b5da9cd856258e5) into `feature/ctest_atm_3dvar`.   The prep, run, and post atm 3dvar tests work prior to the merge.

**Comment by guillaumevernieres** [comment]
> Fully transitioning to `pygw` is critical. atm 3dvar ctests in GDASApp in `feature/ctest_atm_3dvar` fail after locally merging the current head of `devlop`, [74b9c1d](https://github.com/NOAA-EMC/GDASApp/commit/74b9c1d9d0263b88ce84a0382b5da9cd856258e5) into `feature/ctest_atm_3dvar`. The prep, run, and post atm 3dvar tests work prior to the merge.

It works for me @RussTreadon-NOAA , but noted. As long as we don't erase `ufsda` we're fine. I'll make the switch but not for the current pr.
