### ISSUE TITLE
[Bug] land-apply_jedi_incr does not build with gnu

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#245]
@jiaruidong2017 , the repository in the title does not build with `gnu`. I submitted a small PR with a simple fix here [https://github.com/NOAA-PSL/land-apply_jedi_incr/pulls](https://github.com/NOAA-PSL/land-apply_jedi_incr/pulls). Are you allowed to review/merge?

**Comment by CoryMartin-NOAA** [comment]
This might be for @barlage or @ClaraDraper-NOAA (the latter of which I think is on leave)

**Comment by jiaruidong2017** [comment]
Yes, this repo is managed by @ClaraDraper-NOAA.

**Comment by guillaumevernieres** [comment]
> Yes, this repo is managed by @ClaraDraper-NOAA.

OK, no worries, that can wait until @ClaraDraper-NOAA comes back.
