### ISSUE TITLE
Split the soca run jjob 

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#263]
## Description
Isolate `soca_var.x` in one jjob only, move the other executables to a separate, dedicated jjob. Not ideal yet, but arguably closer to perfection!

## Stuff to do
Create a new `script` in this repo and a new `jjob` in the g-w that will contain the JEDI executables in [exgdas_global_marine_analysis_run.sh](https://github.com/NOAA-EMC/GDASApp/blob/develop/scripts/exgdas_global_marine_analysis_run.sh) between [L88](https://github.com/NOAA-EMC/GDASApp/blob/develop/scripts/exgdas_global_marine_analysis_run.sh#L88) and [L133](https://github.com/NOAA-EMC/GDASApp/blob/develop/scripts/exgdas_global_marine_analysis_run.sh#L88)

Suggested name for the script: `exgdas_global_marine_analysis_bmat.sh` ? 

_To be discussed with_ @AndrewEichmann-NOAA

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres So are we shooting for all of the APRUN calls to have their own scripts?

**Comment by AndrewEichmann-NOAA** [comment]
The goal for now will be to split the soca_var.x executable call from the previous ones, so that it has its own script and j-job that runs in the current workflow-enabled ctests within GDASApp, with the eventual goal of having separate tasks within the rocoto workflow.

**Comment by AndrewEichmann-NOAA** [comment]
Partially addressed by https://github.com/NOAA-EMC/GDASApp/pull/272

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres Do we want a separate g-w config file for JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT, either now or in the future? Right now it does fine with `configs="base ocnanal ocnanalrun"`, and I don't know how strictly the g-w people would want a separate one. With EFSOI there was some resistance to a proliferation of config files.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres Do we want a separate g-w config file for JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT, either now or in the future? Right now it does fine with `configs="base ocnanal ocnanalrun"`, and I don't know how strictly the g-w people would want a separate one. With EFSOI there was some resistance to a proliferation of config files.

It's probably OK for now @AndrewEichmann-NOAA . Your j-job will use the same resources as the "run" j-job, but the completion time should be a lot less than running the DA, that's the one difference that I can think of ... I'm sure I'm missing something, but that can be pushed down to your next PR that will add the dependencies of that j-job.

**Comment by guillaumevernieres** [comment]
Thanks @AndrewEichmann-NOAA ... better you than me :)
Done so closing.
