### ISSUE TITLE
Add basic QC to AOD observation YAMLs

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/GDASApp#291]
The YAMLs in GDASApp currently do not have any QC for the AOD obs, need to add some basic QC (high quality only?) and perhaps thinning (versus in the preprocessing step)

**Comment by andytangborn** [comment]
These both would be good.   Are there any good examples for other obs types that we could work from?

**Comment by CoryMartin-NOAA** [comment]
@andytangborn I thought you already had the QC mark for high only included in your YAMLs? It just isn't checked into the repository yet.

**Comment by andytangborn** [comment]
Oh right. Yes I have that. I was thinking that this would be something new.
