### ISSUE TITLE
Add the dependencies of the BMAT j-job in the g-w

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#308]
`BMAT` needs to run after `PREP` and before `RUN`

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres It's not doing that already?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres It's not doing that already?

That's your pr 1286 in g-w @AndrewEichmann-NOAA . Just trying to capture most of our work in issues.

**Comment by AndrewEichmann-NOAA** [comment]
Ah, ok
