### ISSUE TITLE
Concatenation of ioda files only works for sst

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#326]
The ioda concatenation only works for sst's ... Oops. 
Make it work for all obs.

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres Where is this not happening?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres Where is this not happening?

No hurries on that one. Let's get a simple `eva` application in first.
But happy to chat about it when you have time.

**Comment by ShastriPaturi** [comment]
Include me as well.

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres Is this something to revisit?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres Is this something to revisit?

I'm 95.7% sure I sorted out the issue a while back, but to be checked. I don't know why I would not have closed this issue though ... humm ...
