### ISSUE TITLE
Fix the input obs file for broken land_letkfoi_snowda ctest

### ISSUE THREAD

**Issue by jiaruidong2017** [NOAA-EMC/GDASApp#337]
PR #328 provides examples to update yamls and obs data files to the new IODA format. This issue is opened to update the input obs files used by ctest: `test_gdasapp_land_letkfoi_snowda`.

**Comment by jiaruidong2017** [comment]
@CoryMartin-NOAA @ADCollard Where can I find the tool `ioda-upgrade-v2-to-v3.x`? Is it available in the GDASApp? Thanks.

**Comment by CoryMartin-NOAA** [comment]
@jiaruidong2017 I think I already was able to update the one file that is needed on Orion and will copy to Hera tomorrow. Can you confirm which files are already in IODA format that your existing tests use? Is it just `adpsfc_snow_2021032318.nc4`?

**Comment by jiaruidong2017** [comment]
@CoryMartin-NOAA Yes, it is `adpsfc_snow_2021032318.nc4`. Hera is back now. Thanks.

**Comment by CoryMartin-NOAA** [comment]
@jiaruidong2017 transferring it now, test it out and if it works, then it should be good to go already

**Comment by CoryMartin-NOAA** [comment]
@jiaruidong2017 you'll need to test it with a fresh build of develop. we merged in everything earlier today

**Comment by jiaruidong2017** [comment]
@CoryMartin-NOAA Thanks for remainder. I will rebuild GDASApp in develop branch, and run my ctest.

**Comment by jiaruidong2017** [comment]
$ ctest -R test_gdasapp_land_letkfoi_snowda
```
Test project /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.6/build
    Start 1339: test_gdasapp_land_letkfoi_snowda
1/1 Test #1339: test_gdasapp_land_letkfoi_snowda ...   Passed    6.75 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   7.04 sec
```
A PR will be created for this bug fix to the yaml file.
