### ISSUE TITLE
High-res WCDA setup 

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#342]
Model resolution: C384/0.25deg
Setup for the JCSDA golden period: July 1 2021

- [x] #353
- [x] #374
- [x] #354
- [x] #375
- [x] Convert obs to ioda-v3 for the golden period (see issue #???)
- [x] ~setup a GDASApp stand alone test case (`run_jjob.py`)~
- [x] setup a global-workflow experiment at high res
- [x] ioda concatenation see #347 
- [x] Document the necessary steps to setup an experiment

Example for a low-res setup:
```/scratch2/NCEPDEV/ocean/Guillaume.Vernieres/runs/wcda-tutorial/global-workflow/sorc/gdas.cd/build/test```

**Comment by AndrewEichmann-NOAA** [comment]
Hi-res coupled setup: https://github.com/NOAA-EMC/global-workflow/pull/1274
