### ISSUE TITLE
Miss-guiding comment in vrfy j-job

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/GDASApp#348]
Per discussion with @guillaumevernieres, `ocnanalpost` is the dependency of both `ocnanalvrfy` and the following cycle, due to the anticipated run length of `ocnanalvrfy`. `JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY` for its part has this comment

`# Do not remove the Temporary working directory (do this in POST)`

and `JGDAS_GLOBAL_OCEAN_ANALYSIS_POST` does indeed have the default to remove `DATA`. The apparent assumption in   `exgdas_global_marine_analysis_vrfy.py` is to run in `COMOUT`, but with a todo to run in `DATA`, which I suspect is what is expected in global-workflow. As such there appears to be the at least the future danger of `ocnanalpost` deleting `DATA` before `ocnanalvrfy` is finished in it.

**Comment by guillaumevernieres** [comment]
@AndrewEichmann-NOAA , my point from yesterday was that we should only use what's been saved in the comout/comrot and assume that the rundir for the DA is gone.

So no, it's not a  danger, it's a guaranty that the rundir will be gone when `vrfy` runs. Your `eva` yaml should be based on what's in the coumout/diag.

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres I didn't see it as an immediate concern, but thought it might become an issue later

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres I didn't see it as an immediate concern, but thought it might become an issue later

I won't close this issue since clearly my comment in the j-job is wrong ...

**Comment by guillaumevernieres** [comment]
I adjusted the title of your issue @AndrewEichmann-NOAA .
