### ISSUE TITLE
SSMIS Zeeman channels not calculated correctly

### ISSUE THREAD

**Issue by ADCollard** [NOAA-EMC/GDASApp#356]
Channels 19-22 are not agreeing between the JEDI calculation and that from the GSI obs files/geovals.

The differences are indicative of the Zeeman correction not being applied in the JEDI calculation.  This appears to be an issue with this particular crtm implementation (crtm_2.3.0_emc) as the ctests for SSMIS (which use crtm_2.4.0) all pass with hofx identical.

<img width="701" alt="Screenshot 2023-02-14 at 10 24 58 AM" src="https://user-images.githubusercontent.com/40322596/218782646-a7ff7ad5-2711-41dd-a90e-86a96c3432e1.png">

**Comment by ADCollard** [comment]
cksums differ between the crtm coeffs used in JEDI and GSI:

```
2120858364 243580 /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack-gfsv16/intel-18.0.5.274/crtm/2.3.0/fix/zssmis_f17.TauCoeff.bin
921699313 243580 /scratch1/NCEPDEV/stmp2/Andrew.Collard/ufoeval/2021080100/ssmis_f17/crtm/zssmis_f17.TauCoeff.bin
```

**Comment by ADCollard** [comment]
If we omit the `zssmis_f17.TauCoeff.bin` file from the `crtm/` directory we get just about perfect agreement.

<img width="706" alt="Screenshot 2023-02-14 at 5 27 24 PM" src="https://user-images.githubusercontent.com/40322596/218877567-c2ed850b-f0a8-4ef2-a79d-acd3e5106a0b.png">

This is a little confusing as [this article](https://nwp-saf.eumetsat.int/publications/vs_reports/nwpsaf-mo-vs-035.pdf) seems to say that the Zeeman correction increases the brightness temperature for channels 19 and 20 (Figure 3), but removing these files decreases the BT.  But it is confirmed that the GSI does not use these coefficients.

**Comment by ADCollard** [comment]
Obs-BG plots indicate that the JEDI calculations (with Zeeman) are better, but these channels are passive in the GSI anyway.

<img width="699" alt="Screenshot 2023-02-14 at 5 35 21 PM" src="https://user-images.githubusercontent.com/40322596/218878761-6fc1fabe-ca60-4b09-be9f-e1241fa13a0b.png">
<img width="695" alt="Screenshot 2023-02-14 at 5 36 34 PM" src="https://user-images.githubusercontent.com/40322596/218878966-78af8292-a1af-41a8-a6e7-69320ed1bc34.png">

**Comment by ADCollard** [comment]
@CoryMartin-NOAA Can you move or rename the `zssmis*` files in the CRTM fix directories (Orion and Hera), please?

**Comment by CoryMartin-NOAA** [comment]
@ADCollard will do
