### ISSUE TITLE
ioda change in diag file layout might break eva yaml generator

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/GDASApp#362]
Apparently a recent change in ioda removes the processor indicator from diag file filenames, eg from `adt_j3.2018041512_0000.nc4` to `adt_j3.2018041512.nc4`, which potentially breaks the yamls generated by`ush/eva/gen_eva_obs_yaml.py` handle filenames. At the very least it does on the marine side, as I discovered in final testing of additions for using eva to generate plots for soca. Would changing this in `ush/eva/gen_eva_obs_yaml.py` work for everybody else?

**Comment by AndrewEichmann-NOAA** [comment]
..., he asked at 5:10PM on Friday

**Comment by guillaumevernieres** [comment]
> ..., he asked at 5:10PM on Friday

Oops, sorry @AndrewEichmann-NOAA , I didn't mean this was supposed to be done today! But thank you :)

**Comment by CoryMartin-NOAA** [comment]
I think @ADCollard was working on this already...

**Comment by AndrewEichmann-NOAA** [comment]
> > ..., he asked at 5:10PM on Friday
> 
> Oops, sorry @AndrewEichmann-NOAA , I didn't mean this was supposed to be done today! But thank you :)

Eh, I just looked up and realized I wasn't going to get an answer for a while

**Comment by ADCollard** [comment]
It's already in a branch.  I might as well go ahead and PR it.

**Comment by ADCollard** [comment]
@CoryMartin-NOAA @guillaumevernieres @AndrewEichmann-NOAA This change was committed to develop with [PR360](https://github.com/NOAA-EMC/GDASApp/pull/360/files).

**Comment by AndrewEichmann-NOAA** [comment]
An apparent problem now is that the output file, the name of which gets split up to obtain the cycle, has changed, and so is has to be processed a little differently to get a proper output filename for the yaml. I'm taking care of in my pr, but currently there are wider problems with the build

**Comment by AndrewEichmann-NOAA** [comment]
Ok, no wider problems, but extracting the YYYYMMDDHH cycle from the diag file is now a little different. This should probably be obtained from either the yaml or, failing that, netcdf metadata
