### ISSUE TITLE
Profiling the cycling jobs at C384O025

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#368]
I'm wondering if we should consider a lower res atmosphere. Running that beast of a model might not be amazingly quick!

| j-job | Timing | Nodes |
| -------- | -------- | -------- |
| gdasprep |  |  |
| gdasanal |  |  |
| gdasocnanalprep | 68 sec |  |
| gdasocnanalbmat |  |  |
| gdasocnanalrun |  |  |
| gdasocnanalpost |  |  |
| gdassfcanl |  |  |
| gdasanalcalc |  |  |
| gdasanaldiag |  |  |
| gdasfcst | 37 mn | 18 |
| gdaspost |  |  |

**Comment by guillaumevernieres** [comment]
Let's populate that table once we have numbers @AndrewEichmann-NOAA . I'm guessing ~2 hours per 6 hour cycle (including the queued time).

**Comment by AndrewEichmann-NOAA** [comment]
Does swapping resolutions willy-nilly create problems? I'm thinking of the work that goes into making sure a new resolution works scientifically, and if that's a problem coupling different resolutions
