### ISSUE TITLE
Add start of infrastructure for BUFR to IODA observation processing to GDASApp

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/GDASApp#376]
Through a lot of effort by Ron and others, there is a bufr2ioda executable in ioda-converters that can convert BUFR files to netCDF4/HDF5 IODA files based on input YAML configurations.

While this will be an iterative process to get every field needed (and with the correct format, names, units, etc.), this issue is to track the initial inclusion of this infrastructure into GDASApp.

- [ ] Templated YAML for PrepBUFR
- [x] Templated YAML for ATMS
- [ ] Templated YAML for AMSU-A
- [x] Script to generate YAMLs
- [x] Script to run executable

**Comment by guillaumevernieres** [comment]
FYI @CoryMartin-NOAA : https://github.com/NOAA-EMC/GDASApp/blob/fede25cb41932e339671258d0a0af7913320abf2/test/soca/CMakeLists.txt#L14

We could just move the bufr2ioda tests out of "soca", the testing "infrastructure" is already there and was added by @AndrewEichmann-NOAA and @ShastriPaturi a while back.

**Comment by CoryMartin-NOAA** [comment]
@guillaumevernieres yeah I have testing too for one ob type to make sure it works, this issue is to include YAMLs and have infrastructure to process a full cycle's worth of obs from BUFR to IODA in one go, do you have anything to do the latter yet?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres yeah I have testing too for one ob type to make sure it works, this issue is to include YAMLs and have infrastructure to process a full cycle's worth of obs from BUFR to IODA in one go, do you have anything to do the latter yet?

I'm not quite sure what the above means @CoryMartin-NOAA ... So probably not! What's in the soca ctest only runs the bufr to ioda converter for a few of the marine obs, so just the same thing that you currently are doing.
