### ISSUE TITLE
Qualitative analysis of NSST

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#378]
### Identify NSST related variables
- NSST foundation is in `tref`
- skin temp (?) is in: `tmpsfc`
- ocean temp is in `Temp`
- dtanl is the nsst increment?
- ...

### Qualitative analysis
- compare `tref` with mom6's ocean surface temp for (03-06-09) over a few cycle
- ...

**Comment by guillaumevernieres** [comment]
FYI @AndrewEichmann-NOAA : 
After a bit of investigation, `cplflx = .true.` in input.nml means that tref is coming from mom6. No clue yet exactly what is used from mom6, but I suspect just the top layer, which does include a diurnal cycle.

Below is the `tref` difference with and without marine DA.
![tref-diff](https://user-images.githubusercontent.com/14031856/225456759-4ff46ecb-ac5d-4b30-bc92-bbd436e5eac4.png)

`tref` is defined here in [sfc_nst_pre.f#L80](https://github.com/ufs-community/ccpp-physics/blob/630d37494a9e32690131b0af0ea367886581ecba/physics/sfc_nst_pre.f#L80)

The plot above also indicate that `tref` is clearly coming from mom6.

I think the next step is to look at the nsst analysis ... I'm pretty sure this isn't fed back to the model.

**Comment by AndrewEichmann-NOAA** [comment]
So we expect the inputs to that equation to come from the ice model and mom6?

**Comment by guillaumevernieres** [comment]
> So we expect the inputs to that equation to come from the ice model and mom6?

@AndrewEichmann-NOAA , I don't know where `tgice` is coming from.
