### ISSUE TITLE
Remove empty obs spaces

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#393]
### Description
What we have in `obs_list.yaml` is what we wish to assimilate/simulate but the staged obs will rarely have the entire wish list available. The result is the jedi exe failing.
 
### Solution
There are multiple ways to do this. I'm thinking about culling the obs space based on what was actually staged. Any other suggestions @RussTreadon-NOAA , @CoryMartin-NOAA , @AndrewEichmann-NOAA , ... and others ...

A simple python application:
```
input: 
 - var/hofx/letkf.yaml
 - path to where the obs were staged
output:
- new var.yaml with obs spaces pointing to non-existent files removed
```

**Comment by CoryMartin-NOAA** [comment]
@guillaumevernieres I think my preference would be to create an `obs_list` yaml on the fly from the input obs_list and available observation types. How easy would that be to implement?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres I think my preference would be to create an `obs_list` yaml on the fly from the input obs_list and available observation types. How easy would that be to implement?

I'll look into it @CoryMartin-NOAA . I forgot in what order the `var.yaml` and obs staging is done.

**Comment by RussTreadon-NOAA** [comment]
Why can't JEDI apps simply note that a specific input observation file is missing and continue app execution?   The GSI does this.

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA great question and one that I have been asking for a while (years) now. I hope that we can make this a requirement before JEDI is in operations. Perhaps it will fall on us/EMC to make the necessary changes in IODA to ignore an obsspace with a missing file.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres I think my preference would be to create an `obs_list` yaml on the fly from the input obs_list and available observation types. How easy would that be to implement?

@CoryMartin-NOAA , @RussTreadon-NOAA : That's a chicken&egg problem. In the marine da case, the obs yaml is used to fetch the obs from r2d2, I won't know if they actually exist after they have been fetched. I can output the "effective" obs list if we think that's useful, but the original obs list would have been used already.

I'm planning to clean the obs space in ```stage_cfg``` after (or at the end of?) the call to ```ufsda.stage.obs(stage_cfg)```.

**Comment by CoryMartin-NOAA** [comment]
See this: https://github.com/JCSDA-internal/ioda/issues/541
