### ISSUE TITLE
run_jedi_exe.py fails because genYAML inconsistent with g-w yaml_file.py 

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/GDASApp#408]
GDASApp PRs #407 (land) and #405 (atmosphere) along with g-w PRs [#1370](https://github.com/NOAA-EMC/global-workflow/pull/1370) (aerosol), and [#1372](https://github.com/NOAA-EMC/global-workflow/pull/1372) (atmosphere) update yamls to a new syntax consistent with g-w [`ush/python/pygw/src/pygw/yaml_file.py`](https://github.com/NOAA-EMC/global-workflow/blob/develop/ush/python/pygw/src/pygw/yaml_file.py).

GDASApp [ush/ufsda/genYAML.py](https://github.com/NOAA-EMC/GDASApp/blob/develop/ush/ufsda/genYAML.py) does not properly handle the new syntax used by `yaml_file.py`.   This is problematic.   Keywords in the updated source yamls are not properly handled by `genYAML`  As a result, yamls created by [ush/run_jedi_exe.py](https://github.com/NOAA-EMC/GDASApp/blob/develop/ush/run_jedi_exe.py) no longer work in UFS-DA applications (e.g., `fv3jedi_var.x`, `fv3jedi_letkf.x`).  

For example, `./run_jedi_exe.py -c examples/run_jedi_exe/3dvar_orion.yaml` creates `gdas_variational.yaml` beginning with
```
cost function:
  cost type: 3D-Var
  window begin: '{{ ATM_WINDOW_BEGIN | to_isotime }}'
  window length: PT6H
```

`fv3jedi_var.x` fails with
```
OOPS_STATS Variational start                        - Runtime:     3.62 sec,  Local Memory:   194.27 Mb
Exception: BadValue: Badly formatted date: {{ A
Exception: BadValue: Badly formatted date: {{ A
Exception: BadValue: Badly formatted date: {{ A
Exception: BadValue: Badly formatted date: {{ A
Exception: BadValue: Badly formatted date: {{ A
Exception: BadValue: Badly formatted date: {{ A
BadValue: Badly formatted date: {{ A caught in  (/work/noaa/da/rtreadon/git/global_workflow/test2/sorc/gdas.cd/oops/src/oops/runs/Run.cc +193 execute)
Exception: oops::Variational<FV3JEDI, UFO and IODA observations> terminating...
```

This issue is opened to document this problem and document a suitable path forward.

**Comment by RussTreadon-NOAA** [comment]
Tagging @CoryMartin-NOAA , @guillaumevernieres , @andytangborn , @jiaruidong2017 , and @aerorahul for awareness and discussion.

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA hmm, so I guess we don't test this script at all in the CI testing? I thought we had all tests pass when Rahul made these changes. Or could you be using an old version of the `pygw` tools that do not yet support his feature?

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA.  The run_jedi_exe ctests intentionally cancel the submitted job because we have j-job ctests which execute the UFS-DA app.   We decided limit to execution of the UFS-DA app to a single ctest.   So while the run_jedi ctests _PASS_ the actual yaml file generated by run_jedi_exe.py will not work in the UFS-DA app.   We could (should) add a yaml validator to the run_jedi_exe ctests.

**Comment by CoryMartin-NOAA** [comment]
ah! got it
