### ISSUE TITLE
Correct obs error estimation based on surface type in viirs_aod2ioda.py

### ISSUE THREAD

**Issue by ypwang19** [NOAA-EMC/GDASApp#409]
The VIIRS AOD obs error/uncertainty is computed based on a surface type variable of QCPath. However, QCPath value is wrongly interpreted. 

We need to convert the QCPath value to binary format first and then use it to identify dark/bright land or ocean surface.

**Comment by CoryMartin-NOAA** [comment]
Sorry that it wasn't clear @ypwang19, I think this issue belongs in https://github.com/jCSDA-internal/ioda-converters since that is where the change needs to happen.

**Comment by ypwang19** [comment]
Oh, sorry, should I close this one and open a new one under ioda-converters?

> Sorry that it wasn't clear @ypwang19, I think this issue belongs in https://github.com/jCSDA-internal/ioda-converters since that is where the change needs to happen.

**Comment by CoryMartin-NOAA** [comment]
yes please!
