### ISSUE TITLE
Archiving: conflict in ush/hpssarch_gen.sh

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#417]
A diff with develop of ```ush/hpssarch_gen.sh``` returns a commented out section, see here:

https://github.com/guillaumevernieres/global-workflow/blob/f1f125a84cb1f5ed2fcc7b7466402415b3e0398f/ush/hpssarch_gen.sh#L344

This needs to be wrapped around some logic ...

**Comment by AndrewEichmann-NOAA** [comment]
Addressed in https://github.com/NOAA-EMC/global-workflow/pull/1498

**Comment by guillaumevernieres** [comment]
OMG!!! No story points!
