### ISSUE TITLE
Create initial C96 (C48 analysis res) 3DVar regression test

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/GDASApp#45]
Will run 3DVar as part of ctest, compare output increment to staged increment on disk with `nccmp` and return successful if `fv3jedi_var.x` and `nccmp` have exit codes of 0.

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA is this something you would like to tackle or would you prefer I do it (probably next week)?

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA , I can work on this after prototype GDAS-JEDI cycling is in g-w.   fv3-jedi has 3dvar ctests.   Does it make sense to model our ctest based on these existing tests with our extensions added?

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA thanks! Yes, what I used for inspiration was the hyb-3dvar test: https://github.com/JCSDA-internal/fv3-jedi/blob/develop/test/testinput/hyb-3dvar.yaml and just changed the **B**. I think this is a good idea to model ours based on what is in the authoritative repo, since then it will be easier to change our YAMLs if the syntax changes.

**Comment by RussTreadon-NOAA** [comment]
Add self (@RussTreadon-NOAA ) to list of issue assignees

**Comment by CoryMartin-NOAA** [comment]
Here is at least one goal for the sprint for next week @guillaumevernieres @RussTreadon-NOAA

**Comment by guillaumevernieres** [comment]
Or we simply add a test section in our `yamls`?

**Comment by CoryMartin-NOAA** [comment]
@guillaumevernieres sorry if I confused, I mainly meant we want a 3DVar C48 test for atm in our ctest ASAP (I think what you're saying is that OOPS can handle some basic testing capability within the exe?)

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres sorry if I confused, I mainly meant we want a 3DVar C48 test for atm in our ctest ASAP (I think what you're saying is that OOPS can handle some basic testing capability within the exe?)

@CoryMartin-NOAA , sorry for the confusion. Yes, I was just thinking as an alternative to nccmp we could just use what's provided in oops and only store a small ascii file instead of the full increment or state or ...
