### ISSUE TITLE
Option to build GDASApp without fv3-bundle

### ISSUE THREAD

**Issue by FanHan-NOAA** [NOAA-EMC/GDASApp#46]
I see that fv3-bundle is built with GDASApp by default and wonder if OK to add an option to build it without fv3-bundle. Instead, just provide a path for the already built fv3-bundle somewhere else so the script can create all the symlinks from the provided path.

**Comment by CoryMartin-NOAA** [comment]
@FanHan-NOAA you can pass to the build script/cmake the following argument:
`-DBUILD_GDASBUNDLE=OFF`

This will not build the bundle. 

Are you thinking of having it include an external build for regression/unit tests? Or just for running larger experiments (such as the script added in #44 ?)

**Comment by FanHan-NOAA** [comment]
Thanks, I did not know it has this option which is exactly what I need. I just don't like having multiple fv3-bundle so it would be nice to just use the one I already built and updated regularly. 

I'll close this issue as resolved.
