### ISSUE TITLE
test for ocean output to z* cordiante

### ISSUE THREAD

**Issue by hyunchul386** [NOAA-EMC/GDASApp#464]
- make diag_table for MOM6 3D output to z* coordinate.
- test and check the MOM6 3D output in z* coordinate

**Comment by hyunchul386** [comment]
The updated diag_table for z* coordinate:
      1 @[SYEAR]@[SMONTH]@[SDAY].@[SHOUR]Z.@[ATMRES].64bit.non-mono
      2 @[SYEAR] @[SMONTH] @[SDAY] @[SHOUR] 0 0
      3
      4 "fv3_history",    0,  "hours",  1,  "hours",  "time"
      5 "fv3_history2d",  0,  "hours",  1,  "hours",  "time"
      6 ######################
      7 "ocn_da%4yr%2mo%2dy%2hr",      1,  "hours", 1, "hours", "time", 1, "hours", "1901 1 1 0 0 0"
      8 ##############################################
      9 # static fields
     10  "ocean_model", "geolon",      "geolon",      "ocn_da%4yr%2mo%2dy%2hr", "all", .false., "none", 2
     11  "ocean_model", "geolat",      "geolat",      "ocn_da%4yr%2mo%2dy%2hr", "all", .false., "none", 2
     12
     13 # ocean output SSH and MLD
     14  "ocean_model", "SSH",       "SSH",      "ocn_da%4yr%2mo%2dy%2hr","all",.false.,"none",2
     15  "ocean_model", "MLD_0125",  "MLD_0125", "ocn_da%4yr%2mo%2dy%2hr","all",.false.,"none",2
     16
     17 # Z*-Space:
     18 #===============================================
     19  "ocean_model_z","uo","uo"      ,"ocn_da%4yr%2mo%2dy%2hr","all",.false.,"none",2
     20  "ocean_model_z","vo","vo"      ,"ocn_da%4yr%2mo%2dy%2hr","all",.false.,"none",2
     21  "ocean_model_z","so","so"      ,"ocn_da%4yr%2mo%2dy%2hr","all",.false.,"none",2
     22  "ocean_model_z","temp","temp"  ,"ocn_da%4yr%2mo%2dy%2hr","all",.false.,"none",2

**Comment by hyunchul386** [comment]
Temperature section from the updated diag_table 

![Screenshot (100)](https://github.com/NOAA-EMC/GDASApp/assets/14810515/e63f5b7a-72c9-4385-aa5a-74d3c1986ee6)

**Comment by ShastriPaturi** [comment]
@hyunchul386 please do a spell check before you post: The title of the issue has incorrect spelling, so does ufs-weather-model.

**Comment by hyunchul386** [comment]
@ShastriPaturi Thanks for letting me know the misspelling, and let me know any issues on the diag_table/plot.

**Comment by guillaumevernieres** [comment]
> @ShastriPaturi Thanks for letting me know the misspelling, and let me know any issues on the diag_table/plot.

A few questions @hyunchul386 :
1 - Do you need somebody to show you how to edit the title?
2 - What are uo/vo/so?
