### ISSUE TITLE
Create script to clone/checkout/build workflow and GDASApp for particular hashes

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/GDASApp#467]
A script should be able to point to a YAML file, text file, etc. containing key information such as:

- GDASApp commit hash
- global workflow commit hash
- 'nickname' of experiment
- relevant paths (expdir, comrot, archive, etc.)

**Comment by CoryMartin-NOAA** [comment]
This work will begin and be in [feature/gen_proto](https://github.com/NOAA-EMC/GDASApp/tree/feature/gen_proto)

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA , I cloned [`feature/gen_proto`](https://github.com/NOAA-EMC/GDASApp/tree/feature/gen_proto) and updated the following files to get more GDASApp ctests to _Pass_
```
        modified:   parm/atm/berror/hybvar_bump.yaml
        modified:   parm/atm/berror/hybvar_gsibec.yaml
        modified:   parm/atm/lgetkf/lgetkf.yaml
        modified:   test/atm/global-workflow/config.base.emc.dyn
        modified:   test/atm/global-workflow/jjob_ens_final.sh
        modified:   test/atm/global-workflow/jjob_ens_init.sh
        modified:   test/atm/global-workflow/jjob_ens_run.sh
        modified:   ush/run_jedi_exe.py
        modified:   ush/ufsda/stage.py
```
 Most of the changes are replacing `NMEM_ENKF` with `NMEM_ENS`.

7 ctests fail after making the above local modifications
```
        1449 - test_gdasapp_soca_prep (Not Run)
        1452 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP (Failed)
        1453 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT (Failed)
        1454 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT_VRFY (Failed)
        1455 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN (Failed)
        1456 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT (Failed)
        1457 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_POST (Failed)
```
The _Not Run_ result is odd.  I never saw this before.  I'm looking into it.

**Comment by guillaumevernieres** [comment]
@RussTreadon-NOAA , I need to update the python script that runs the marine jjobs.

**Comment by RussTreadon-NOAA** [comment]
A fresh build of my GDASApp clone fixed whatever was wrong with my initial `test_gdasapp_soca_prep`.   This test now runs and passes.   

I looked into the `soca_JGDAS` tests failures.   As @guillaumevernieres notes `run_jjobs.py` needs a few updates
- add `gfs` to `setupexpt` command
- add `/gfs` to `config` paths

When I run `test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP` a second time, the g-w `setup_expt.py` hangs.  It detects the presence of directories comrot and expdir.   The script prompts the user to enter `y` to overwrite the existing directory.  We don't see this prompt from the ctest but if we enter `y` two times the ctest submits the PREP job.   

The PREP job dies when `ush/ufsda/misc_utils.py` tries to get `COMOUT` from the environment.  `JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP` no longer defines `COMOUT` after the COM directory update.

**Comment by guillaumevernieres** [comment]
Thanks for testing @RussTreadon-NOAA , the `test_gdasapp_soca_run_clean` ctest needs to run before the prep j-job. I should probably revisit this at some point. 
I'll try to submit a fix today.
