### ISSUE TITLE
Copying of marine obs from com_obs fails if the file does not exist

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#468]
### Description
The copying of ioda obs files is based on the original obs list (just guessing here) which might not exist for the cycle. 

### Solution
Build the obs list from what is actually in the com_obs.

**Comment by guillaumevernieres** [comment]
I think this was fixed ...

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres yes, I think so
