### ISSUE TITLE
Add statistical analysis of atmospheric diag files to ocean analysis verify

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/GDASApp#479]
Extract statistics relevant to WCDA from atmospheric diag files (for variables t over the ocean as possible, and sst)

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres Care to add anything?

**Comment by guillaumevernieres** [comment]
~Nope, not that I can think of. Are you adding to the gsi python package @AndrewEichmann-NOAA ?~
never mind ...
