### ISSUE TITLE
Global Ocean Monitoring and Observing (GOMO)

### ISSUE THREAD

**Issue by hyunchul386** [NOAA-EMC/GDASApp#485]
Global Ocean Monitoring and Observing in results of GDASApp/Global-Workflow/ufs-weather-model  
- monitoring  ocean observing systems in JEDI/SOCA
- evaluating the impacts of ocean observing systems in Tropical oceans in JEDI/SOCA
- Carrying out the GOMO project

**Comment by ShastriPaturi** [comment]
@hyunchul386 please add a description

**Comment by hyunchul386** [comment]
Adding descriptions, @ShastriPaturi
