### ISSUE TITLE
(o-b) in tropical Atlantic/Indian regions and other basins

### ISSUE THREAD

**Issue by hyunchul386** [NOAA-EMC/GDASApp#487]
check (o-b) of SST in the Tropical Atlantic/Indian regions
 calculation |o-b| and |o-a| of SST in the Tropical Atlantic/Indian regions
 check (o-b) of SSH in the Tropical Atlantic/Indian regions
 calculation |o-b| and |o-a| of SSH in the Tropical Atlantic/Indian regions

**Comment by hyunchul386** [comment]
This issue was moved under the GOMO epic

**Comment by hyunchul386** [comment]
Checking (o-b) of SST on 2021-07-23 of gloden-c384 for all SST data in the Tropical Atlantic, MDR, Western Indian, and Eastern Indian regions
![plot_surface_FD_scat_sst_TropAtl](https://github.com/NOAA-EMC/GDASApp/assets/14810515/734894aa-e69c-47a7-a5ae-a4b2e71a2c30)
![plot_surface_FD_scat_sst_MDR](https://github.com/NOAA-EMC/GDASApp/assets/14810515/2b5b7ae8-00cc-40aa-9de3-ee1ecdceaf8a)
![plot_surface_FD_scat_sst_WIND](https://github.com/NOAA-EMC/GDASApp/assets/14810515/dd6c28cf-1e50-49bc-9124-5f2dbf840cb2)
![plot_surface_FD_scat_sst_EIND](https://github.com/NOAA-EMC/GDASApp/assets/14810515/2f86eac7-2715-423b-8a94-513d96682d47)

**Comment by hyunchul386** [comment]
![Screenshot (118)](https://github.com/NOAA-EMC/GDASApp/assets/14810515/96b4fc77-4928-4181-917f-693220e879c5)

**Comment by hyunchul386** [comment]
Regional |o-b| and |o-a| of SST in the Tropical Pacific, MDR, western Tropical Indian and eastern Tropical Indian Ocean, on 2021-07-23 from golden-c384 run.

![plot_surface_FD_sst_bar_atlind](https://github.com/NOAA-EMC/GDASApp/assets/14810515/f28bd365-4d7e-4e98-8ecf-b1d48cc19392)

**Comment by ShastriPaturi** [comment]
> ![Screenshot (118)](https://user-images.githubusercontent.com/14810515/244475664-96b4fc77-4928-4181-917f-693220e879c5.png)

@hyunchul386 Why are pmbg values present on land?

**Comment by ShastriPaturi** [comment]
> ![plot_surface_FD_sst_bar_atlind](https://user-images.githubusercontent.com/14810515/248895478-f28bd365-4d7e-4e98-8ecf-b1d48cc19392.jpg)

@hyunchul386 provide a description and summary
added "Regional |o-b| and |o-a| of SST in the Tropical Pacific, MDR, western Tropical Indian and eastern Tropical Indian Ocean, on 2021-07-23 from golden-c384 run."

**Comment by hyunchul386** [comment]
> > ![Screenshot (118)](https://user-images.githubusercontent.com/14810515/244475664-96b4fc77-4928-4181-917f-693220e879c5.png)
> 
> @hyunchul386 Why are pmbg values present on land?

@ShastriPaturi The data of SST (o-b) were from golden-c384, /scratch2/NCEPDEV/ocean/Guillaume.Vernieres/runs/low-res/golden-c384/COMROT/golden-c384/gdas.20210723/00/ocean/diags. The preQC flags are all zero's in the file, and I am not sure why there are (o-b)'s on land. I will ask to @guillaumevernieres about it, first.

**Comment by hyunchul386** [comment]
![plot_surface_FD_sst_bar_nino](https://github.com/NOAA-EMC/GDASApp/assets/14810515/aa55d3c7-77c8-432d-ad4d-8b411c616aed)

**Comment by hyunchul386** [comment]
regional |o-b| and |o-a| (red bar in left panel) of merged SST in the Tropical Atlantic and Indian on 2021-07-04 00Z from cp0

![plot_surface_FD_sst_bar_atlind](https://github.com/NOAA-EMC/GDASApp/assets/14810515/c0e96ac1-3425-4e25-bf1e-e0de86d68d3c)

**Comment by hyunchul386** [comment]
post QC'ed SST (o-b) of cp0 on 2021-07-04 00Z, which is merged from metop a/b/c/ viirs data for global, NH, SH and Tropics

![plot_sst_arcglob_2021070400_glob](https://github.com/NOAA-EMC/GDASApp/assets/14810515/25db296a-4bb1-4f45-80a4-82c4f9c9bb33)

![plot_sst_arcglob_2021070400_NH](https://github.com/NOAA-EMC/GDASApp/assets/14810515/2b2de1c5-b8fb-42d6-bba6-67846fcf5ee2)

![plot_sst_arcglob_2021070400_SH](https://github.com/NOAA-EMC/GDASApp/assets/14810515/79843101-fea4-4a90-97cb-8034f7e01490)

![plot_sst_arcglob_2021070400_Trop](https://github.com/NOAA-EMC/GDASApp/assets/14810515/2f9e5c6f-d199-4177-b434-a0c643229677)

**Comment by hyunchul386** [comment]
|o-b| and |o-a| of QC'ed SST of cp0 over the regions in the global, NH, SH and Tropics,

![plot_surface_FD_sst_bar_arcglob_2021070400_qc](https://github.com/NOAA-EMC/GDASApp/assets/14810515/02eb875d-2458-4c5d-adaf-ebc0f3ebf0de)
