### ISSUE TITLE
(o-b) of sea surface fields in NINO regions

### ISSUE THREAD

**Issue by hyunchul386** [NOAA-EMC/GDASApp#488]
- [x] check (o-b) of SST in the NINO regions
- [x] calculation |o-b| and |o-a| of SST in the NINO regions
- [x] check (o-b) of SSH in the NINO regions
- [x] calculation |o-b| and |o-a| of SSH in the NINO regions
- [ ] put the code in ctest in GDASApp in G-W

**Comment by hyunchul386** [comment]
Check SST (o-b) of WCDA on 2021-07-23, merged all SST obs data (metop a/b/c/, viirs_npp)
![Screenshot (118)](https://github.com/NOAA-EMC/GDASApp/assets/14810515/96b4fc77-4928-4181-917f-693220e879c5)

**Comment by hyunchul386** [comment]
SST (o-b) of WCDA on 2021-07-23 in NINO regions
![plot_surface_FD_scat_nino12](https://github.com/NOAA-EMC/GDASApp/assets/14810515/0a8dcb2c-768f-48e3-bcb9-a24af440f236)
![plot_surface_FD_scat_nino30](https://github.com/NOAA-EMC/GDASApp/assets/14810515/f0cfad4f-4eea-4224-bf39-ed0b0b5297dc)
![plot_surface_FD_scat_nino34](https://github.com/NOAA-EMC/GDASApp/assets/14810515/ea2c8666-ee35-4050-b54f-f0fca84a103b)
![plot_surface_FD_scat_nino40](https://github.com/NOAA-EMC/GDASApp/assets/14810515/e652b4f8-981b-48bb-9455-57555a3969bd)

**Comment by hyunchul386** [comment]
A preliminary plot from golden-c384 on 2021-07-23 00Z, |o-b| of SST in NINO regions,
![plot_surface_FD_bar](https://github.com/NOAA-EMC/GDASApp/assets/14810515/e1189159-1080-4479-aeef-3d5b4e26be5f)

**Comment by hyunchul386** [comment]
A preliminary plot from golden-c384 on 2021-07-23 00Z, |o-b| of SST in NINO regions,
![plot_surface_FD_bar](https://github.com/NOAA-EMC/GDASApp/assets/14810515/6128519f-e157-4e11-808c-03c7e865ac34)

**Comment by hyunchul386** [comment]
Adding |o-a| in the plot,
![plot_surface_FD_bar](https://github.com/NOAA-EMC/GDASApp/assets/14810515/6ba7651f-a19b-436d-ad6c-a759b46197a7)

**Comment by guillaumevernieres** [comment]
What am I suppose to learn from these figures @hyunchul386 ?

**Comment by hyunchul386** [comment]
Currently, preliminary...
but this suggests that the deviation from observations of |o-b| and |o-a| of SST in the NINO regions on 2021-07-23. 
In NINO12 region, |o-b| is large in average, and so |o-a|, but the number of Obs is little, so the total (just summation) is also little. In NINI4 region, the pattern is reverse to the NINI12.

**Comment by hyunchul386** [comment]
And also it can be checked the sanity of individual Obs Systems, in this case.

**Comment by hyunchul386** [comment]
Checking (o-b) of SSH in golden-c384 on 2021-07-23 00Z from all adt Obs in All, NINO12, NINO3, NINO34,NINI4 regions,

![plot_surface_FD_scat_ssh_all](https://github.com/NOAA-EMC/GDASApp/assets/14810515/182d43df-3607-4950-b2be-2912084a3520)

![plot_surface_FD_scat_ssh_n12](https://github.com/NOAA-EMC/GDASApp/assets/14810515/097ad1bc-f9cc-481e-87bf-3e8283249cc8)

![plot_surface_FD_scat_ssh_n30](https://github.com/NOAA-EMC/GDASApp/assets/14810515/c358fbaa-5d09-4a78-9086-5c70f900b679)

![plot_surface_FD_scat_ssh_n34](https://github.com/NOAA-EMC/GDASApp/assets/14810515/65ddfad2-b32e-4355-85eb-d386e1605986)

![plot_surface_FD_scat_ssh_n40](https://github.com/NOAA-EMC/GDASApp/assets/14810515/cadf7033-5e25-40cc-b3bb-41a4f9b4798c)

**Comment by hyunchul386** [comment]
|o-b| and |o-a| of SSH in NINO regions,
![plot_surface_FD_ssh_bar](https://github.com/NOAA-EMC/GDASApp/assets/14810515/ab68ef6c-fdf8-466c-bbaf-cce74ecfe99a)

**Comment by hyunchul386** [comment]
region |o-b| and |o-a| of merged SST from cp0 on 2021-07-04 00Z,
it seems that it looks okay,

![plot_surface_FD_sst_bar_atlind](https://github.com/NOAA-EMC/GDASApp/assets/14810515/f378d705-771e-4731-8bf6-1295f589e714)

![plot_surface_FD_sst_bar_nino](https://github.com/NOAA-EMC/GDASApp/assets/14810515/7fd88328-9932-459c-b0d6-bac2ae2d52d7)
