### ISSUE TITLE
Update MOM6's diag_table to save fields on z*

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#494]
Update MOM6's diagnostic table to output `Temperature` on `z*`.

**Comment by hyunchul386** [comment]
Following will be tested for the z* output of Temp
---------------------------------------------------------------------

"fv3_history",    0,  "hours",  1,  "hours",  "time"
"fv3_history2d",  0,  "hours",  1,  "hours",  "time"
"ocn_da%4yr%2mo%2dy%2hr", 1, "hours", 1, "hours", "time", 1,  "hours"
"ocn_da_z%4yr%2mo%2dy%2hr", 1, "hours", 1, "hours", "time", 1,  "hours"

"ocean_model",  "geolon",    "geolon",   "ocn_da%4yr%2mo%2dy%2hr",  "all",  "none",  "none",  2
"ocean_model",  "geolat",    "geolat",   "ocn_da%4yr%2mo%2dy%2hr",  "all",  "none",  "none",  2
"ocean_model",  "SSH",       "ave_ssh",  "ocn_da%4yr%2mo%2dy%2hr",  "all",  "none",  "none",  2
"ocean_model",  "MLD_0125",  "MLD",      "ocn_da%4yr%2mo%2dy%2hr",  "all",  "none",  "none",  2
"ocean_model",  "u",         "u",        "ocn_da%4yr%2mo%2dy%2hr",  "all",  "none",  "none",  2
"ocean_model",  "v",         "v",        "ocn_da%4yr%2mo%2dy%2hr",  "all",  "none",  "none",  2
"ocean_model",  "h",         "h",        "ocn_da%4yr%2mo%2dy%2hr",  "all",  "none",  "none",  2
"ocean_model",  "salt",      "Salt",     "ocn_da%4yr%2mo%2dy%2hr",  "all",  "none",  "none",  2
"ocean_model",  "temp",      "Temp",     "ocn_da%4yr%2mo%2dy%2hr",  "all",  "none",  "none",  2
"ocean_model_z",  "temp",      "Temp",     "ocn_da_z%4yr%2mo%2dy%2hr",  "all",  "none",  "none",  2

**Comment by hyunchul386** [comment]
A results of RT run for ocn_da_z in UWM:

netcdf ocn_da_z_2011_10_01_06 {
dimensions:
        xh = 360 ;
        yh = 320 ;
        z_l = 40 ;
        z_i = 41 ;
        time = UNLIMITED ; // (1 currently)
variables:
        double xh(xh) ;
                xh:units = "degrees_east" ;
                xh:long_name = "h point nominal longitude" ;
                xh:axis = "X" ;
        double yh(yh) ;
                yh:units = "degrees_north" ;
                yh:long_name = "h point nominal latitude" ;
                yh:axis = "Y" ;
        double z_l(z_l) ;
                z_l:units = "meters" ;
                z_l:long_name = "Depth at cell center" ;
                z_l:axis = "Z" ;
                z_l:positive = "down" ;
                z_l:edges = "z_i" ;
        double z_i(z_i) ;
                z_i:units = "meters" ;
                z_i:long_name = "Depth at interface" ;
                z_i:axis = "Z" ;
                z_i:positive = "down" ;
        double time(time) ;
                time:units = "hours since 2011-10-01 00:00:00" ;
                time:long_name = "time" ;
                time:axis = "T" ;
                time:calendar_type = "JULIAN" ;
                time:calendar = "julian" ;
        float Temp(time, z_l, yh, xh) ;
                Temp:_FillValue = -1.e+34f ;
                Temp:missing_value = -1.e+34f ;
                Temp:units = "degC" ;
                Temp:long_name = "Potential Temperature" ;
                Temp:cell_methods = "area:mean z_l:mean yh:mean xh:mean time: point" ;

**Comment by hyunchul386** [comment]
Temp section along EQ from the ocn_da_z
![Screenshot (116)](https://github.com/NOAA-EMC/GDASApp/assets/14810515/207dd812-5d36-41b1-a17b-1cc7015c347c)
