### ISSUE TITLE
Prototype real time observation tanking

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#497]
## Deliverable
 Marine observations, bufr and netcdf, copied in real time, in their original formats, from the GTS to `6 hour dumps`.
 
## Implementation
This task may or may not require the implementation of a new `j-job`/`ex_script` in the  [obsproc](https://github.com/NOAA-EMC/obsproc) repository. TBD by @ilianagenkova and @weiwli-NOAA .

### Bufr observation files
A prototype is being tested.

### Netcdf 
- Files containing less than 6 hours of obs: Simple copy, don't bother splitting the files if they overlap two 6 hour windows, just copy in both. These would be for example: 
   - SST retrievals: Copy the 10 mn files in `6 hour dumps`
   - SSS ?
   - ...
- Files containing more than 6 hour worth of observations: These will need to be split in 6 (or less) hour chunks. Examples:
  - AMSR2 ice concentration: ...
- Observations with large latency: 
  - Altimeters (RADS): Copy obs that may be as old as 48 hours in the real time 6 hour dump location. How far back we copy these obs will be adjusted as we better understand the latency of the RADS.
  - Sea-ice Freeboard: TBD
  - ...

**Comment by ShastriPaturi** [comment]
The NRT 6-hourly dumps for the netcdf(s) and bufr are running in cron and have been looked at.
The JJOB in the ObsProc repo will be added by the new Team member.
