### ISSUE TITLE
marine DA verify task is failing

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#498]
I have not check where yet ...

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres @CoryMartin-NOAA 
With the changes in PR https://github.com/NOAA-EMC/GDASApp/pull/507 in place, the vrfy ctest now fails when it doesn't find the file `build/test/soca/gw/testrun/testjjobs/ROTDIRS/gdas_test/gdas.20180415/12//analysis/atmos/gdas.t12z.cnvstat`. Is there some accounting for its absence, and do we want to leave it to break when it's not found (as opposed to just issuing a warning)?
EDIT: It dawns on me that this does not exist in the ctest - can we provide it? Or make it a warning?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres @CoryMartin-NOAA With the changes in PR #507 in place, the vrfy ctest now fails when it doesn't find the file `build/test/soca/gw/testrun/testjjobs/ROTDIRS/gdas_test/gdas.20180415/12//analysis/atmos/gdas.t12z.cnvstat`. Is there some accounting for its absence, and do we want to leave it to break when it's not found (as opposed to just issuing a warning)? EDIT: It dawns on me that this does not exist in the ctest - can we provide it? Or make it a warning?

I just checked, that file is `164M` ... How about just issuing a warning?

**Comment by CoryMartin-NOAA** [comment]
Or a test that creates a 'dummy' cnvstat file

**Comment by guillaumevernieres** [comment]
My grepping isn't returning anything. Where are we using that file @AndrewEichmann-NOAA ?

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres That's just it - it gets produced with the atmospheric analysis and so is not present when you run just soca. Lil' ol' genius me tested it with cycling instead of the ctests.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres That's just it - it gets produced with the atmospheric analysis and so is not present when you run just soca. Lil' ol' genius me tested it with cycling instead of the ctests.

Well, myself being a super genius, I knew that! I was just wondering where it was used in the ex script. I forgot you added that `diag_statistics.get_diag_stats()` a while back. 
Up to you @AndrewEichmann-NOAA , I'm fine with skipping and issuing a warning. @CoryMartin-NOAA 's proposition seems like a better way to go though. If you decide to skip, can you create an issue from @CoryMartin-NOAA 's suggestion?

**Comment by AndrewEichmann-NOAA** [comment]
@CoryMartin-NOAA @guillaumevernieres So by a dummy cnvstat file, are we talking about a file with the minimum to make the test work? That would mean a tarfile with gzipped t and sst diag files.

**Comment by guillaumevernieres** [comment]
> 

ha! I thought it was a tarred/zipped ascii file ... I guess that would explain the 160M. So I guess skip!

**Comment by CoryMartin-NOAA** [comment]
No I meant:
`touch gdas.t00z.cnvstat`

Assuming it's not actually used. If used, then skip away!

**Comment by guillaumevernieres** [comment]
> No I meant: `touch gdas.t00z.cnvstat`
> 
> Assuming it's not actually used. If used, then skip away!

Ha! it is actually used @CoryMartin-NOAA .
