### ISSUE TITLE
Missing seaice offline ensemble member

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#505]
Missing from hpss: `cice.res.nc` for `2019-07-15T00Z` from @liuxiao37k 's offline ensemble

**Comment by hyunchul386** [comment]
### In the source directory, /lustre/f2/dev/ncep/Xiao.Liu/sandbox/09aug2022/cpld_BGC_v2/ens2019010600_001/rst/2019071500/ctrl/
cice.res.nc is missing in the directory, and ice.restart_file is empty.
-------------
-rw-r--r-- 1 Xiao.Liu ncep   29538828 Jan  1 01:43 ca_data.tile6.nc
-rw-r--r-- 1 Xiao.Liu ncep        300 Jan  1 01:43 coupler.res
lrwxrwxrwx 1 Xiao.Liu ncep         96 Jan  1 21:23 ctrl -> /lustre/f2/dev/ncep/Xiao.Liu/sandbox/09aug2022/cpld_BGC_v2/ens2019010600_00/rst/2019071500/ctrl
-------------
-rw-r--r-- 1 Xiao.Liu ncep      19808 Jan  1 01:42 fv_core.res.nc


-rw-r--r-- 1 Xiao.Liu ncep          0 Jan  1 01:43 ice.restart_file

**Comment by liuxiao37k** [comment]
@hyunchul386 @guillaumevernieres @ShastriPaturi 
Not sure what happened there but I should be able to reproduce `cice.res.nc` without rerun the forecast step. Please see my email response. The actual ice restart file `iced.2019-07-15-00000.nc` still exists.

**Comment by liuxiao37k** [comment]
@hyunchul386 @guillaumevernieres 
The missing `cice.res.nc` has been regenerated by running the standalone program `soca_seaice.py` on `iced.2019-07-15-00000.nc`. 
gaea path:
/lustre/f2/dev/ncep/Xiao.Liu/sandbox/09aug2022/cpld_BGC_v2/ens2019010600_001/rst/2019071500/ctrl/cice.res.nc

In case you notice any more missing `cice.res.nc` files in the future, here is the step to regenerate it on gaea:
```
cd ${THE RST DIR WHERE THE FILE IS MISSING}
salloc --ntasks 16 --time=00:30:00 --account=nggps_emc --clusters=c4
module unload intel
module unload cray-mpich
module unload cray-python
module unload darshan
module use /lustre/f2/pdata/esrl/gsd/spack-stack/modulefiles
module load miniconda/3.9.12
module load ecflow/5.8.4
module load mysql/8.0.31
module use /lustre/f2/dev/wpo/role.epic/contrib/spack-stack/spack-stack-1.3.1/envs/unified-env/install/modulefiles/Core
module load stack-intel/2022.0.2
module load stack-cray-mpich/7.7.20
module load stack-python/3.9.12
module load ecbuild/3.7.2 
module load soca-env/unified-dev
module load fms/release-jcsda
/lustre/f2/dev/ncep/Xiao.Liu/sandbox/22may2023/build-intel/bin/soca_seaice.py -f iced.${YYYY-MM-DD}-00000.nc -m cice -a model2soca -o cice.res.nc
```
Hope this helps.

**Comment by guillaumevernieres** [comment]
Thanks @liuxiao37k .

**Comment by hyunchul386** [comment]
@liuxiao37k Thanks for regenerating and the information.

**Comment by hyunchul386** [comment]
The file of ens2019010600_001 in 219071500 has been updated at hpss,

htar -tvf /5year/NCEPDEV/marineda/Ensem_xiao/ens2019010600_001/rst.2019071500.tar
[connecting to hpsscore1.fairmont.rdhpcs.noaa.gov/1217]
HTAR: -rw-r--r--  Xiao.Liu/ncep 2273344603 2023-01-03 18:53  MOM.res.nc                                    
HTAR: -rw-r--r--  Xiao.Liu/ncep  473455247 2023-01-01 06:42  MOM.res_5.nc
HTAR: -rw-r--r--  Xiao.Liu/ncep   37368369 2023-06-15 13:56  **cice.res.nc**
HTAR: -rw-r--r--  Xiao.Liu/ncep 1978216948 2023-01-02 01:26  iced.2019-07-15-00000.nc
HTAR: -rw-r--r--  Xiao.Liu/ncep          0 2023-01-01 06:43  ice.restart_file
HTAR: -rw-------  Hyun-Chul.Lee/ncep        256 2023-06-20 12:27  /tmp/HTAR_CF_CHK_113295_1687264075
HTAR: Listing complete for /5year/NCEPDEV/marineda/Ensem_xiao/ens2019010600_001/rst.2019071500.tar, 6 files 6 total objects
HTAR: HTAR SUCCESSFUL
