### ISSUE TITLE
BMAT_VRFY task failing in ctests

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/GDASApp#512]
The BMAT_VRFY task was pulled out of the soca ctests - when run it fails with complaints of no file `dirac.yaml`. A `find` in `build/test/soca` produces the following:

```
(gdasapp) -bash-4.2$ find -name dirac*
./gw/testrun/testjjobs/ROTDIRS/gdas_test/gdas.20180415/12/analysis/ocean/yaml/dirac_output.yaml
```

**Comment by guillaumevernieres** [comment]
FYI @AndrewEichmann-NOAA , I'm working on this right now.

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres close?
