### ISSUE TITLE
refactoring of vrfy task 

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/GDASApp#531]
General effort to clean up vrfy task, particularly with respect to plotting. General concept is to get the nitty-gritty of plotting parameters out of the exgdas script by making it more abstract there and offloading the details into subroutines. Also a possibility is getting the parameters and assorted magic numbers into yaml files.

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres @ShastriPaturi  Any requests for this?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres @ShastriPaturi Any requests for this?

Closing this issue. I think what you've done is good enough for now @AndrewEichmann-NOAA .
