### ISSUE TITLE
Check feature/gdasapp_ufo daily 

### ISSUE THREAD

**Issue by emilyhcliu** [NOAA-EMC/GDASApp#535]
Following the suggestion from[ Issue#526](https://github.com/NOAA-EMC/GDASApp/issues/526).  

Two options from @guillaumevernieres
 1 - revert to develop, those of you who need that branch would just have to swap develop with feature/gdasapp_ufo in the bundle CMakeLists.txt. Easy enough.
2 - Assign somebody to check on a daily basis if ufo develop has been updated, and if so, update the ``feature/gdasapp_ufo`

Let's take option 2.  I will do daily check on feature/gdasapp_ufo against ufo develop and merge if there is an update.
I am sorry about the inconvenience.  I will speed up merging feature/gdasapp_ufo to the develop.

tagging @CoryMartin-NOAA , @ADCollard , @emilyhcliu , @RussTreadon-NOAA, @guillaumevernieres

**Comment by guillaumevernieres** [comment]
Thanks @emilyhcliu

**Comment by emilyhcliu** [comment]
> Thanks @emilyhcliu

@guillaumevernieres Thanks for bearing with me.

**Comment by ADCollard** [comment]
Do we have a branch on `JCSDA-internal` that contains these changes?

If not, I have created https://github.com/JCSDA-internal/ufo/tree/feature/gdasapp_ufo, to move this process forward.  It is already 18 commits behind develop and cannot be automatically updated, but I can address that today.

Running `ctest -R qc` results in three tests failing:
```
The following tests FAILED:
	872 - ufo_test_tier1_test_ufo_amsua_qc_filters (Failed)
	873 - ufo_test_tier1_test_ufo_amsua_qc_filters_geos (Failed)
	875 - ufo_test_tier1_test_ufo_atms_qc_filters (Failed)
```

This does not include any Tier2 tests.

Let's work together to get this done and let's use this issue to keep each other updated.

**Comment by emilyhcliu** [comment]
One question.  Are our JEDI applications in the GDASApp from JCSDA public (not internal)?

**Comment by CoryMartin-NOAA** [comment]
@emilyhcliu all are publicly readable. Some are on 'jcsda-internal' but they are still readable by all. This is so that anyone who checks out GDASApp develop (or feature/stable-nightly) can build regardless of if they have jcsda-internal access.

**Comment by ADCollard** [comment]
I see there is now a `feature/gdasapp_ufo2` branch.   What is this for?  Should I stop using `feature/gdasapp_ufo`?

**Comment by emilyhcliu** [comment]
@ADCollard Yes, I have a branch in JCSDA-internal/ufo to incorporate the changes from feature/gdasapp_ufo.
Don't create the branch in JCSDA-internal/ufo for me.  This confuses me.  

While I am working on my branch in JCSDA-internal/ufo to incorporate changes in feature/gdasapp_ufo (in JCSDA/ufo),  I will do daily check on JCSAD/ufo against JCSDA/develop and merge if necessary.

**Comment by ADCollard** [comment]
OK.  I was just trying to help.

**Comment by emilyhcliu** [comment]
> I see there is now a `feature/gdasapp_ufo2` branch. What is this for? Should I stop using `feature/gdasapp_ufo`?

@ADCollard feature/gdasapp_ufo2 is to add changes I reported in our End-to_End tests.

**Comment by ADCollard** [comment]
@emilyhcliu So should we keep `feature/gdasapp_ufo` for the GDASApp issues or should I delete it?

Just let me know how I can help.
@ADCollard Thanks for helping.  The branch you created will be a good reference for me.  Please keep it for a while.

**Comment by guillaumevernieres** [comment]
@emilyhcliu . @ADCollard , I've been building locally with ufo develop, so it is not a blocking issues yet, but fyi, the `feature/gdasapp_ufo` branch is out of date, and I don't know how the conflict with develop should be resolved. Any chance one of you could have a look?
