### ISSUE TITLE
Interpolate HYCOM SST/SSH onto the MOM6 grid

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#540]
### Workflow
1 - Get the HYCOM surface fields from HPSS (netcdf files, not binary) for the period of July and August 2021
2 - Create a simple python script to interpolate into the MOM6 tripolar grid
3 - Save the interpolated HYCOM fields in netcdf files

**Comment by hyunchul386** [comment]
An interpolation from RTOFS SST in rtofs_glo_2ds_f000_prog.nc (upper) to mom6 grid on 2021-07-04 00Z (lower)


![SST_rtofs 20210704](https://github.com/NOAA-EMC/GDASApp/assets/14810515/d417c99b-4379-4c95-bba9-546b55d61031)

![SST_rtofs2mom6 20210704](https://github.com/NOAA-EMC/GDASApp/assets/14810515/2b9a3665-1e6e-4dc1-97a8-4e0eab5d9fde)



Interpolated SST netcdf file

netcdf rtofs2mom6_sst {
dimensions:
        time = UNLIMITED ; // (1 currently)
        lat = 1080 ;
        lon = 1440 ;
variables:
        float time(time) ;
        float lat(lat) ;
        float lon(lon) ;
        float sst(time, lat, lon) ;
                sst:long_name = "Sea Surface Temperature" ;
                sst:units = "degree C" ;
}

**Comment by hyunchul386** [comment]
An interpolation from RTOFS SSH in rtofs_glo_2ds_f000_diag.nc (upper) to mom6 grid on 2021-07-04 00Z (lower)

![rtofs_ssh_20210704_ori](https://github.com/NOAA-EMC/GDASApp/assets/14810515/85f398c9-ed36-46a6-8bc0-c53e18473bea)

![rtofs2mom6_ssh_20210704](https://github.com/NOAA-EMC/GDASApp/assets/14810515/cf68a90e-f09a-4c5c-a8eb-65659992b15d)

netcdf rtofs2mom6_ssh_20210704 {
dimensions:
        time = UNLIMITED ; // (1 currently)
        lat = 1080 ;
        lon = 1440 ;
variables:
        float time(time) ;
        float lat(lat) ;
        float lon(lon) ;
        float ssh(time, lat, lon) ;
                ssh:long_name = "Sea Surface Elevation" ;
                ssh:units = "m" ;
}

**Comment by hyunchul386** [comment]
On the white line in the interpolated plot, it seems to be due to the graphics, attached is the same interpolated plot by ncview

![Screenshot (127)](https://github.com/NOAA-EMC/GDASApp/assets/14810515/f95af893-6845-449d-8545-423e26d5bf08)

**Comment by hyunchul386** [comment]
and also SSH along x=-179 deg from the interpolated data, and there is no break at the region,

![rtofs2mom6_ssh_20210704_x-179](https://github.com/NOAA-EMC/GDASApp/assets/14810515/6d2071b8-ad11-4a4b-9a66-bcac98e87f28)

**Comment by hyunchul386** [comment]
SSH along X=-179 deg from the interpolated data, and there is no break at the white line region,

![rtofs2mom6_ssh_20210704_x-179b](https://github.com/NOAA-EMC/GDASApp/assets/14810515/c99e516d-c7ce-488c-9e36-5e7146a6fc01)

**Comment by hyunchul386** [comment]
Interpolation of RTOFS SST from rtofs_glo_2ds_n000_diag.nc, have been done for 2021-07~ 2021-08, and can be found at
/scratch1/NCEPDEV/stmp2/Hyun-Chul.Lee/RTOFS/RTOFS2MOM6/
/work/noaa/stmp/hlee/stmp/hlee/RTOFS/RTOFS2MOM6

**Comment by hyunchul386** [comment]
Following are checks for the interpolations;
- First image is the interpolated SST in 2021-07-01
- Second is the interpolated SST in 2021-07-05
- Third one is the original RTOFS in 2021-07-05
- 4th one is the interpolated SST in 2021-07-31
- 5th one is the original RTOFS in 2021-07-31

![image](https://github.com/NOAA-EMC/GDASApp/assets/14810515/0c6c41cb-f40c-4d83-9e72-2a71f0707062)

![image](https://github.com/NOAA-EMC/GDASApp/assets/14810515/8c3c1e4d-1f76-400d-8a95-f8a03f6dfcc2)

![image](https://github.com/NOAA-EMC/GDASApp/assets/14810515/1d1702c8-053e-418c-8294-149890c4abd3)

![image](https://github.com/NOAA-EMC/GDASApp/assets/14810515/9d8be7c3-05d1-4860-95de-1ad0b8f6ac2f)

![image](https://github.com/NOAA-EMC/GDASApp/assets/14810515/b0b07ea5-4953-4254-9a21-a1cb7fdb02eb)

**Comment by hyunchul386** [comment]
Following are similar checks for the interpolations of SSH;
- First image is the interpolated SST in 2021-07-01
- Second is the interpolated SST in 2021-07-05
- Third one is the original RTOFS in 2021-07-05

![ssh_20210701_intp](https://github.com/NOAA-EMC/GDASApp/assets/14810515/e280c566-3a10-4b21-abe0-c839e10ec16f)
![ssh_20210705_intp](https://github.com/NOAA-EMC/GDASApp/assets/14810515/3a940cb0-891d-466a-8ea8-fc1ae1cb2b05)
![ssh_20210705](https://github.com/NOAA-EMC/GDASApp/assets/14810515/1da79223-098d-4c3d-b1c0-5c11cc64b007)
