### ISSUE TITLE
Prepare marine obs from the 6 hourly dump

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#579]
## Description
We want to thin and reformat the recently created 6 hourly marine obs "dump".

## Work plan
The development will be in the g-w, so this issue will have to be moved before the work starts. 

1 - Shastri to copy a few examples of ```6 hourly dumps``` on Hera or /and Orion
2 - Create a specific j-job/ex-script in the g-w 
3 - Create an ocean obs python class
```python
class OceanObservations:
    def __init__(self, window_begin, window_length, DMPDIR, COM_OBS):
        self.window_begin = window_begin
        self.window_length = window_length
        self.DMPDIR = DMPDIR
        self.COM_OBS = COM_OBS
    
    def fetch():
        # copy obs from 6 hourly dumps to RUNDIR
        # Make use of FileHandler to copy

    def convert(self, ...):
         # do common generic stuff
         # Call ioda converter 

    def concatenate(self, ...):
         # 

class AdtObs(OceanObservations):  # Inherit from OceanObservations
    def __init__(self, window_begin, window_length, DMPDIR, COM_OBS, sst_threshold):
        # Call the base class constructor using super()
        super().__init__(window_begin, window_length, DMPDIR, COM_OBS)
        # other stuff that may need to be initialized when processing ADT
        ...
    def convert(self, ...):
         super().convert(...)
         # call adt ioda converter

...
```

This includes creating a new j-job in the global workflow along with making use and inheriting some of the "task" related base classes recently added to the g-w.

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres @ShastriPaturi There is a bit of a name clash with the task names - as I recall (gdas)prep is the equivalent in the current atmospheric cycling but we already have a prep.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres @ShastriPaturi There is a bit of a name clash with the task names - as I recall (gdas)prep is the equivalent in the current atmospheric cycling but we already have a prep.

@AndrewEichmann-NOAA , I'm not sure why there would be a name clash since the task doesn't exist! Just pick a name that makes sense.
`gdasprep` is definitely not descriptive of the task that needs to be developed. How about `ocnobsprep` ?

**Comment by AndrewEichmann-NOAA** [comment]
My initial approach is to have stubs in the jjobs and initial python script, with a g-w ctest in a branch of GDASApp so that it can be readily tested

**Comment by guillaumevernieres** [comment]
> My initial approach is to have stubs in the jjobs and initial python script, with a g-w ctest in a branch of GDASApp so that it can be readily tested

sounds good @AndrewEichmann-NOAA

**Comment by AndrewEichmann-NOAA** [comment]
work with be in `git@github.com:AndrewEichmann-NOAA/global-workflow.git` under branch `feature/prepocniodaobs`, which automatically checks out the GDASApp branch of the same name. I probably need to set some novel permissions in my fork, but the goal is to have following set it up:

```
$  git clone AndrewEichmann-NOAA/global-workflow.git
$  git checkout feature/prepocniodaobs
$  cd global-workflow/sorc
$  ./checkout.sh -u
$ ./build.sh -t hera -c "-DWORKFLOW_TESTS=ON"
```
