### ISSUE TITLE
Netcdf to ioda

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#580]
## Description
The python ioda converters are too slow: Replace with a c++ implementation instead. 

### Converters to implement
- [x] #607
- [x] #608 (@guillaumevernieres @apchoiCMD)
- [x] #609 (@ShastriPaturi )
- [x] #610 (@apchoiCMD)
- [x] #613 (@AndrewEichmann-NOAA )
- [x] #614 (@AndrewEichmann-NOAA )

### Check the conversion
- [x] #665 (@apchoiCMD)
- [x] #677 (@apchoiCMD)

**Comment by ShastriPaturi** [comment]
Input files for the "Marine Obsprep code sprint" are copied to orion here:
`/work2/noaa/stmp/spaturi/forAndrew`

**Comment by guillaumevernieres** [comment]
I think I over-engineered the concatenation ... Oops. I just implemented the serial version of what we now do with mpi gather and it's a lot faster on my laptop, and it doesn't randomly hang. 
I'm testing with the RADS files, which are a lot smaller than anything else that we have to convert:
Reading in ~50 files with a total obs count of ~3M and writing the ioda file took 2.5s ...

**Comment by guillaumevernieres** [comment]
I'll wait until @ShastriPaturi is done with his converter before removing the gather. We have 36 files to process per 6 hour window, each file has 162M obs ...

**Comment by ShastriPaturi** [comment]
@guillaumevernieres,
`There's more, @ShastriPaturi , can you fill in the rest please?`
I do not think there are anymore netcdf files that we will consider, for now.
