### ISSUE TITLE
GDASApp develop build fails with error in utils/soca/gdas_incr_handler.cc

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/GDASApp#589]
Clone GDASApp `develop` at 9fa348f on Orion inside g-w.  Execution of g-w `build_gdas.sh` aborts with
```
8-xgstw63/include -isystem /work/noaa/epic-ps/role-epic-ps/spack-stack/spack-stack-1.3.1/envs/unified-env/install/intel/2022.0.2/hdf5-1.12.2-eefcl5d/include -O2 -g -DNDEBUG -fPIE -qopenmp -std=c++17 -MD -MT gdas-utils/soca/CMakeFiles/gdas_incr_handler.x.dir/gdas_incr_handler.cc.o -MF CMakeFiles/gdas_incr_handler.x.dir/gdas_incr_handler.cc.o.d -o CMakeFiles/gdas_incr_handler.x.dir/gdas_incr_handler.cc.o -c /work2/noaa/da/rtreadon/git/global-workflow/test2/sorc/gdas.cd/gdas-utils/soca/gdas_incr_handler.cc
In file included from /work2/noaa/da/rtreadon/git/global-workflow/test2/sorc/gdas.cd/gdas-utils/soca/gdas_incr_handler.h(25),
                 from /work2/noaa/da/rtreadon/git/global-workflow/test2/sorc/gdas.cd/gdas-utils/soca/gdas_incr_handler.cc(1):
/work2/noaa/da/rtreadon/git/global-workflow/test2/sorc/gdas.cd/gdas-utils/soca/gdas_postprocincr.h(165): error: no instance of constructor "soca::LinearVariableChange::LinearVariableChange" matches the argument list
            argument types are: (const soca::Geometry, soca::LinearVariableChangeParameters)
      soca::LinearVariableChange lvc(this->geom_, params);
                                     ^
/work2/noaa/da/rtreadon/git/global-workflow/test2/sorc/gdas.cd/soca/src/soca/../soca/LinearVariableChange/LinearVariableChange.h(44): \
note: this candidate was rejected because mismatch in count of arguments
  class LinearVariableChange : public util::Printable {
        ^
/work2/noaa/da/rtreadon/git/global-workflow/test2/sorc/gdas.cd/soca/src/soca/../soca/LinearVariableChange/LinearVariableChange.h(55): \
note: this candidate was rejected because arguments do not match
    explicit LinearVariableChange(const Geometry &, const eckit::Configuration &);
             ^

compilation aborted for /work2/noaa/da/rtreadon/git/global-workflow/test2/sorc/gdas.cd/gdas-utils/soca/gdas_incr_handler.cc (code 2)
make[2]: *** [gdas-utils/soca/CMakeFiles/gdas_incr_handler.x.dir/gdas_incr_handler.cc.o] Error 2
```
The `gdas-utils` directory is a soft link to `utils`.  Thus, [`gdas.cd/gdas-utils/soca/gdas_incr_handler.cc`](https://github.com/NOAA-EMC/GDASApp/blob/develop/utils/soca/gdas_incr_handler.cc) is a GDASApp code.  

As a test comment out the following lines in [`utils/soca/CMakeLists.txt`](https://github.com/NOAA-EMC/GDASApp/blob/develop/utils/soca/CMakeLists.txt)

 ```
# Increment post processing
-ecbuild_add_executable( TARGET gdas_incr_handler.x
-                        SOURCES gdas_incr_handler.cc gdas_postprocincr.h)
-target_compile_features( gdas_incr_handler.x PUBLIC cxx_std_17)
-target_link_libraries( gdas_incr_handler.x PUBLIC NetCDF::NetCDF_CXX oops atlas soca)
+#ecbuild_add_executable( TARGET gdas_incr_handler.x
+#                        SOURCES gdas_incr_handler.cc gdas_postprocincr.h)
+#target_compile_features( gdas_incr_handler.x PUBLIC cxx_std_17)
+#target_link_libraries( gdas_incr_handler.x PUBLIC NetCDF::NetCDF_CXX oops atlas soca)
```

With the above change g-w `build_gdas.sh` runs to completion.

It looks like something changed in soca which requires a corresponding change in `/gdas_incr_handler.cc`.

**Comment by guillaumevernieres** [comment]
Thanks for the head's up @RussTreadon-NOAA . Do comment out the soca related problematic code if you have work in the pipeline that you want to merge.

**Comment by RussTreadon-NOAA** [comment]
soca PR [#948](https://github.com/JCSDA-internal/soca/pull/948) changed `src/soca/LinearVariableChange/LinearVariableChange.h`.  It was

```
explicit LinearVariableChange(const Geometry &, const Parameters_ &);
  ~LinearVariableChange();
```
and changed to
```
 explicit LinearVariableChange(const Geometry &, const eckit::Configuration &);
  ~LinearVariableChange();
```

The GDASApp `gdas_postprocincr.h` invokes
```
soca::LinearVariableChange lvc(this->geom_, params);
```

We need to replace the second argument `params` with a configuration.

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres and @CoryMartin-NOAA  , are there any examples in JEDI (SOCA?) which can guide me in replacing `params` with a configuration?  

I made the blind change of replacing `params` with `lvcConfig` in `utils/soca/gdas_postprocincr.h`. 
```
     oops::Log::info() << "======      applying specified change of variables" << std::endl;
-    soca::LinearVariableChangeParameters params;
-    params.deserialize(lvcConfig_);
-    oops::Log::info() <<  params << std::endl;
-    soca::LinearVariableChange lvc(this->geom_, params);
+    eckit::LocalConfiguration lvcConfig_;
+    lvcConfig.deserialize(lvcConfig_);
+    oops::Log::info() <<  lvcConfig << std::endl;
+    soca::LinearVariableChange lvc(this->geom_, lvcConfig);
     oops::Log::info() <<  "traj: " << xTraj_ << std::endl;
```
Compilation still failed but the error message now differs
```
In file included from /work2/noaa/da/rtreadon/git/global-workflow/test2/sorc/gdas.cd/gdas-```
utils/soca/gdas_incr_handler.h(25),
                 from /work2/noaa/da/rtreadon/git/global-workflow/test2/sorc/gdas.cd/gdas-utils/soca/gdas_incr_handler.cc(1):
/work2/noaa/da/rtreadon/git/global-workflow/test2/sorc/gdas.cd/gdas-utils/soca/gdas_postprocincr.h(163): error: identifier "lvcConfig" is undefined
      lvcConfig.deserialize(lvcConfig_);
      ^

compilation aborted for /work2/noaa/da/rtreadon/git/global-workflow/test2/sorc/gdas.cd/gdas-utils/soca/gdas_incr_handler.cc (code 2)
```
I'm fine with tinkering and using google searches but if you have any pointers, they would be much appreciated.

**Comment by jiaruidong2017** [comment]
I got the same issues and hope to get a solution too.

**Comment by RussTreadon-NOAA** [comment]
What have you tried, @jiaruidong2017, to get the code to compile?

**Comment by jiaruidong2017** [comment]
@RussTreadon-NOAA Sorry for the misleading. I did try, but didn't have a solution yet.

**Comment by RussTreadon-NOAA** [comment]
Thanks @jiaruidong2017 .   

With the following changes to `utils/soca/gdas_postprocincr.h`, 
```
     oops::Log::info() << "======      applying specified change of variables" << std::endl;
-    soca::LinearVariableChangeParameters params;
-    params.deserialize(lvcConfig_);
-    oops::Log::info() <<  params << std::endl;
-    soca::LinearVariableChange lvc(this->geom_, params);
+    oops::Log::info() <<  lvcConfig_ << std::endl;
+    eckit::LocalConfiguration lvcConfig_;
+    soca::LinearVariableChange lvc(this->geom_, lvcConfig_);
     oops::Log::info() <<  "traj: " << xTraj_ << std::endl;
```
the g-w `build_gdas.sh` successfully compiles GDASApp 'develop` at 9fa348f.

Not sure if the changes are correct or the resulting code runs correctly, but at least GDASApp builds.

**Comment by RussTreadon-NOAA** [comment]
Create GDASApp branch [`feature/utils_soca`](https://github.com/NOAA-EMC/GDASApp/tree/feature/utils_soca) to which to commit modified `utils/soca/gdas_postprocincr.h`

**Comment by guillaumevernieres** [comment]
Apologies @jiaruidong2017 and @RussTreadon-NOAA .
I can push a fix today, in the meantime, comment out the the build in the cmakelist.txt.
Commenting out that line should do it:
[byebyesocautils](https://github.com/NOAA-EMC/GDASApp/blob/0bc9be8569402123f9aeea61ca608f2c97d2b62b/utils/CMakeLists.txt#L18
)

I have not looked at the issue yet @RussTreadon-NOAA . I don't suspect it's very involved but I have no guidance as of yet. I can work on it now and probably have a tested fix before the end of the day, but let me know if you want to have a go at it ... Always happy to delegate :)

**Comment by guillaumevernieres** [comment]
I'm behind, just saw your PR @RussTreadon-NOAA . Thanks!
