### ISSUE TITLE
marine DA Verfy task takes too long in the ci

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#600]
Comment out or make it faster.6 to 10mn is too long for a test.

**Comment by apchoiCMD** [comment]
#### What we plan to do
- To improve a processing time on Marine VRFY Task
- Run a Python script `statePlotter(config)` in parallel

#### Possible method by using in python
- `multiprocessing`
- `threading`

#### Preliminary Test w/ following conditions
- Profiling of Marine VRFY task : normally 340 ~ 683 sec (Hera and Orion)
- Only run VRFY task with plotting, excluded `eva` stuff in the bottom of script
- Applied to plot sections at background error and ocean increment

| Method |  Machine  |   Runtime          |
|----------|-------------|------------|
| Serial     |    Hera      | 391.73 sec      |
| Multiprocessing      |   Hera   |      299.33 sec     |
| Threading               |   Hera    |    277.37 sec     |

**Comment by apchoiCMD** [comment]
#### Ctests on Hera Machine
#### Before in parallel
```
      Start 20: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY
20/23 Test #20: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY ....   Passed  362.37 sec
```

#### After
```
      Start 20: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY
20/23 Test #20: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY ....   Passed  202.23 sec
```

**Comment by guillaumevernieres** [comment]
@apchoiCMD , I think the timing for the ctests includes the time waiting in the queue, so not good for profiling.

**Comment by apchoiCMD** [comment]
> @apchoiCMD , I think the timing for the ctests includes the time waiting in the queue, so not good for profiling.

Thank you, it is good to know!

**Comment by apchoiCMD** [comment]
#### For more than 20+ tests, profiling shows 240 to 260 sec
```
[Mindo.Choi@hfe01 test_vrfy_speed_up]$ ./exgdas_global_marine_analysis_vrfy_new.py
Elapsed time for Marine VRFY Task: 256.61915826797485 seconds
```

**Comment by guillaumevernieres** [comment]
> #### For more than 20+ tests, profiling shows 240 to 260 sec
> ```
> [Mindo.Choi@hfe01 test_vrfy_speed_up]$ ./exgdas_global_marine_analysis_vrfy_new.py
> Elapsed time for Marine VRFY Task: 256.61915826797485 seconds
> ```

That's fine, but:
1- compared to what?
2- You're running on the login node. Avoid, it's a memory/cpu intensive task so it's annoying for the others logged in `hera01` and since your doing these runs for profiling, the numbers are not very meaningful since you're sharing the node. If you want meaningful timing, you need to sbatch the jobs.

**Comment by apchoiCMD** [comment]
> > #### For more than 20+ tests, profiling shows 240 to 260 sec
> 
> > ```
> 
> > [Mindo.Choi@hfe01 test_vrfy_speed_up]$ ./exgdas_global_marine_analysis_vrfy_new.py
> 
> > Elapsed time for Marine VRFY Task: 256.61915826797485 seconds
> 
> > ```
> 
> 
> 
> That's fine, but:
> 
> 1- compared to what?
> 
> 2- You're running on the login node. Avoid, it's a memory/cpu intensive task so it's annoying for the others logged in `hera01` and since your doing these runs for profiling, the numbers are not very meaningful since you're sharing the node. If you want meaningful timing, you need to sbatch the jobs. 

Thanks for your comment @guillaumevernieres , I forgot what I did when profiling python ioda converters. Yep, will post a meaningful number with sbatch job.

**Comment by apchoiCMD** [comment]
#### Here are sbatch job results on Hera (as of today, Orion scheduled maintenance)

| Sbatch |  Runtime  |   Machine          |
|----------|-------------|------------|
| Before     |    379 sec    |  Hera     |
| After        |    239 sec    |   Hera    |
