### ISSUE TITLE
adding temporal monitoring of regional (a-b)/(o-b) at obs space

### ISSUE THREAD

**Issue by hyunchul386** [NOAA-EMC/GDASApp#603]
- to add temporal monitoring/check of the regression of (o-b) to (a-b) in regional/global obs spaces  
- to add temporal monitoring/check for rmse of (o-b) and (o-a) in regional/global obs spaces

**Comment by hyunchul386** [comment]
- Time Series of regression of (o-b) to (a-b) of SST (metop_a/b/c, viirs-npp) from cp0.b/cp0.a/cp0-a in global, N-H (EQ-60N), S-H (EQ-60S) and HAT10 domain.

![plot_TS_Regressionof(o-b)to(a-b)_SST_Global](https://github.com/NOAA-EMC/GDASApp/assets/14810515/aee7ee4c-58f0-41ef-98ce-9486ce7f2e96)

![plot_TS_Regressionof(o-b)to(a-b)_SST_NH-SubP](https://github.com/NOAA-EMC/GDASApp/assets/14810515/f1604dda-68e1-44c2-85a9-d2703d3a1b10)

![plot_TS_Regressionof(o-b)to(a-b)_SST_SH-SubP](https://github.com/NOAA-EMC/GDASApp/assets/14810515/85467d3a-1bfe-4d72-8c1a-b9feb472a727)

![plot_TS_Regressionof(o-b)to(a-b)_SST_HAT10](https://github.com/NOAA-EMC/GDASApp/assets/14810515/281d39ed-12ed-48a5-87eb-8cfa6a91f823)

**Comment by guillaumevernieres** [comment]
can you explain to us how we should interpret that analysis @hyunchul386 ?

**Comment by guillaumevernieres** [comment]
> can you explain to us how we should interpret that analysis @hyunchul386 ?

BUMP ... I'm still interested in some kind of answer @hyunchul386 .

I am trying to set the monitoring/evaluations for timeseries of regression of of (o-b) to (a-b), which give the evaluation of the gain from the assimilation, regionally and globally. In the recent runs of cp0-a, cp0.a and cp0.b, the regression of (o-b) and (a-b) is different, which show the impacts of the configurations/data changed in the runs to the DA systems.

In addition RMSE of global/regional (o-a) and (o-a) can be evaluated in the cp0 runs for the system improvements.

**Comment by hyunchul386** [comment]
Temporal changes of regress of (o-b) to (a-b) from cp0-a, cp0.a, cp0.b in global, northern SubP (EQ~60N), southern SubP(EQ~60S), HAT10 region,

![plot_TS_Regressionof(o-b)to(a-b)_SST_Global](https://github.com/NOAA-EMC/GDASApp/assets/14810515/7c059334-9342-40f2-a436-359ef0f64ade)

![plot_TS_Regressionof(o-b)to(a-b)_SST_NH-SubP](https://github.com/NOAA-EMC/GDASApp/assets/14810515/d31517fd-d4d7-4bb4-b8c4-c2497f531fad)

![plot_TS_Regressionof(o-b)to(a-b)_SST_SH-SubP](https://github.com/NOAA-EMC/GDASApp/assets/14810515/0c9a8876-4734-46fe-9df2-28ed00cfe3b1)

![plot_TS_Regressionof(o-b)to(a-b)_SST_HAT10](https://github.com/NOAA-EMC/GDASApp/assets/14810515/5dfc06c8-98e2-403a-9dfb-2fc196b9a88d)

**Comment by hyunchul386** [comment]
Temporal changes of regress of (o-b) to (a-b) from cp0-a, cp0.a, cp0.b in global,
northern SubP (EQ - 60N), southern SubP(EQ - 60S), HAT10 region,

![plot_TS_Regressionof(o-b)to(a-b)_SST_Global](https://github.com/NOAA-EMC/GDASApp/assets/14810515/0c4ed750-cf8b-4856-96e9-e31ed2d753d1)

![plot_TS_Regressionof(o-b)to(a-b)_SST_NH-SubP](https://github.com/NOAA-EMC/GDASApp/assets/14810515/b0fba4c8-42e2-466c-b0f2-96af510602de)

![plot_TS_Regressionof(o-b)to(a-b)_SST_SH-SubP](https://github.com/NOAA-EMC/GDASApp/assets/14810515/ce8f256e-664c-4b41-b1d8-ebc651e8cb92)

![plot_TS_Regressionof(o-b)to(a-b)_SST_HAT10](https://github.com/NOAA-EMC/GDASApp/assets/14810515/a47487bb-4587-41f3-9be8-d91823ce50b0)

**Comment by hyunchul386** [comment]
Added RMSE of (a-b)  from cp0-a, cp0.a, cp0.b in global,
northern SubP (EQ - 60N), southern SubP(EQ - 60S), HAT10 region,

![plot_TS_RMSEof(a-b)_SST_Global](https://github.com/NOAA-EMC/GDASApp/assets/14810515/33a99a8c-40bc-4ec2-9723-28d87f161798)

![plot_TS_RMSEof(a-b)_SST_NH-SubP](https://github.com/NOAA-EMC/GDASApp/assets/14810515/706fbefe-32fe-4fe7-ae9c-ec112be96a1f)

![plot_TS_RMSEof(a-b)_SST_SH-SubP](https://github.com/NOAA-EMC/GDASApp/assets/14810515/cf91907b-2ca2-4dcc-837b-447eb7931356)

![plot_TS_RMSEof(a-b)_SST_HAT10](https://github.com/NOAA-EMC/GDASApp/assets/14810515/090cacf8-c106-492c-a905-e7fcfe8e284b)

**Comment by hyunchul386** [comment]
Added RMSE of (o-a) from cp0-a, cp0.a, cp0.b in global,
northern SubP (EQ - 60N), southern SubP(EQ - 60S), HAT10 region,

![plot_TS_RMSEof(o-a)_SST_Global](https://github.com/NOAA-EMC/GDASApp/assets/14810515/b62258f5-120d-4f55-8565-7479f6095c84)

![plot_TS_RMSEof(o-a)_SST_NH-SubP](https://github.com/NOAA-EMC/GDASApp/assets/14810515/9fd7c126-894c-42b0-83ac-81abfc7ed10a)
![plot_TS_RMSEof(o-a)_SST_SH-SubP](https://github.com/NOAA-EMC/GDASApp/assets/14810515/d01091af-f24d-43d3-8de2-b427b5f73d06)

![plot_TS_RMSEof(o-a)_SST_HAT10](https://github.com/NOAA-EMC/GDASApp/assets/14810515/0a9d61b7-7d80-4f25-8157-c9a82faa4bbd)

**Comment by hyunchul386** [comment]
Added RMSE of (o-b) from cp0-a, cp0.a, cp0.b in global,
northern SubP (EQ - 60N), southern SubP(EQ - 60S), HAT10 region,

![plot_TS_RMSEof(o-b)_SST_Global](https://github.com/NOAA-EMC/GDASApp/assets/14810515/74414cbf-91c7-422a-a5ff-191918d2507c)

![plot_TS_RMSEof(o-b)_SST_NH-SubP](https://github.com/NOAA-EMC/GDASApp/assets/14810515/5b1f1bd7-18ed-4c76-bacb-912dbe398182)

![plot_TS_RMSEof(o-b)_SST_SH-SubP](https://github.com/NOAA-EMC/GDASApp/assets/14810515/9e9ce97c-f647-438e-8237-ca961e0bad17)

![plot_TS_RMSEof(o-b)_SST_HAT10](https://github.com/NOAA-EMC/GDASApp/assets/14810515/0f2d7256-1450-4581-bf55-c88dfc7892fd)

**Comment by hyunchul386** [comment]
- In the runs, regres variations show that the increments of cp0.a is most sensitive to (o-b), and the cp0-a is abnormal. 

- In consistent with regres, the RMSE’s of (o-a) of cp0.a/cp0.c/cp0.ocn-da.sst are better than others.

![plot_TS_Regressionof(o-b)to(a-b)_SST_Global](https://github.com/NOAA-EMC/GDASApp/assets/14810515/68cc5fd7-d28e-4c55-8b43-26c3a78adb0c)

![plot_TS_RMSEof(o-a)_SST_Global](https://github.com/NOAA-EMC/GDASApp/assets/14810515/6b20f113-2f7f-451a-aa53-f23a572ccf0f)
