### ISSUE TITLE
Generate 6 hourly observation "cdumps"

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#619]
## Description
We need to generate a few examples of 6 hourly observation "cdumps" that will contain all the observation types that we plan to process during the code sprint (see #580).

See example here:
```
/scratch1/NCEPDEV/stmp4/Shastri.Paturi/forAndrew/gdas.202107[01-02]
```

**Comment by ShastriPaturi** [comment]
Completed
