### ISSUE TITLE
Meridional figures are blank

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#625]
What the title says ...

**Comment by apchoiCMD** [comment]
Need to check it again-

**Comment by apchoiCMD** [comment]
### - bkgerr for Salt and Temp at max depth = 700m ###

![bkgerr_salt](https://github.com/NOAA-EMC/GDASApp/assets/141867620/96fa1214-e3ab-4839-a48e-208a53ce3250)
![bkgerr_temp](https://github.com/NOAA-EMC/GDASApp/assets/141867620/a63f4569-078d-47c5-b0e7-574828eab08e)

**Comment by apchoiCMD** [comment]
### - incr for Salt and Temp at max depth = 700m ###

![incr_salt](https://github.com/NOAA-EMC/GDASApp/assets/141867620/ed4d6ecb-7d56-4abb-b709-8b08d0e0fc52)
![incr_temp](https://github.com/NOAA-EMC/GDASApp/assets/141867620/28888904-a0f6-4937-b842-cbffb3e1a141)
