### ISSUE TITLE
Plot and check original obs vs IODA files for all providers

### ISSUE THREAD

**Issue by ShastriPaturi** [NOAA-EMC/GDASApp#665]
**Write a script in python to:**
- [x] Plot original obs
- [x] Plot IODA file: Cplusplus converter

for all providers

**Comment by apchoiCMD** [comment]
***For RADS to IODA***
![rads_subsample](https://github.com/NOAA-EMC/GDASApp/assets/141867620/01c59435-49bf-4c6f-9d7e-d435fdb3f4b5)
![rads_ioda](https://github.com/NOAA-EMC/GDASApp/assets/141867620/304a7edd-3fbe-4ac1-9723-1472badf616f)

**Comment by apchoiCMD** [comment]
**For ICEC (AMSR2) to IODA**
*Ice Concentration data range below (plots are converted to 0-100 range for comparison)*
- Provider : 0 to 100
- Ioda : 0 to 1

![icec_amsr2_subsample](https://github.com/NOAA-EMC/GDASApp/assets/141867620/c6940b9d-aec5-49df-b618-89008408ee28)
**After Mask (nan values)**
![icec_amsr2_ioda](https://github.com/NOAA-EMC/GDASApp/assets/141867620/b3555ca3-98b5-4873-a4b8-9ac8ff1b44c7)

**Comment by guillaumevernieres** [comment]
Thanks @apchoiCMD .
I'm pretty sure ice concentration should be in [0, 1], not [0, 100]. That's a bug in the converter.

**Comment by apchoiCMD** [comment]
Thanks for the comment and good point! @guillaumevernieres 
For the clarification, information are below,

- Provider : 0 to 100
- Ioda : 0 to 1 

Last two plots are converted to 0-100 for comparison with nan values (3rd plot) that less than 0 to see if there is discrepancy.

**Comment by ShastriPaturi** [comment]
Thanks @apchoiCMD 
Can you do the same for the GHRSST SST?

**Comment by apchoiCMD** [comment]
**For Sea Surface Salinity (SMOS) to IODA**
![sss_smos_subsample](https://github.com/NOAA-EMC/GDASApp/assets/141867620/d902a5ba-7d0a-4d58-9eca-c5ca44acdfde)
![sss_smos_ioda](https://github.com/NOAA-EMC/GDASApp/assets/141867620/6479f03a-d6ed-4af9-a0f1-02b2be542aec)

**Comment by apchoiCMD** [comment]
> Thanks @apchoiCMD Can you do the same for the GHRSST SST?

@ShastriPaturi I don't think GHRSST SST class is in place at develop.

**Comment by apchoiCMD** [comment]
**For Sea Surface Salinity (SMAP) to IODA**
![sss_smap_subsample](https://github.com/NOAA-EMC/GDASApp/assets/141867620/94e92143-5437-4ef4-99f6-a9182838dada)
![sss_smos_ioda](https://github.com/NOAA-EMC/GDASApp/assets/141867620/44e3b021-161e-4304-baa2-2555c2b24afb)

**Comment by guillaumevernieres** [comment]
Great, so far so good!
@apchoiCMD , could you pull develop and rebuild? I just merged the ghrsst PR.

**Comment by apchoiCMD** [comment]
Yes, I am planning to do! @guillaumevernieres Thanks for your efforts on this!

**Comment by apchoiCMD** [comment]
**For Sea Surface Temperature (GHRSST) to IODA w/superobing**

![Capture_two_sub_000](https://github.com/NOAA-EMC/GDASApp/assets/141867620/beccdd78-759a-49b2-b10b-732898e01c4e)
![Capture_two_sub_100](https://github.com/NOAA-EMC/GDASApp/assets/141867620/323819f1-c435-40a4-965e-0126f70cef4b)

**Comment by apchoiCMD** [comment]
***All plots from one full provider netcdf file***
**- Below plots are made ONLY for a visual verification to product from various providers**
**- Providers full netcdf (Left) vs. After IODA Converters (Right)**

**For ADT from RADS**

![Capture_two_adt](https://github.com/NOAA-EMC/GDASApp/assets/141867620/653acf0d-f386-4ae2-b422-1c1279646a72)

**For SSS from SMOS**
 
![Capture_two_smos](https://github.com/NOAA-EMC/GDASApp/assets/141867620/2c6ec362-5c93-434a-aaf1-8037eb2047a9)

**For SSS from SMAP**

![Capture_two_smap](https://github.com/NOAA-EMC/GDASApp/assets/141867620/7abe2982-e75f-4739-9204-685a76c0f640)

**Comment by apchoiCMD** [comment]
***Plots from one full provider netcdf file***
**- Below plots are made ONLY for a visual verification to ICEC from ASMR2**
**- Providers full netcdf (Left) vs. After IODA Converters (Right)**

**For ICEC from AMSR2**

![Capture_two_icec](https://github.com/NOAA-EMC/GDASApp/assets/141867620/ec028e53-7f8b-482e-aae6-0d465d724b75)

**Comment by guillaumevernieres** [comment]
Please check the sst obs before closing @apchoiCMD .

**Comment by apchoiCMD** [comment]
@guillaumevernieres Yes, I will~ thanks for the comment!

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres Yes, I will~ thanks for the comment!

@apchoiCMD , talk to @ShastriPaturi . He just shared a figure with us on slack, I'm pretty sure he is looking into it.

**Comment by apchoiCMD** [comment]
***Plots from one full provider netcdf file***
**- Below plots are made ONLY for a visual verification to Sea Surface Temperature from GHRSST**
**- Providers full netcdf (Left) vs. After IODA Converters (Right) with superobing process**
**- Data Numbers: 162M (Left) vs. 32,402 (Right)**

**For SST from GHRSST**

![sst_ghrsst_two_together](https://github.com/NOAA-EMC/GDASApp/assets/141867620/4581448b-24b1-4984-b78c-d6ac229dff49)

**Comment by apchoiCMD** [comment]
**Validation Process for new IODA converter**

https://docs.google.com/document/d/1NBIJ60SZFKHiLRelUk0AeG6q8Cc7LTG83Cv8zynla9o/edit?usp=sharing

**Comment by apchoiCMD** [comment]
***Obs. Validation for new IODA converter except SST***
**- Data from each 6hours cycle**

![Validation except SST](https://github.com/NOAA-EMC/GDASApp/assets/141867620/628e1541-3e15-4740-ade3-0fd16868a56c)

**Comment by guillaumevernieres** [comment]
Thanks @apchoiCMD , is the table above for multiple input files or just 1? 
I found an issue when concatenating the sst's, I'm working on a fix today.

**Comment by apchoiCMD** [comment]
Above results are in the table with 6 hours cycle (multiple files at each provider) only. @guillaumevernieres Thank you so much for your effort~

**Comment by guillaumevernieres** [comment]
I'm confused again. I don't think I fixed a bug but I did change the code. This is what I get now:
```
binned    , min=-1.8395001888275146, max=27.282995223999023, nobs=17135
not binned, min=-1.9745001792907715, max=27.40949821472168, nobs=251082
```
which seems to make sense. Testing with 2 files only.
I'll submit a PR this am with a few minor changes that should facilitate the testing @apchoiCMD .

**Comment by apchoiCMD** [comment]
@guillaumevernieres Thanks! Just wonder are stride and min number of obs. the same? "nobs" show dramatic reduces. (I am sure depending on two files).

**Comment by apchoiCMD** [comment]
#### Description

Validation for 5 new ioda converters

#### Purpose

- Comparing to old vs. new ioda converters
- To see the obs. values on variables by plotting histograms on each converters
- To see min, max, sum and number of obs.
- dateTime from each setting of epoch time

#### RADS_ADT
#### dateTime has slightly off on histogram, but min and max has constant to old converter.
![RADSADT_alpha_dTime](https://github.com/NOAA-EMC/GDASApp/assets/141867620/5eadca80-f629-4d9b-bc7a-c5621d4c76da)

#### SMOS_SSS
![smos_sss_added_sum](https://github.com/NOAA-EMC/GDASApp/assets/141867620/7718f41f-f541-4bff-b6b2-f2361d4061ef)

#### SMAP_SSS
![smap_sss_added_sum](https://github.com/NOAA-EMC/GDASApp/assets/141867620/4b052772-2526-44d3-9b90-9632b9e8479b)

#### AMSR2_ICEC
#### Have had a bug on obs value "0" without datetime stamp (which mostly are (-) dateTime)
#### Added another trim on converter that ignores more "0"s, seems reduces data 1/4 from original file (see 2nd figure)
#### Do we still need superobing?
![AMSR2ICEC_backto_initial](https://github.com/NOAA-EMC/GDASApp/assets/141867620/03f1d702-7d83-4924-b42e-0611e31989d0)
![AMSR2ICEC_backto](https://github.com/NOAA-EMC/GDASApp/assets/141867620/c7651f48-4bd3-4863-ba08-14166d59cda2)

#### GHRSST
#### Current band-aid works good compared to old converter
#### Current converter stores SST as "Kelvin"
![GHRSST__more_ops_hera](https://github.com/NOAA-EMC/GDASApp/assets/141867620/a1831097-a90c-43a5-970c-a190834a72f8)

**Comment by guillaumevernieres** [comment]
@apchoiCMD ,
1 - For GHRSST: Why do you convert the old sst to C?
2 - It looks like the PreQC flag for smos is wrong
3 - I'd rather just used obs that have a preqc floag of 0 ... What do you think @ShastriPaturi ?

**Comment by apchoiCMD** [comment]
> @apchoiCMD , 1 - For GHRSST: Why do you convert the old sst to C? 2 - It looks like the PreQC flag for smos is wrong 3 - I'd rather just used obs that have a preqc floag of 0 ... What do you think @ShastriPaturi ?

@guillaumevernieres 

1. Figure uploaded was my point of view, just removed and re-posted it
2. old vs. new
- old
```
for i in range(len(lon)):
    if sss_qc[i] <= 150:
       sss_qc[i] = 0
    else:
       sss_qc[i] = 1
```
- new
```
std::vector< uint16_t > sss_qc(iodaVars.location_);
ncFile.getVar("Dg_quality_SSS_corr").getVar(sss_qc.data());
```
Do you want me to mimic what old converter has?

**Comment by ShastriPaturi** [comment]
@guillaumevernieres having a PreQC flag=0 for all obs makes sense but I had added the condition based on the information in the raw SMOS file which mentions that values of >150 for "Dg_quality_SSS_corr" should not be used.
@apchoiCMD can look through the raw data and confirm.

**Comment by guillaumevernieres** [comment]
That's too many figures to look at on github, could you create a google doc and add your figures to it?

**Comment by apchoiCMD** [comment]
@ShastriPaturi I will check to confirm
@guillaumevernieres Yep, I have google slide to take a look! share it soon

**Comment by guillaumevernieres** [comment]
Good enough for the time being. Thanks for doing that work @apchoiCMD , we'll reopen a new issue if we need more evaluation.
