### ISSUE TITLE
The build is failing in `gdas_meanioda.h`.

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#672]
The build is failing in `gdas_meanioda.h`. It's not finding the ```ObsSpace``` constructor.
See recent `ioda` [PR#1121](https://github.com/JCSDA-internal/ioda/pull/1121) . We need to now pass 
```c++
const util::TimeWindow
```
instead of a 
```c++
const util::DateTime
```

_Originally posted by @guillaumevernieres in https://github.com/NOAA-EMC/GDASApp/issues/671#issuecomment-1756493262_

**Comment by guillaumevernieres** [comment]
@CoryMartin-NOAA , do you want to keep the example alive or should we :bomb: it? Seems like a trivial change.

**Comment by CoryMartin-NOAA** [comment]
Yes, I started to fix this yesterday, @guillaumevernieres , will work to fix it today.
