### ISSUE TITLE
Cycle the low-res marine DA on Orion

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#678]
To be able to do this we need to copy the following over to somewhere on Orion:
- [x] ICs
- [x] obs for the testing period of interest
- [x] fix files
- [x] obs for the testing period of interest (new IODA converters and in situ BUFR)

**Comment by ShastriPaturi** [comment]
Set-up GDASApp/g-w,
IC's saved on orion: ` /work2/noaa/da/common/data/ICSDIR/`
Fix files saved on orion: ` /work2/noaa/da/common/data/static`

r2d2 from hera saved on orion: ` /work2/noaa/da/common/r2d2-v3/`
for 20210323-20210325.

Tested 3 cycles from 2021032306. All jobs run including arch and vrfy.
Results not looked at.

**Comment by guillaumevernieres** [comment]
FYI @aerorahul : I forgot exactly what the issue was for your soca ci test in the g-w, but @ShastriPaturi copied the obs and static files on Orion.
