### ISSUE TITLE
Implementation of obs. trimming

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#682]
A trim method was developed by @AndrewEichmann-NOAA but only implemented for a few providers. It also need to be implemented for the following:
- IceAmsr2Ioda
- ~Rads2Ioda~
- Smap2Ioda

**Comment by apchoiCMD** [comment]
### - IceAmsr2Ioda before/after trimming data for 6 hours

| Provider | Num. Files in | Num. Obs. in | Num. Obs. out | Num. Obs. out after trimming |
|----------------------|--------------------|---------------------|------------------|----------------------------|
| AMSR2 (NH & SH) | 10 | 9.04M | 9.04M |             |
| AMSR2 NH only | 5 | 5,512,500  |  | 2,876,046   |
| AMSR2 SH only  | 5 | 3,528,000  |  | 2,811,320   |

![icec_amsr2_ioda_two_together](https://github.com/NOAA-EMC/GDASApp/assets/141867620/bf1136f5-0bed-412e-9dc5-d366a1b9e32b)

### - Smap2Ioda before/after trimming data for 6 hours
- Most of -9999 values from lat, lon and ObsVal are trimmed. (The second plot is a zoom-in of the first plot)

| Provider | Num. Files in | Num. Obs. in | Num. Obs. out | Num. Obs. out after trimming |
|----------------------|--------------------|---------------------|------------------|----------------------------|
| NASA for SMAP | 8 | 493.696  | 493.696 |  |
| NASA for SMAP  | 8 | 493.696  |  | 112,751   |

![Capture_three](https://github.com/NOAA-EMC/GDASApp/assets/141867620/68c7b54a-bba5-4431-ba71-07c375df2193)
