### ISSUE TITLE
Add initial YAML files for surface obs

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/GDASApp#69]
- [ ] sfc
- [ ] sfcship

**Comment by CoryMartin-NOAA** [comment]
@CatherineThomas-NOAA @joshk24 I will try to assign Josh to these once I figure out if I can add him as a 'collaborator'. Here's the first issue, I will make others.

**Comment by joshk24** [comment]
Encountered the same error when trying to generate the netcdf files for both sfc and sfcship plots:

**work2/noaa/stmp/jkumm/gdas_single_test_hofx3d/GDASApp.o6038653
fv3jedi_vc_model2geovals_mod.changevar unknown field: t2m. Not in input field and no transform case specified.**

results in a second netcdf file under "../diags" not being generated, causing the yaml to fail when being run in eva. Cory suggested this could be due using an improper forward operator, but still unclear as of now...

**Comment by CoryMartin-NOAA** [comment]
Assigning myself as a reminder to look into this more in the near future, `sfc` and `sfcship` probably should not use the deprecated GSISfcModel forward operator...
