### ISSUE TITLE
Typo in AMSUA-N19 YAML

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/GDASApp#726]
https://github.com/NOAA-EMC/GDASApp/blob/03fb9d58f7b02aa4d5363ccade9d476592171d32/parm/atm/obs/config/amsua_n19.yaml#L360

**Comment by RussTreadon-NOAA** [comment]
Branch [`feature/amsua_n19`](https://github.com/NOAA-EMC/GDASApp/tree/feature/amsua_n19) created as copy of `develop` at ea9b6d2 .

**Comment by emilyhcliu** [comment]
I will fix this when I open PR for AMSU-A

**Comment by RussTreadon-NOAA** [comment]
@emilyhcliu , can PR #751 move forward?  It's ready to go.
