### ISSUE TITLE
Typo in parm/atm/obs/config/satwind_goes-17.yaml

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/GDASApp#742]
https://github.com/NOAA-EMC/GDASApp/blob/40e81bb07b2d0496c4e276bc04610155ea01123f/parm/atm/obs/config/satwind_goes-17.yaml#L20

differs from

https://github.com/NOAA-EMC/GDASApp/blob/40e81bb07b2d0496c4e276bc04610155ea01123f/parm/atm/obs/config/satwind_goes-16.yaml#L20

The order in `satwind_goes-17.yaml` is reversed compared to `satwind_goes-16.yaml`.   The order in `satwind_goes-16.yaml` is correct.  

This issue is opened to document the typo and its correction.   The correction can be committed to [`feature/gdas-validation-satwind`](https://github.com/NOAA-EMC/GDASApp/blob/feature/gdas-validation-satwind/modulefiles/GDAS/orion.lua)

**Comment by RussTreadon-NOAA** [comment]
@emilyhcliu , a test of the fix is [described](https://github.com/NOAA-EMC/JEDI-T2O/issues/98#issuecomment-1815632229) in JEDI-T2O issue [#98](https://github.com/NOAA-EMC/JEDI-T2O/issues/98).

Would you like me to make the fix in [`feature/gdas-validation-satwind`](https://github.com/NOAA-EMC/GDASApp/blob/feature/gdas-validation-satwind/modulefiles/GDAS/orion.lua), open a PR, and list you as a reviewer?

**Comment by RussTreadon-NOAA** [comment]
The following has been done in a working copy of [feature/gdas-validation-satwind](https://github.com/NOAA-EMC/GDASApp/blob/feature/gdas-validation-satwind/modulefiles/GDAS/orion.lua) on Orion
1. merge `feature/gdas-validation` into `feature/gdas-validation-satwind`
2. correct typo in `parm/atm/obs/config/satwind_goes-17.yaml`

Given your green light, @emilyhcliu , I'll push the updated branch to NOAA-EMC/GDASApp, open a PR, and ask you to review.

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA sorry I saw you also created a branch, whoops! I didn't intend to reproduce work (but it was a quick fix) I think this can be closed now.
