### ISSUE TITLE
Change YAMLs for new window section

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/GDASApp#759]
When JCSDA coordinates their merge of repos (Dec 7 currently?) we will need to update our YAML templates. 

The new format should look like:
```
time window:
  begin: <start datetime>
  length|end: <length|end datetime>
  bound to include: <begin|end (default)>
```

**Comment by guillaumevernieres** [comment]
pinging @ShastriPaturi , @AndrewEichmann-NOAA and @apchoiCMD : The merge is scheduled for Thursday, could one of you submit the fix?
See @travissluka 's fix here: [soca PR#979](https://github.com/JCSDA-internal/soca/pull/979/files)
