### ISSUE TITLE
Add initial YAML files for ozone observations

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/GDASApp#77]
- [x] omi_aura
- [x] ompsnp_npp
- [x] ompstc8_npp

**Comment by joshk24** [comment]
[parm/atm/obs/config/omi_aura.yaml](https://github.com/joshk24/GDASApp/blob/feature/add_ozone_obs/parm/atm/obs/config/omi_aura.yaml)

**Comment by joshk24** [comment]
it's not letting me check the box for some reason :/

**Comment by CoryMartin-NOAA** [comment]
@joshk24 hmm, also that URL link doesn't point to anything, I assume it was supposed to point to a file in a feature branch?
