### ISSUE TITLE
Add the ocean basin flag to all converters

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#775]
See [PR#732](https://github.com/NOAA-EMC/GDASApp/pull/732).

**Comment by apchoiCMD** [comment]
#### Example for Ocean Basin Flag: One full Obs files are used for each plot
![ocean_flag_combined](https://github.com/NOAA-EMC/GDASApp/assets/141867620/51fdd078-afe6-48ca-b3e5-69113ca622a5)
