### ISSUE TITLE
Add IODA converters to prepocnobs task and add to ctest

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/GDASApp#779]
Take existing JGLOBAL_PREP_OCEAN_OBS task, incorporate NetCDF to IODA converters, and create ctest for same

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres I couldn't find an issue to hang the PRs on

**Comment by guillaumevernieres** [comment]
Thanks for the quick turnaround @WalterKolczynski-NOAA and @aerorahul , much appreciated.
