### ISSUE TITLE
Add the ocean basin masks to the fix files

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#782]
Copy  `RECCAP2_region_masks_all_v20221025.nc` from [reccap2 ocean mask](https://reccap2-ocean.github.io/regions/) to the marine DA fix file location.

**Comment by apchoiCMD** [comment]
use below if you want:

`/work2/noaa/da/mchoi3/sandbox/global-workflow/sorc/gdas.cd/build/gdas-utils/test/obsproc/RECCAP2_region_masks_all_v20221025.nc`

**Comment by ShastriPaturi** [comment]
@apchoiCMD, yes I want it.

The `RECCAP2_region_masks_all_v20221025.nc` file is copied to:
Hera: `/scratch2/NCEPDEV/marineda/validation/` and
         `/scratch1/NCEPDEV/da/common/`
Orion: `/work2/noaa/ng-godas/common/validation/`
