### ISSUE TITLE
rocoto_viewer.py fails in role.jedipara

### ISSUE THREAD

**Issue by ShastriPaturi** [NOAA-EMC/GDASApp#784]
The following error occurs:
[role.jedipara@hfe11 c48_test]$ ./rocoto_viewer.py  -d ./c48.test/EXPDIR/c48.test/c48.test.db -w c48.test/EXPDIR/c48.test/c48.test.xml

Usage: rocoto_status_viewer.py  -w workflow.xml -d database.db [--listtasks] [--html=filename.html]

Mandatory arguments:
  -w workflow.xml
  -d database.db
Optional arguments:
  --listtasks             --- print out a list of all tasks
  --html=filename.html    --- creates an HTML document of status
  --help                  --- print this usage message

./c48.test/EXPDIR/c48.test/c48.test.db is not a SQLite3 database file

[role.jedipara@hfe11 c48_test]$ ./rocoto_viewer.py  -w c48.test/EXPDIR/c48.test/c48.test.xml -d ./c48.test/EXPDIR/c48.test/c48.test.db

Usage: rocoto_status_viewer.py  -w workflow.xml -d database.db [--listtasks] [--html=filename.html]

Mandatory arguments:
  -w workflow.xml
  -d database.db
Optional arguments:
  --listtasks             --- print out a list of all tasks
  --html=filename.html    --- creates an HTML document of status
  --help                  --- print this usage message

./c48.test/EXPDIR/c48.test/c48.test.db is not a SQLite3 database file

**Comment by RussTreadon-NOAA** [comment]
@ShastriPaturi , I do not use rocoto_viewer.  I directly use rocoto commands and after things are running OK let cron drive the parallel.   

I'm not surprised rocoto_viewer doesn't work out of the box for role.jedipara.  If rocoto_viewer works from your Hera user account, compare your environment with that of role.jedipara to see what's missing from role.jedipara.

**Comment by ShastriPaturi** [comment]
Thanks @RussTreadon-NOAA, will do.
Closing this.
