### ISSUE TITLE
Updates to ADPSFC, ACFT_PROFILES and conventional ps bufr2ioda python scripts

### ISSUE THREAD

**Issue by nicholasesposito** [NOAA-EMC/GDASApp#785]
Some updates were made to the following bufr2ioda python sripts.

There were a number of changes needed to some of the converter scripts. The changes are outlined in issue #785 .

From that issue:
Some updates were made to the following bufr2ioda python sripts.

1. acft_profiles prepbufr script
      - added units to instantaneousAltitudeRate (should be ms-1)
      - added ObsError for all variables
      - added windEastward to QM
      - dateTime code fix to make it run faster. Missing is now _, 

2. ADPSFC prepbufr script - changes to the SFCSHP script that came up during the code sprint needed to be done to ADPSFC as well
      - I added ObsError for stationPressure. 
      - I edited the height variable down from heightOfStation. 
      - I added stationElevation to MetaData.
      - datetime fix

3. the conventional ps script.
      - Added ObsSubType ([GSI code](https://github.com/NOAA-EMC/GSI/blob/44a8f59ef5cb6def27ba27fcc6a35c074a30332b/src/gsi/read_prepbufr.f90#L693C1-L729C14)) 
      - Added ObsError
      - Added stationElevation to MetaData
      - heightOfStation -> height
      - fixed types
      - ObsError and QM ==0 are changed to "Missing"
      - dateTime codefix. Runs slightly faster. Missing is no longer 0, it is _,

**Comment by emilyhcliu** [comment]
@nicholasesposito These stationPressures are from your conventional_ps converter.  
They look good.  

![sfc_ps](https://github.com/NOAA-EMC/GDASApp/assets/36091766/2208a6a4-8560-48f8-9846-44decf82fa9a)
![sfcship_ps](https://github.com/NOAA-EMC/GDASApp/assets/36091766/e8eb800e-9a73-4347-a5bc-68ec270644ad)
![sonde_ps](https://github.com/NOAA-EMC/GDASApp/assets/36091766/c14e4d2e-3303-4b12-8bd1-7e0ae9a44aa3)

I check the conventional ps IODA obs file.  The stationPressures are comparable to those from [GSI.]( https://docs.google.com/presentation/d/1OvVMYOutxVyk0GE93Jzoh3hQVoj-dCgrwsVWDDlPT1s/edit#slide=id.g27d3030a211_0_0)

**Comment by nicholasesposito** [comment]
I added ObsSubType. I based it on the lines 692 - 726 in the read_prepbufr.f90 code of GSI. I ended up with 6010 data points where subtype ==1, which is the exact same number as GSI. subtype == 0 is substantially larger for my converter but that is due to the way that the group_by function worked with the adpupa data.
