### ISSUE TITLE
Land ctest are failing

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#818]
FYI @jiaruidong2017 .

              @CoryMartin-NOAA , yes it certainly looks like a bufr issue.  I ran `ctest -R test_gdasapp` in a fresh clone and build of GDASApp `develop`.   Only two tests failed
```
        1691 - test_gdasapp_land_apply_jediincr (Failed)
        1692 - test_gdasapp_land_letkfoi_snowda (Failed)
```
Let me compare the hashes for jedi components in `feature/submodule` with the hashes found in the `develop` build.

_Originally posted by @RussTreadon-NOAA in https://github.com/NOAA-EMC/GDASApp/issues/811#issuecomment-1863395195_

**Comment by jiaruidong2017** [comment]
@guillaumevernieres Do you have the log file I can look at? Thanks.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres Do you have the log file I can look at? Thanks.

The last `ci` didn't complain @jiaruidong2017 , so maybe it's just me. No idea where the logs are for land but here's where my build is:
`/scratch1/NCEPDEV/stmp2/Guillaume.Vernieres/runs/ensbw/global-workflow/sorc/gdas.cd/build`
