### ISSUE TITLE
Re-organize the marine obs "dump"?

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#852]
The marine "obs dumps" needs to be reorganized and look like this:
```
|-- 00
|   |-- atmos
|   |-- ocean
|   |   |-- adt
|   |   |-- sss
|   |   |-- icec
|   |   |-- sst
|   |   `-- ...
```

**Comment by ShastriPaturi** [comment]
@guillaumevernieres, what you see is the way the marine obs directories are named.
1. Shouldn't they be?
2. All will be made lower case.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres, what you see is the way the marine obs directories are named.
> 
> 1. Shouldn't they be?
> 2. All will be made lower case.

1 - apple, banana, tractor, orange ...

**Comment by ShastriPaturi** [comment]
Tractor is transporting apple, banana and orange

**Comment by ilianagenkova** [comment]
@guillaumevernieres , 
2. Will make them all lower case, thanks for the input
1.  The marine satellite data (a.k.a marine netcdf data) was put on the same level as "atmo", and in subdirectories (sst, sss, etc) for easier finding it and testing, it was an arbitrary decision. So we currently have:
**gdas.YYYYMMDD/HH/atmos[sst, sss, etc]/file_names.** 
Would your like to see all the 00z sst files (for example) in the /atmos directory among all other dumps (not my preference)? Or would you rather see the directories like that: 
gdas.YYYYMMDD/HH/**atmos/sst**/file_names or may be
gdas.YYYYMMDD/HH/**marine/sst**/file_names ?
Suggest how you'd like to see it and we'll make the change. Thanks.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres , 2. Will make them all lower case, thanks for the input
> 
> 1. The marine satellite data (a.k.a marine netcdf data) was put on the same level as "atmo", and in subdirectories (sst, sss, etc) for easier finding it and testing, it was an arbitrary decision. So we currently have:
>    **gdas.YYYYMMDD/HH/atmos[sst, sss, etc]/file_names.**
>    Would your like to see all the 00z sst files (for example) in the /atmos directory among all other dumps (not my preference)? Or would you rather see the directories like that:
>    gdas.YYYYMMDD/HH/**atmos/sst**/file_names or may be
>    gdas.YYYYMMDD/HH/**marine/sst**/file_names ?
>    Suggest how you'd like to see it and we'll make the change. Thanks.

Thanks for the reply @ilianagenkova , I modified the issue description, after a few back and forth with @CoryMartin-NOAA , we should organize the obs this way :

```
gdas.YYYYMMDD/HH/ocean/sst/file_names 
```
and I vote for dumping the seaice obs under `ocean`

**Comment by ilianagenkova** [comment]
Sounds good! 
Once we get the dev machine back I'll edit the scripts to stage the data like this:
gdas.YYYYMMDD/HH/atmos/*.bufr_d (bathy, tesac, dbuoy,etc)
gdas.YYYYMMDD/HH/ocean/sst/*   (I noticed a bug in the HH for sst on Dogwood, will fix that)
gdas.YYYYMMDD/HH/ocean/adt/*
gdas.YYYYMMDD/HH/ocean/sss/*
gdas.YYYYMMDD/HH/ocean/icec/*

Which data files are you reffering to when you say "seaice"?

**Comment by guillaumevernieres** [comment]
> Sounds good! Once we get the dev machine back I'll edit the scripts to stage the data like this: gdas.YYYYMMDD/HH/atmos/_.bufr_d (bathy, tesac, dbuoy,etc) gdas.YYYYMMDD/HH/ocean/sst/_ (I noticed a bug in the HH for sst on Dogwood, will fix that) gdas.YYYYMMDD/HH/ocean/adt/* gdas.YYYYMMDD/HH/ocean/sss/* gdas.YYYYMMDD/HH/ocean/icec/*
> 
> Which data files are you reffering to when you say "seaice"?

@ilianagenkova , `icec` (sea ice concentration).

**Comment by guillaumevernieres** [comment]
What's the time line to modify our small retrospective "database" @ShastriPaturi ?

**Comment by ShastriPaturi** [comment]
@guillaumevernieres I will need to talk to @ilianagenkova, since she is working on it.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres I will need to talk to @ilianagenkova, since she is working on it.

sure @ShastriPaturi , but in the meantime you can reorganize our retrospective db.

**Comment by ilianagenkova** [comment]
I updated the scripts for the satellite data, in a few hours we should see the /ocean directory: 
gdas.YYYYMMDD/HH/**ocean**/sst[icec, etc]/* 
Next on my list :
-reorganize the earlier satellite data (Dec2023-today) to fit the same /ocean structure
-move the sst /01 , /07 , /13 , /19 directory's data into the 00,06,12,18 (this was a bug resulting from a dump window adjustment)

**Comment by ilianagenkova** [comment]
I no longer see directories name with caps. If I have missed anything, pls point me to these paths.

**Comment by ShastriPaturi** [comment]
@ilianagenkova there are no directories with caps now... all are lower case similar to the schematic in the description.
