### ISSUE TITLE
Make all YAML/jinja templates use consistent variable formatting

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/GDASApp#865]
Now that we are using `wxflow`, we should ensure that all variables are defined in templates consistently.

@aerorahul just to confirm, the preferred approach is `{{ foo }}` for everything, right?

**Comment by aerorahul** [comment]
`{{ foo }}` is the syntax for jinja. 
There may be very few places where one might need to use `!INC ${ENVVAR}` but that is extremely limited.

**Comment by CoryMartin-NOAA** [comment]
Solved with JCB
