### ISSUE TITLE
Time dependent obs error

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#871]

**Comment by apchoiCMD** [comment]
### Preliminary Results for redating and adjusting errors

- Redating obs. date from out of DA window (red box) and adjusting errors (0.1m/ every 6 hours from initial 0.1m)

![Redating compare_with DA Box](https://github.com/NOAA-EMC/GDASApp/assets/141867620/dd2788e2-db19-4c3b-a12b-100a483c54bf)
