### ISSUE TITLE
SST converter is failing

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#881]
I'm not sure what the issue is yet. The ioda converter for sst is segfaulting when ran as part of `test_gdasapp_soca_JGLOBAL_PREP_OCEAN_OB` but runs fine when tested outside ...

**Comment by AndrewEichmann-NOAA** [comment]
related to https://github.com/NOAA-EMC/GDASApp/issues/880 ?

**Comment by AndrewEichmann-NOAA** [comment]
Observations running with bugfix/sst-conversion branched off of feature/obs-window: running both the ctest and "bare", the converter gets past 2018041412-20180414092000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.nc and bombs on the next one:
```
Processing files provided by GHRSST
Reading... 2018041418-20180414151000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.nc
 done subsampling
 done subsampling
 done subsampling
 done subsampling
 done subsampling
OOPS_TRACE[0] IodaVars::IodaVars created.
OOPS_TRACE[0] IodaVars::IodaVars created.
IodaVars::IodaVars done masking.
Traceback (most recent call last):
Floating point exception
```

**Comment by AndrewEichmann-NOAA** [comment]
After commenting out the binning entries in the yaml, it completes successfully

**Comment by guillaumevernieres** [comment]
> After commenting out the binning entries in the yaml, it completes successfully

I was wondering about that yesterday. 
... Thursday Friday Monday Tuesday ... @AndrewEichmann-NOAA ?

**Comment by AndrewEichmann-NOAA** [comment]
> > After commenting out the binning entries in the yaml, it completes successfully
> 
> I was wondering about that yesterday. ... Thursday Friday Monday Tuesday ... @AndrewEichmann-NOAA ?

Blame says those entries came in with the reorg yesterday (Friday)

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres Looking at the calls to https://github.com/NOAA-EMC/GDASApp/blob/develop/utils/obsproc/superob.h from https://github.com/NOAA-EMC/GDASApp/blob/develop/utils/obsproc/Ghrsst2Ioda.h , the same operations are performed on all the fields -  I could see how it would \work, but what are the assumptions behind that? Is there any chance the arrays aren't the same size?

**Comment by guillaumevernieres** [comment]
No clue @AndrewEichmann-NOAA , a problem for Monday. Feel free to comment out the binning in your PR if you want to have sst back.

**Comment by AndrewEichmann-NOAA** [comment]
Apparently not the issue (prints before `return subsampled;`):
```
Processing files provided by GHRSST
Reading... 2018041418-20180414151000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.nc
 minNumObs 10
 subsampled.size() 18
 subsampled[0].size() 36
 count 0
 done subsampling
 minNumObs 10
 subsampled.size() 18
 subsampled[0].size() 36
 count 0
 done subsampling
 minNumObs 10
 subsampled.size() 18
 subsampled[0].size() 36
 count 0
 done subsampling
 minNumObs 10
 subsampled.size() 18
 subsampled[0].size() 36
 count 0
 done subsampling
 minNumObs 10
 subsampled.size() 18
 subsampled[0].size() 36
 count 0
 done subsampling
IodaVars::IodaVars done masking.
Floating point exception
```
