### ISSUE TITLE
More marine obs as part of the default list

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#885]
Add these back to the possible obs spaces:
```
	sst_abi_g16_l3c.yaml
	sst_abi_g17_l3c.yaml
	sst_ahi_h08_l3c.yaml
	sst_metopa_l3u.yaml
	sst_metopc_l3u.yaml
	sst_viirs_n20_l3u.yaml
	sst_viirs_npp_l3u.yaml
```
and test

**Comment by ShastriPaturi** [comment]
@guillaumevernieres what is the time period you are looking to test:
`20180415 or 20210324 or 20210701`

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres what is the time period you are looking to test: `20180415 or 20210324 or 20210701`

```/scratch1/NCEPDEV/stmp2/Guillaume.Vernieres/runs/gw-ci/ci-obs/gdas.20210324/18/ocean```
