### ISSUE TITLE
Update detect_machine.sh to be consistent with UFSWM

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/GDASApp#889]
GDASApp has a copy of `detect_machine.sh` which is not consistent with `detect_machine.sh` in GSI PR [#691](https://github.com/NOAA-EMC/GSI/pull/691).  This issue is opened to work with the g-w team to get the correct `detect_machine.sh` in GDASApp `ush/`.

**Comment by RussTreadon-NOAA** [comment]
@HenryWinterbottom-NOAA and @aerorahul :  from where do we get the official `detect_machine.sh which all EMC repos should be using?

**Comment by aerorahul** [comment]
@RussTreadon-NOAA Since the UFS-weather-model is usually the first component to be ported to a new system, we are treating it as the source for `detect_machine.sh`.
There is a PR in the ufs-weather-model under review at https://github.com/ufs-community/ufs-weather-model/pull/2111/files
One can grab that file from that PR or the global-workflow PR https://github.com/NOAA-EMC/global-workflow/pull/2252

**Comment by RussTreadon-NOAA** [comment]
Thanks @aerorahul .  @HenryWinterbottom-NOAA , shall I assign this issue to you for action at your convenience?

**Comment by HenryRWinterbottom** [comment]
@RussTreadon-NOAA Do you mean, as the `detect_machine.sh` changes within the UFSWM, I am responsible for updating the necessary GW submodules (including the GSI)?

If so, yes -- please assign to me.

**Comment by RussTreadon-NOAA** [comment]
@HenryWinterbottom-NOAA , GDASApp is cloned as a submodule from GW `develop` so I guess updating `ush/detect_machine.sh` in GDASApp is within the  scope of what you are working on.  Feel free to correct me if I'm wrong.

**Comment by RussTreadon-NOAA** [comment]
Assigning this issue to @HenryWinterbottom-NOAA .  If this isn't within the scope of your work, reassign to me and I'll work with others to figure out how to proceed.

**Comment by aerorahul** [comment]
I think @HenryWinterbottom-NOAA can/will make a PR in the GDASapp when he is done with the other components.

**Comment by RussTreadon-NOAA** [comment]
Great!  Thank you @aerorahul and @HenryWinterbottom-NOAA

**Comment by RussTreadon-NOAA** [comment]
Close with merger of PR #890 into `develop`.
