### ISSUE TITLE
fv3jedi_letkf.x fails with RoundRobin error message when processing gnssrobndnbam

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/GDASApp#895]
Attempts to process gnssrobndnbam observations using `fv3jedi_letkf.x` fail with the error message
```
Exception: Bad parameter: Can not use ObsHorLocalization with distribution=RoundRobin
```
This is true whether `fv3jedi_letkf.x` is run either of two modes:
1. run `fv3jedi_letkf.x` in hofx mode.  This execution of `fv3jedi_letkf.x` completes.  Run the executable a second time in solver mode.  `fv3jedi_letkf.x` fails with the above error message.
2. run `fv3jedi_letkf.x` in a single execution running both hofx and the solver.  `fv3jedi_letkf.x` fails with the above error message. 

The gnssrobndnbam file read in these tests is created by the bufr2ioda converter.  

The yaml read by `fv3jedi_letkf.x` does not specify `RoundRobin` for gnssrobndnbam.  However, `RoundRobin` appears in the OOPS_TRACE listing of `fv3jedi_letkf.x`
```
0: OOPS_TRACE[0] Variables::Variables start LocalConfiguration[root={name => gnssrobndnbam , obsdatain => {engine => {type => H5File , obsfile => /scratch1/NCEPDEV/stmp2/role.jedipara/RUNDIRS/prjedi/enkfgdasatmensanl_18/obs/[gdas.t18z.gnssro.tm00.bufr_d.nc](http://gdas.t18z.gnssro.tm00.bufr_d.nc/)}} , obsdataout => {engine => {type => H5File , obsfile => /scratch1/NCEPDEV/stmp2/role.jedipara/RUNDIRS/prjedi/enkfgdasatmensanl_18/diags/diag_gnssro_2021032318.nc4}} , si
mulated variables => (bendingAngle) , distribution => {center => (-50.1859,-32.8329) , radius => 708321}}]
  0: OOPS_TRACE[0] Variables::Variables done
  0: OOPS_TRACE[0] ReaderFactory::createParameters starting
  0: OOPS_TRACE[0] ReaderFactory::createParameters done
  0: OOPS_TRACE[0] WriterFactory::createParameters starting
  0: OOPS_TRACE[0] WriterFactory::createParameters done
  0: OOPS_TRACE[0] ObsSpace<OBS>::ObsSpace starting
  0: OOPS_TRACE[0] Variables::Variables
  0: OOPS_TRACE[0] Variables::Variables
  0: OOPS_TRACE[0] Variables::Variables
  0: OOPS_TRACE[0] Variables::Variables
  0: OOPS_TRACE[0] Variables::Variables
  0: OOPS_TRACE[0] Variables::Variables
  0: OOPS_TRACE[0] Distribution::create starting
  0: OOPS_TRACE[0] Distribution constructed
  0: OOPS_TRACE[0] NonoverlappingDistribution constructed
  0: OOPS_TRACE[0] RoundRobin constructed
  0: OOPS_TRACE[0] Distribution::create done
```

Hofx calculations appear to be successful based on the run time job log.  Problems arise when the solver begins
```
  0: QC gnssrobndnbam bendingAngle: 167212 passed out of 336276 observations.
  0: Beginning core local solver...
  0: OOPS_STATS LocalEnsembleDA before solver            - Runtime:    237.47 sec,  Memory: total:   185.68 Gb, per task: min =   398.71 Mb, max =   746.75 Mb
335: Exception: Bad parameter: Can not use ObsHorLocalization with distribution=RoundRobin
334: Exception: Bad parameter: Can not use ObsHorLocalization with distribution=RoundRobin
```
The input yaml read by `fv3jedi_letkf.x` specifies horizontal localization for observations via
```
    obs localizations:
    - localization method: Horizontal Gaspari-Cohn
      lengthscale: 1250e3
      max nobs: 10000
```

It is not clear at present how to resolve this problem  We are unable to assimilate gnssrobndnbam observations using `fv3jedi_letkf.x` until this problem is resolved.

**Comment by TravisElless-NOAA** [comment]
@RussTreadon-NOAA I think this issue is related to an error in creating the obs yaml setup. I ran with the PSL workflow and haphazardly added the letkf distribution information after the first name like other files, and got the same errors as above. However, after closer examination  https://github.com/NOAA-EMC/GDASApp/blob/develop/parm/atm/obs/config/gnssro.yaml is setup to have the obs operator come first in the yaml and obs space to come 2nd (opposite from other yamls). Moving the distribution section to the obs space section (after line 9 in the above yaml) I was able to get the gnssrobndnbam data to process with the `fv3jedi_letkf.x`. Can you please check if the yaml you are using for this is setup in a similar manner?

**Comment by RussTreadon-NOAA** [comment]
Thank you @TravisElless-NOAA for looking into this.  Moving the `distribution` section into the `obs space` block of the yaml allows `fv3jedi_letkf.x` to run beyond the previous point of failure.   Your explanation of why the previous order was wrong makes sense.  The distribution was being applied to the `obs operator` and not the `obs space`.

**Comment by RussTreadon-NOAA** [comment]
Closing this issue.  The problem was with the placement of the `distribution` section in the `gnssro` yaml.  `fv3jedi_letkf.x` runs OK after moving `distribution` inside `obs space`.
