### ISSUE TITLE
Prepare obs for cycling

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#903]
We need to reformat the current obs "data base" to look like this: ```/scratch1/NCEPDEV/stmp2/Guillaume.Vernieres/runs/gw-ci/ci-obs```

**Comment by ShastriPaturi** [comment]
The obs "data base" reorg at `/scratch1/NCEPDEV/stmp4/Shastri.Paturi/forAndrew` for `gdas.<20210324, 202107??, 202108??>` is completed similar to `/scratch1/NCEPDEV/stmp2/Guillaume.Vernieres/runs/gw-ci/ci-obs`

**Comment by guillaumevernieres** [comment]
thanks @ShastriPaturi
