### ISSUE TITLE
Check the binning of the geostationary sst's

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#905]
Our binning works on the L3 uncollated grid but I have no idea if this is valid for the "collated" product, which is what we use for the geostationary instruments. I presume it's fine, but we should probably check!

Just plotting the input and output binned sst field would be sufficient.

Example here:
```/scratch1/NCEPDEV/stmp2/Guillaume.Vernieres/runs/gw-ci-c384/test/COMROOT/test/gdas.20210702/00/obs```
look for ```gdas.t00z.sst_abi_g16_l3c.2021070200.nc4``` and the corresponding yaml file for the input.

**Comment by AndrewEichmann-NOAA** [comment]
@apchoiCMD I have a tarball of data to look at on Hera under /scratch1/NCEPDEV/da/Andrew.Eichmann/sstcheck

**Comment by apchoiCMD** [comment]
### Input 1:
![Picture1](https://github.com/NOAA-EMC/GDASApp/assets/141867620/049d5b97-2458-4c5d-93ad-8ea1f2285aab)

### Input 2:
![Picture2](https://github.com/NOAA-EMC/GDASApp/assets/141867620/afb2a8b3-bf09-402d-9e16-2113654a40ce)

### .....

### Output including 25 inputs
![all](https://github.com/NOAA-EMC/GDASApp/assets/141867620/72361d91-c771-4e6e-8f91-9628c80afdb1)

**Comment by guillaumevernieres** [comment]
Sorry for not being clear in the issue description @apchoiCMD . What we want to test is if the time stamps between the original and binned observations are consistent.

**Comment by apchoiCMD** [comment]
> Sorry for not being clear in the issue description @apchoiCMD . What we want to test is if the time stamps between the original and binned observations are consistent.

Oh I see, I will update.

**Comment by apchoiCMD** [comment]
### Histogram for DateTime (sec) Stamp
#### - First five inputs (blue block) vs output (colors)
#### - After sst binning and datetime averaging, make datetime stamps off, only green inputs show good match.
![compared_sstcheck_1to5](https://github.com/NOAA-EMC/GDASApp/assets/141867620/24f77095-4412-450a-b5d0-b0813180dd89)

**Comment by apchoiCMD** [comment]
### Starting with just 5 obs.

- DateTime for original obs vs averaging ***DATETIME ONLY*** with original obs

![3vs4](https://github.com/NOAA-EMC/GDASApp/assets/141867620/3c7e174b-4664-4fb7-8445-3e9e47738b22)

- DateTime for original obs vs ***BINNING*** with original obs

![2vs4](https://github.com/NOAA-EMC/GDASApp/assets/141867620/01ab08b9-fddd-47da-b6a3-a8aa5d9ccf3f)

- DateTime for original obs vs ***BINNING and AVERAGING*** with original obs

![1vs4](https://github.com/NOAA-EMC/GDASApp/assets/141867620/2c2c3a56-0cb4-4f52-82da-8ffee1ddffdc)

#### Definitely there is bug subsample2D in superob.h, I am looking into it.
