### ISSUE TITLE
Seaice DA might be "broken"

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#906]
Check if the analysis is applied properly. (see "gw-ci-c384")

**Comment by ShastriPaturi** [comment]
First step:
Plot ice concentration comparisons.
The developer mentions that the seg-faulting is random.

**Comment by guillaumevernieres** [comment]
the random "segfauling" is a separate issue @ShastriPaturi , what I'm curious about here is if the analysis is properly applied.
