### ISSUE TITLE
Recenter ens. members around the deterministic background.

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#912]
The code/application exists (under utils) but is not implemented in the workflow yet. We need to pass recentering increments to the ensemble members.

**Comment by guillaumevernieres** [comment]
Notes:
1 - We only need the initial conditions (MOM.res.nc and cice.res.nc), not need to stage f006 & f009
2 - Create `soca_recenter.yaml` based off of `soca_ensb.yaml`
3 - We need to turn off most of the options of the re-centering ... (@guillaumevernieres 's job)
4 - move the ensemble of increment to the comroot/model_data

**Comment by AndrewEichmann-NOAA** [comment]
in [feature/ocnanalecen](https://github.com/NOAA-EMC/GDASApp/tree/feature/ocnanalecen)

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres Which of I presume the following should be copied back?
```
ocn.ssh_recentering_error.incr.2018-04-15T09:00:00Z.nc
ice.ssh_recentering_error.incr.2018-04-15T09:00:00Z.nc
ocn.steric_explained_variance.incr.2018-04-15T09:00:00Z.nc
ocn.ssh_unbal_stddev.incr.2018-04-15T09:00:00Z.nc
ocn.ssh_total_stddev.incr.2018-04-15T09:00:00Z.nc
ocn.ssh_steric_stddev.incr.2018-04-15T09:00:00Z.nc
ocn.pert.steric.4.nc
ocn.pert.steric.3.nc
ocn.pert.steric.2.nc
ocn.pert.steric.1.nc
ocn.bkgerr_stddev.incr.2018-04-15T09:00:00Z.nc
ice.trash.incr.2018-04-15T09:00:00Z.nc
ice.bkgerr_stddev.incr.2018-04-15T09:00:00Z.nc
```

**Comment by guillaumevernieres** [comment]
I forgot to change the name of the increments ... and we're not outputting sea-ice.
We should copy the ocn.pert.steric*, but they also should be name differently.

**Comment by AndrewEichmann-NOAA** [comment]
@CoryMartin-NOAA Do you know what the increment files should be called when copied back to COM after recentering? Started with (for example) `enkfgdas.20180415/12/mem001/model_data/ocean/restart/gdas.ocean.t12z.incr.nc`

**Comment by CoryMartin-NOAA** [comment]
that's a good start, they shouldn't be in the `restart/` directory though, but rather the `analysis/` directory. I'm not sure what the 'final' naming would be, but that seems good enough for now to me.

**Comment by guillaumevernieres** [comment]
@AndrewEichmann-NOAA , the name should probably match what is currently being done for the deterministic. @CatherineThomas-NOAA , did you keep the logs for the ensemble members failing to find the increment?

**Comment by CatherineThomas-NOAA** [comment]
@guillaumevernieres Yes, I still have the logs.  Here's the what the script is currently looking for:
`enkfgdas.20210324/18/mem001/analysis/ocean/enkfgdas.t18z.ocninc.nc `

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres Yes, I still have the logs. Here's the what the script is currently looking for: `enkfgdas.20210324/18/mem001/analysis/ocean/enkfgdas.t18z.ocninc.nc `

There you go @AndrewEichmann-NOAA , that's the filename you want to use. Thanks @CatherineThomas-NOAA .

**Comment by AndrewEichmann-NOAA** [comment]
Thank you, @CatherineThomas-NOAA , I was getting lost in the forest of current scripts looking for it
