### ISSUE TITLE
Copy 6-hrly marine obs to a common location

### ISSUE THREAD

**Issue by ShastriPaturi** [NOAA-EMC/GDASApp#915]
Hera: `/scratch1/NCEPDEV/da/common`
orion: `/work2/noaa/da/common`

Time period: `2019-01-01 till 2023-06-30`
For the period 2019-2020: SST, SSS are from external site.

Note: 2023-07-01 to real-time are on WCOSS2

**Comment by guillaumevernieres** [comment]
Could we have this asap @ShastriPaturi , now that we are back to cycling ...

**Comment by guillaumevernieres** [comment]
I think this is done?
