### ISSUE TITLE
Need to superob AMSR2 icec 

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#930]
https://github.com/NOAA-EMC/GDASApp/blob/0376c0812952dcdfb5ebaf3b04dbd625225a2def/parm/soca/obsprep/obsprep_config.yaml#L26

We're missing the yaml keys for the binning directive ...

Calibrate the binning visually by comparing the model grid to the obs grid.

**Comment by ShastriPaturi** [comment]
@guillaumevernieres did we not decide to not superob?

**Comment by guillaumevernieres** [comment]
No need to worry about it for now @apchoiCMD . I created the issue to remind myself that I need to add the binning info in the yaml. Fingers crossed that's all that needs to be done.
