### ISSUE TITLE
Better documentation of the obs error adjustment in the RADS converter

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#956]
This:  
https://github.com/NOAA-EMC/GDASApp/blob/a3c3c10a62ac54dde502598129f8b543197325a6/utils/obsproc/Rads2Ioda.h#L31

needs to be documented so the user doesn't have to dig into the code to figure out what's being done.

**Comment by guillaumevernieres** [comment]
Also, we should initialize `errorRatio` here https://github.com/NOAA-EMC/GDASApp/blob/a3c3c10a62ac54dde502598129f8b543197325a6/utils/obsproc/Rads2Ioda.h#L32

or impose to have a value in the `yaml`. Sorry for not catching this in the review.

**Comment by apchoiCMD** [comment]
> Also, we should initialize `errorRatio` here
> 
> https://github.com/NOAA-EMC/GDASApp/blob/a3c3c10a62ac54dde502598129f8b543197325a6/utils/obsproc/Rads2Ioda.h#L32
> 
> or impose to have a value in the `yaml`. Sorry for not catching this in the review.

errRatio was imposed in https://github.com/NOAA-EMC/GDASApp/blob/a3c3c10a62ac54dde502598129f8b543197325a6/utils/test/testinput/gdas_rads2ioda.yaml#L4
Do you want it to be in Rads2Ioda.h ?

**Comment by guillaumevernieres** [comment]
> > Also, we should initialize `errorRatio` here
> > https://github.com/NOAA-EMC/GDASApp/blob/a3c3c10a62ac54dde502598129f8b543197325a6/utils/obsproc/Rads2Ioda.h#L32
> > 
> > or impose to have a value in the `yaml`. Sorry for not catching this in the review.
> 
> errRatio was imposed in
> 
> https://github.com/NOAA-EMC/GDASApp/blob/a3c3c10a62ac54dde502598129f8b543197325a6/utils/test/testinput/gdas_rads2ioda.yaml#L4
> 
> 
> Do you want it to be in Rads2Ioda.h ?

if the yaml key is not present, there is no specific initialization of `errorRatio`.
