### ISSUE TITLE
Remove copyfile here so that we can get rid of solo dependency

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/GDASApp#960]
https://github.com/NOAA-EMC/GDASApp/blob/a3c3c10a62ac54dde502598129f8b543197325a6/ush/socaincr2mom6.py#L29

**Comment by CoryMartin-NOAA** [comment]
Also here:
https://github.com/NOAA-EMC/GDASApp/blob/a3c3c10a62ac54dde502598129f8b543197325a6/scripts/exgdas_global_marine_analysis_prep.py#L24

**Comment by CoryMartin-NOAA** [comment]
@guillaumevernieres Hera going to Rocky8 means we need to change our python env. I'd prefer to use this opportunity to remove dependency on SOLO and R2D2 and other things like that. I'll take a crack at this in the afternoon.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres Hera going to Rocky8 means we need to change our python env. I'd prefer to use this opportunity to remove dependency on SOLO and R2D2 and other things like that. I'll take a crack at this in the afternoon.

sounds good @CoryMartin-NOAA . I'll start working on this today.

**Comment by CoryMartin-NOAA** [comment]
Thanks! I think we may actually be able to get away with the spack-stack without any of our own env to maintain. Which would be fantastic.

**Comment by AndrewEichmann-NOAA** [comment]
@CoryMartin-NOAA  Is the idea to get rid of ufsda entirely?

**Comment by CoryMartin-NOAA** [comment]
yes @AndrewEichmann-NOAA
