### ISSUE TITLE
Wrong resources

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#962]
You introduced a bug yesterday @AndrewEichmann-NOAA :
https://github.com/NOAA-EMC/global-workflow/blob/d7e9bde84aebe922039589bd2bcd65832c1074eb/parm/config/gfs/config.resources#L375

The resources for the DA run are wrong.

**Comment by guillaumevernieres** [comment]
Should be 480 here:
https://github.com/NOAA-EMC/global-workflow/blob/d7e9bde84aebe922039589bd2bcd65832c1074eb/parm/config/gfs/config.resources#L379

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres The memory setting for this entry are messed up too, right?

```
   "ocnanalrun")
     npes=16
-    case ${CASE} in
-      "C384")
-        npes=480
-        memory_ocnanalrun="128GB"
+    case ${OCNRES} in
+      "025")
+        npes=40
+        memory_ocnanalrun="96GB"
         ;;
-      "C96")
+      "050")
         npes=16
+        memory_ocnanalrun="96GB"
         ;;
-      "C48")
+      "500")
         npes=16
-        memory_ocnanalrun="64GB"
+        memory_ocnanalrun="24GB"
         ;;
       *)
-        echo "FATAL ERROR: Resources not defined for job ${job} at resolution ${CASE}"
+        echo "FATAL ERROR: Resources not defined for job ${job} at resolution ${OCNRES}"
         exit 4
     esac
```

**Comment by guillaumevernieres** [comment]
I don't know if messed up is the word, since it does what we want, but yes, memory should have been 96GB. I don't know where I found the 128GB number.
