### ISSUE TITLE
List the obs available in the bufr files and document 

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#965]
Document and list the obs available in the insitu bufr files:
https://github.com/NOAA-EMC/GDASApp/blob/8a6f825f6d988c81fad11070de92a2744d5a53cc/parm/soca/obsprep/obsprep_config.yaml#L152

**Comment by guillaumevernieres** [comment]
Any progress on this @ShastriPaturi ? Except for you, the rest of us are very clueless when it comes to what's in the bufr files, it'd be nice to have this sorted out asap.

**Comment by ShastriPaturi** [comment]
instrument and type of variable observed and whatever else you think might be relevant.

> Any progress on this @ShastriPaturi ? Except for you, the rest of us are very clueless when it comes to what's in the bufr files, it'd be nice to have this sorted out asap.

I have not completed it yet. Will finalize it this week.

**Comment by guillaumevernieres** [comment]
... pinging @ShastriPaturi

**Comment by ShastriPaturi** [comment]
Please see [https://docs.google.com/document/d/1UC_jvJ2ZY4ZmsZ_sqFkNzcXs9Re4rzZuW14UQlf6Khc/edit?pli=1](url)

**Comment by apchoiCMD** [comment]
Here final docs and spreadsheet:
https://docs.google.com/document/d/1UC_jvJ2ZY4ZmsZ_sqFkNzcXs9Re4rzZuW14UQlf6Khc/edit
https://docs.google.com/spreadsheets/d/1CNdCsfagn0nnQkMQqFiA9qEaxBfs6QXI/edit#gid=727950977
