### ISSUE TITLE
How do we want to handle the IODA converter failing on individual sensors?

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/GDASApp#972]
On a cycling tests then GRHSST IODA converter in `ocanobsprep` failed on sensors sst_avhrr_ma_l3u, sst_viirs_npp_l3u, and sst_viirs_n20_l3u. Removing these sensors from the obs list allowed obs prep to complete with the remaining sensors. Do we want the whole task to fail if the IODA converter fails on an individual sensor, or to perform some error handling and carry on?

**Comment by RussTreadon-NOAA** [comment]
Thank you, @AndrewEichmann-NOAA , for opening this issue.  The same question applies to JEDI ATM cycling.
