### ISSUE TITLE
The new R8 python env is missing the f90nml module

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#984]
Reported by @KatherineLukens-NOAA .

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres:  the addition of `load("py-f90nml/1.4.3")` to `modulefiles/GDAS/hera.intel.lua` is not yet in `develop`.  Was this issue closed assuming this change had been merged into `develop`?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres: the addition of `load("py-f90nml/1.4.3")` to `modulefiles/GDAS/hera.intel.lua` is not yet in `develop`. Was this issue closed assuming this change had been merged into `develop`?

Ha! yes, I thought that was sorted out.

**Comment by RussTreadon-NOAA** [comment]
Branch [`RussTreadon-NOAA:feature/hera_rocky8_cleanup`](https://github.com/RussTreadon-NOAA/GDASApp/tree/feature/hera_r8_cleanup) has been created to add `load("py-f90nml/1.4.3")`.  The same branch will also address Rahul's issues #990 and #991.
