### ISSUE TITLE
load_ufsda_modules.sh is unable to find `pip` after gdasapp modulefile is loaded.

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/GDASApp#990]
`global-workflow` jobs running GDASApp jobs loads modules from gdasapp using [load_ufsda_modules.sh](https://github.com/NOAA-EMC/global-workflow/blob/develop/ush/load_ufsda_modules.sh).  
In the test for Hera/Rocky8, it appears that `pip` is not found after loading the Hera modules.
The error message (as seen in a job `gdasprepsnowobs`) is:
```
.../global-workflow/ush/load_ufsda_modules.sh: line 52: pip: command not found
```

A workaround is to comment out the `pip list` line in `load_ufsda_modules.sh` and that works for Hera.
If it is required for ufsDA to list the modules installed via pip (as some are on Orion|Hercules), `pip` should be found on Hera as well.

**Comment by RussTreadon-NOAA** [comment]
Thank you @aerorahul for brining this to our attention.  Looks like we need to load `py-pip/23.1.2` on Hera Rocky 8.

**Comment by RussTreadon-NOAA** [comment]
The addition of `py-pip/23.1.2` to `modulefiles/GDAS/hera.intel.lua` will be done in [`RussTreadon-NOAA:feature/hera_r8_cleanup`](url)
